### ISSUE TITLE
There are still bad ajax forms with no error handling

### ISSUE THREAD

**Issue by NatTuck** [isenseDev/rSENSE#1262]
In several places on the web site AJAX is used to simulate forms in a way that hides errors. These should either be replaced with simple forms or refactored in such a way that the AJAX simulation of form submission is guaranteed to show the same errors that submitting a form would show.

An example is the user bio form.

**Comment by bdonald25** [comment]
Testers: Try and find a place on the website where you can't delete media objects. 
(Projects, Data Sets, News articles, Tutorials, and Visualizations are all the places where media objects exist)

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).
