### ISSUE TITLE
Cubic regression best fit on timeline not working

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1299]
Specifically occurred on this vis last night at the workshop: http://isenseproject.org/visualizations/208

@jaypoulz mentioned something sneaky may be going on with the math, @mmcguinn.

**Comment by kcarcia** [comment]
TESTERS: See #1909 for testing this. You can steal the data from the project in the description to test the cubic regression.

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).
Cubic works, but log isn't.  See http://rsense-dev.cs.uml.edu/visualizations/449

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1 x64).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
