### ISSUE TITLE
Pre-existing fixtures for API tests and mobile apps

### ISSUE THREAD

**Issue by nickavv** [isenseDev/rSENSE#1508]
In order to test certain aspects of the Java API, such as uploading with contributor keys. As far as I can tell the only way to deal with this is if there is some pre-existing project(s) that will exist in any fresh copy of iSENSE that the tests can be guaranteed of the existence of.
If anybody can think of any other ways I'm open to suggestions

**Comment by stowellm** [comment]
@jdalphon and I mentioned this once before - we should set up fixtures for projects/users/etc. that get automatically set up anytime the database is recreated.  This way we can guarantee these objects for the APIs, mobile apps, etc.

**Comment by jdalphon** [comment]
Yes, I have been saying this as well for a while now. Time seems to be the
enemy...never enough of it.

On Thu, Apr 23, 2015 at 11:59 AM, Mike Stowell <notifications@github.com>
wrote:

> @jdalphon <https://github.com/jdalphon> and I mentioned this once before
> - we should set up fixtures for projects/users/etc. that get automatically
> set up anytime the database is recreated. This way we can guarantee these
> objects for the APIs, mobile apps, etc.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/isenseDev/rSENSE/issues/1508#issuecomment-95633292>.
>



-- 
--------------------------------
James Dalphond
UML Computer Science
Engaging Computing Group

**Comment by pat-son** [comment]
This is pretty low priority right now, as no one is actively working on any of the APIs. It could be done if the need arises.

**Comment by doug-salvati** [comment]
Nobody currently working knows entirely what this is about and there is no need at the moment.
Furthermore we would only want fixtures on the dev machine, and the projects/users on there are very likely to never be deleted.
Closing for now.
