### ISSUE TITLE
Show pictures  on map

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#1563]
If I upload pictures with location data I should be able to see the pictures on the map. Right now all I see is a bunch of circles showing where each picture was taken.

**Comment by kcarcia** [comment]
TESTERS: Add pictures to a data set with a location and verify that picture shows up on the map at that location.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).
I labeled this as pass but you may consider this a fail: I visualized two data sets, one with an image and one without.  Pictures on map aren't showing up when I click the marker(s) for the data set with the image.  They only show up when visualizing that single data set.

**Comment by stowellm** [comment]
## My goats migrated from Africa to Greenland

So... I uploaded a goat to a data set with map coordinates in Africa.  When visualizing this data set, my goats show up (although left-aligned!!!).  However, when I visualize this data along with another data set that has no goats (and has points in Greenland)... my goats migrate!  Clicking Africa map points yields no goats, but clicking Greenland points suddenly yields my goats!  *And* they now are even more left-aligned with a gray box to the right.  Let's please keep my goats in Africa.  They prefer the warmer whether.  It's animal cruelty to make them swim that far anyways.

**Comment by kcarcia** [comment]
TESTERS: Do your best to break this! Add pictures to a data set with a location and verify that picture shows up on the map at that location. Also verify you are viewing that data with data that does not contain pictures and preferably has other location area to catch any issue similar to Mike's migrating goats.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
