### ISSUE TITLE
Color picker on summary vis should be removed

### ISSUE THREAD

**Issue by JKinsman** [isenseDev/rSENSE#1569]
One of the interns noted that it seems silly to display the color picker on Summary Vis, since it doesn't actually change anything.  It should probably be removed, since the only thing that could really change is font color, and I can't imagine that would be particularly useful.

**Comment by bdonald25** [comment]
Testers: Make sure color picker does not show up next to the groups on summary vis.

**Comment by tylerpuleo** [comment]
PASSED

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).

**Comment by pat-son** [comment]
PASSED testing on Chrome 48.0.2564.116 (OSX 10.10.5).
