### ISSUE TITLE
Embedded vis cuts off x-axis

### ISSUE THREAD

**Issue by AlanRosenthal** [isenseDev/rSENSE#1574]
live, latest chrome, ubuntu

![image](https://cloud.githubusercontent.com/assets/1288897/3120524/722ba872-e752-11e3-839f-c1d265c8f156.png)

You can't read the x-axis.

**Comment by kcarcia** [comment]
@jaypoulz Am I crazy or does vis 2.0 fix this also? It looks like it does!

**Comment by jaypoulz** [comment]
Yes, yes it does. :)

**Comment by kcarcia** [comment]
TESTERS: Verify the x axis on the embedded vis on the homepage is not cut off.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 42.0.2311.135 (mac).

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
