### ISSUE TITLE
Error messages are formatted inconsistently

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#1617]
![screenshot_2014-06-23-14-06-16](https://cloud.githubusercontent.com/assets/4121924/3361742/b9a443b8-fb01-11e3-8ffc-7eeff4fcdda1.png)
The message for invalid contributor key is labeled "msg". This example is labeled "error". I can not reproduce 404 but it also had a different label.

@jdalphon

**Comment by kcarcia** [comment]
@bdonald25 Any way to test this?

**Comment by bdonald25** [comment]
I don't think there's a quick way for testers to test it. You would have to
make every API call and make them fail in someway, then look at the tag for
the error messages and make sure they are consistent.

**Comment by jaypoulz** [comment]
It's probably sufficient to update the android automatic tests to check for consistency.

**Comment by kcarcia** [comment]
@bdonald25 Would you be able to do that? ^

TESTERS: Don't worry about this.

**Comment by bdonald25** [comment]
@jaypoulz 
Android automatic tests? Those never really became a thing. Jeremy made tests specific to the old apps (Canobie, DataWalk, and Uploader) but the new apps (Motion and Writer) do not have any tests written for them at this point.

The standalone java api test app tests that all the api calls work, and if they don't it will display the error message from the server. However, it does not test every failure case. It uses the java api and makes all of the api calls but it does not extend further than that to test edge cases for bad calls. 

I could extend it to test for failure cases, or I could speak with Jeremy about new automated tests for the new apps.

**Comment by jaypoulz** [comment]
Adding a few calls to the java API test package to verify test failure would be fine. Or you can pawn it off to Jeremy. Your call.

**Comment by kcarcia** [comment]
TESTERS: Don't worry about this.

I realize I already said this but it was kind of hidden.

**Comment by JKinsman** [comment]
FAILED testing on Safari 8.0.3 (Mac OSX 10.10.2).
