### ISSUE TITLE
Vis 2.0 restyle and tool overhaul

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1621]
**General Description**
Here's what I am thinking:

Side bar tools with a UI similiar to:
http://www.highcharts.com/demo/line-basic

I really like the the collapsible panes and a theme like this could persist into fullscreen mode. I also think the tools should be on the left, but I admit that's a pretty radical change.

I think the vis tabs should look more like australis. (Default theme for firefox). By that I mean that the tab should be above the content box, and the active tab merges itself into the content pane background. This way the active tab looks like it owns the box of data, which it essentially does.

The colors should maintain consistency with the other motifs we currently have (bootstrappy and card-like panels).

I'd like to spearhead this when I get back, but would also be fine with bring on someone with good UI sense to help out. @kcarcia might be a good fit for this type of UI review.

What are people's thoughts?

**live/dev/localhost:** All
**iSENSE Version:** v5.4
**Logged in (Y or N):** Either
**Admin (Y or N):** Either

**OS:** All
**Browser/Version:** All

**Steps to Reproduce:** N/a

**Associated Image(s):** See links in the description.

**Comment by stowellm** [comment]
Feedback
- [ ] Media box is super small
- [ ] Zooming in to a timeline causes the message "Mode has been changed to symbols and lines because there were too few points to generate a line" even though it actually only displays lines... and the symbols are hidden until you hover over them ([mode_sym_lines](https://cloud.githubusercontent.com/assets/1039162/7206932/c71b7826-e503-11e4-8f94-5844b3df45e1.png)
)

**Comment by kcarcia** [comment]
TESTERS: Verify all buttons are works. Verify all tools do what they need to do. Tell us what’s not easy to do. Do your best to break this.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 42.0.2311.135 (mac).
Bin size slider on histogram is broken.

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).
Great work Jeremy! :D

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
