### ISSUE TITLE
Field descriptions for edit_fields page

### ISSUE THREAD

**Issue by AlanRosenthal** [isenseDev/rSENSE#1623]
On field edit and creation page, add description for each type of field.

**Comment by kcarcia** [comment]
TESTERS: Please read this and make sure they make sense.

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by stowellm** [comment]
FAILED testing on Chrome 40.0.2214.115 (linux).
For location: "'latitude, longitude' between -90 and 90." Longitude can be between -180 and 180

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.115 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 40.0.2214.115 (linux).
