### ISSUE TITLE
Redo field ordering

### ISSUE THREAD

**Issue by AlanRosenthal** [isenseDev/rSENSE#1631]
**General description:**
We used to have to have timestamp first because of Motion Chart.  Which we no longer have.
The fields should be ordered by the order they are created.

**live/dev/localhost:** Live
**iSENSE Version:** v5.4
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** All
**Browser/Version:** All

**Steps to Reproduce:**
Add fields to a project. Notice that they are not ordered by time of creation.

**Associated Image(s):** None

**Comment by kcarcia** [comment]
Closing as per #2009 - The edit_table form will be rebuilt using Coffeescript and allow users to order their fields.
