### ISSUE TITLE
Side by side histogram vis

### ISSUE THREAD

**Issue by AlanRosenthal** [isenseDev/rSENSE#1633]
**General description:**
Instead of combining histograms, have them side by side.  That way you could compare two different distributions.

This was a request from a teacher at the last workshop.

**live/dev/localhost:** N/a
**iSENSE Version:** N/a
**Logged in (Y or N):** N/a
**Admin (Y or N):** N/a

**OS:** All
**Browser/Version:** All

**Steps to Reproduce:** N/a

**Associated Image(s):** None

**Comment by kcarcia** [comment]
@jaypoulz Should this be closed as per #1897?

**Comment by jaypoulz** [comment]
I think this is actually still valid - you either have 2 histograms as a separate vis altogether OR you have an option for show side-by-side.

**Comment by pat-son** [comment]
We decided against doing this, as it would be too complicated to implement without much added value.
