### ISSUE TITLE
Creating news articles or tutorials without titles is broken

### ISSUE THREAD

**Issue by JKinsman** [isenseDev/rSENSE#1647]
**General Description**
Attempting to create a News Article or Tutorial without entering a value in the name field returns a "Template is missing" error page

**live/dev/localhost:** All
**iSENSE Version:** v5.4
**Logged in (Y or N):** Y
**Admin (Y or N):** Y

**OS:** All
**Browser/Version:** All

**Steps to Reproduce:**
1.  Try to create a news article or tutorial without entering a value in the name field.

**Associated Images:** None

**Comment by jaypoulz** [comment]
TESTERS:
Log in as admin and try creating a tutorial and and news article without a title.

**Comment by JKinsman** [comment]
FAILED testing on Safari 8.0.2 (Mac OSX 10.10).
Exploding Beaker Man! :(

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by kcarcia** [comment]
PASSED testing on Chrome 40.0.2214.91 (mac).

**Comment by stowellm** [comment]
@JKinsman - cannot reproduce on Safari 8.0.2 Mac OSX 10.10.1

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
