### ISSUE TITLE
Update contact info for new employees

### ISSUE THREAD

**Issue by AlanRosenthal** [isenseDev/rSENSE#1659]
**General description:**
http://isenseproject.org/contact

**live/dev/localhost:** N/a
**iSENSE Version:** N/a
**Logged in (Y or N):** N/a
**Admin (Y or N):** N/a

**OS:** All
**Browser/Version:** All

**Steps to Reproduce:** N/a

**Associated Image(s):** None

**Comment by kcarcia** [comment]
TESTERS: Tell us what you like and don't like. Are there typos? How does the page work responsively?

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).
My linked in is wrong:
https://www.linkedin.com/in/asalani

**Comment by kcarcia** [comment]
FAILED testing on Chrome 29.0.1547.57 (mac).
General:
There are inconsistencies:
- Either all degrees should have a comma before the year of not. Mine is like "B.S. Computer Science 2015" while Jeremy's is like "M.S. Computer Science, 2016" Seems like most have the comma, so I'd stick with that.
- With the exception of Nat, I'd put all emails in the blahblahblah AT blahblahblah format.
- It might not be necessary to say student after undergraduate or graduate. Really this is up to you. If you keep it as is, I would add Student to Hassan.

Fred:
Director Student Success -- should this say Director of Student Success?

Jeremy:
Should we give him a more specific manager title? Lab manager? Project manger?

Anthony:
Anthony's linked in link doesn't work.

**Comment by stowellm** [comment]
Thanks for all the feedback, @kcarcia!  Definitely caught some things I missed.  All of the above should now be addressed and is in the pending PR, #1957.  I also got a chance to add Skittles to the contact page as well.

**Comment by kcarcia** [comment]
@stowellm Awesome! Will review first thing when I get in tomorrow!

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
Looks good!  @stowellm if you could add 2015 as my year of graduation, I'd greatly appreciate it! :)
