### ISSUE TITLE
Saved vis formatted wrong

### ISSUE THREAD

**Issue by AlanRosenthal** [isenseDev/rSENSE#1661]
**General description:**
The page should be formatted like a regular vis eg: http://isenseproject.org/projects/29/data_sets/6083.

**live/dev/localhost:** Live
**iSENSE Version:** v5.4
**Logged in (Y or N):** N/a
**Admin (Y or N):** N/a

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:**
1. Visit http://isenseproject.org/visualizations/324.

**Associated Image(s):**
![image](https://cloud.githubusercontent.com/assets/1288897/3725212/8e2644f2-1686-11e4-9367-1b1439475f67.png)

**Comment by JKinsman** [comment]
Great bug for @stowellm to get started on web :D

**Comment by stowellm** [comment]
Assigned to @jaypoulz because he's fixing up vis's and this will be changed in his next PR anyways :smile:
