### ISSUE TITLE
Project description cloning needs to be reworked

### ISSUE THREAD

**Issue by JKinsman** [isenseDev/rSENSE#1668]
**General description:**
If a project with an image in its description is cloned, the newly-cloned project renders the same saved media object.  As a result, deleting the Media Object in the parent (cloned from) project causes the image to stop displaying in the child (newly-cloned) project, despite the fact that the media object is still there.

**live/dev/localhost:** dev/localhost
**iSENSE Version:** 5.4-120
**Logged in (Y or N):** Y
**Admin (Y or N):** N/A

**OS:** N/A
**Browser/Version:** N/A

**Steps to Reproduce:**
1.  Create a Project
2.  Add an image to the description
3.  Clone the project
4.  Visit the original project
5.  Delete the media object
6.  Visit the new project
7.  The media object is there, but the image does not display.

**Associated Image(s):** None

**Comment by jaypoulz** [comment]
TESTERS:
Follow the steps to reproduce to verify that the behavoir is fixed.

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.2 (Mac OSX 10.10).

**Comment by kcarcia** [comment]
PASSED testing on Chrome 40.0.2214.91 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).
