### ISSUE TITLE
Change project title does not work in Internet Explorer

### ISSUE THREAD

**Issue by JKinsman** [isenseDev/rSENSE#1669]
**General description:**
On the project show page, Clicking the "edit title" icon next to the project's title and saving a new title will not actually change the Project Title.

**live/dev/localhost:** dev/localhost
**iSENSE Version:** 5.4-120
**Logged in (Y or N):** Y
**Admin (Y or N):** N/A

**OS:** Windows 8.1
**Browser/Version:** Internet Explorer 11

**Steps to Reproduce:**
In Internet Explorer,
1.  Create a Project
2.  Enter a title
3.  On the project Show Page, attempt to edit the title

**Associated Image(s):** None

**Comment by stowellm** [comment]
@jaypoulz Can this be closed as wontfix?  No one has IE :smile:

**Comment by jaypoulz** [comment]
@stowellm Nope - schools still use i.e. Don was using it at Tyngsboro high when he reproduced it just a month ago. We need to fix this if possible. Testing will require a vm.

**Comment by kcarcia** [comment]
TESTERS: I will pick a designated person to test this.

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
