### ISSUE TITLE
Saving a vis inside fullscreen vis appears broken

### ISSUE THREAD

**Issue by chrisgalster** [isenseDev/rSENSE#1698]
**General description:**
While saving a vis inside a fullscreen vis, the data that you are looking at goes blank, and there is no dialog to save the vis. When you exit the fullscreen mode, the dialog comes up and then you can save the vis.

This should probably do something else. Maybe saving the vis exits fullscreen? 

**live/dev/localhost:** Live
**iSENSE Version:** v5.4
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:** Make a saved vis while in fullscreen mode.

**Associated Image(s):** None

**Comment by stowellm** [comment]
This isn't an issue anymore.  May we close it?  Even if it was an issue, Jeremy's vis2.0 doesn't even have fullscreen anymore.

**Comment by jaypoulz** [comment]
Apparently this magically fixed itself before I even touched anything. I'm calling GG, well played.
