### ISSUE TITLE
Seeds that break testing

### ISSUE THREAD

**Issue by NatTuck** [isenseDev/rSENSE#1703]
**General description:**
With randomized tests, some random seeds cause tests to fail.
@asalani93 is collecting such seeds for later testing.
First seed: 9914

**live/dev/localhost:** N/a
**iSENSE Version:** N/a
**Logged in (Y or N):** N/a
**Admin (Y or N):** N/a

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:**
1. Observe test failures in travis.ci.

**Associated Image(s):** None

**Comment by asalani93** [comment]
This doesn't seem to be an issue anymore, so I'm just going to close it.
