### ISSUE TITLE
Best fit line tooltip disappears after hovering over a data point

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1713]
**General description:**
Jim noticed this a while back. Essentially the tooltips are bound when a regression is created, but unbound whenever a regular data point/line is hovered over.

**live/dev/localhost:** Live
**iSENSE Version:** v5.5
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu
**Browser/Version:** FFox/31

**Steps to Reproduce:**
1. Go to a scatter vis
2. Make a best fit line
3. Hover over a data point
4. Hover over the best fit line - the tooltip is missing

**Associated Image(s):** None

**Comment by kcarcia** [comment]
TESTERS: Please follow the steps to reproduce to test this one. The tooltip when you hover over the best fit line should no longer be missing.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 42.0.2311.135 (mac).

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
