### ISSUE TITLE
Add option in user's page for timezone setting

### ISSUE THREAD

**Issue by AlanRosenthal** [isenseDev/rSENSE#1734]
**General description:**
User timezone setting would be awesome. Timestamp fields would be much easier for teachers to use.

**live/dev/localhost:** N/a
**iSENSE Version:** N/a
**Logged in (Y or N):** N/a
**Admin (Y or N):** N/a

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:** N/a

**Associated Image(s):** None

**Comment by bdonald25** [comment]
Testers: Make sure time stamps on iSENSE are being displayed correctly using your timezone.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
