### ISSUE TITLE
Large spaces between buttons on projects#show when logged out

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#1753]
**General description:**
There's only two buttons when you view a project while logged out, and there's a huge space between the two.

**live/dev/localhost:** live/dev/localhost
**iSENSE Version:** 5.6
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu 14.04
**Browser/Version:** Chrome 36 something

**Steps to Reproduce:**
* log out
* view a project
* observe spaces between buttons

**Associated Image(s):**
![screen shot 2014-09-10 at 11 31 04 am](https://cloud.githubusercontent.com/assets/1798956/4220169/862f83d0-38ff-11e4-8855-5d8ebec7c705.png)

**Comment by asalani93** [comment]
TESTERS: Look at the image above and ensure that it looks worse than what is currently there.

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
PASSED testing on Firefox 40.0 (linux).
