### ISSUE TITLE
Visualizations pop-over tips

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1762]
**General description:**
Bar defaults aren't always the most straightforward. For example, for the dataset a,b,c 1,2,3 one would expect something along the lines of http://rsense-dev.cs.uml.edu/visualizations/336. Instead once gets this http://rsense-dev.cs.uml.edu/projects/681/data_sets/5809. Ideally, bar should try to groupBy whatever label it has on the x-axis.

**UPDATE**: For bar vises with one dataset, we are going alert users to group by the first available text field for a better vis.

**live/dev/localhost:** Live
**iSENSE Version:** v5.6
**Logged in (Y or N):** Yes
**Admin (Y or N):** No

**OS:** Ubuntu
**Browser/Version:** Firefox 31.0

**Steps to Reproduce:**
Visit the links in the description for examples of the desired behavior and the current behavior.

**Associated Image(s):**
Current Default
![current](https://cloud.githubusercontent.com/assets/1039164/4110586/7c09bd92-31f4-11e4-8e79-1787a42fd86c.png)

Desired Default
![desired](https://cloud.githubusercontent.com/assets/1039164/4110591/7fc2ed8c-31f4-11e4-8685-9406b0393c3a.png)

**Comment by doug-salvati** [comment]
Testers: Try on a project with text fields.  Group in a way that creates one bar (a project with one dataset, or combined data sets for instance), and click on the suggestion.  Do the same for a project with several datasets but no text fields.  It should recommend grouping by dataset.

**Comment by doug-salvati** [comment]
PASSED testing on Safari 9.1.3 (mac 10.11.6).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 58.0.3029.110 (mac).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 58.0.3029.110 (mac).
