### ISSUE TITLE
Edit and manual upload table

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1764]
**General description:** The current manual entry/edit table is bad.  Date/time/location currently do not have working pickers, and it slows down significantly when you load a large amount of data.

**live/dev/localhost:** live/dev/localhost
**iSENSE Version:** v5.6
**Logged in (Y or N):** Y/N
**Admin (Y or N):** Y/N
**OS:** All
**Browser/Version:** All
**Steps to Reproduce:** None
**Associated Image(s):** None

**Comment by kcarcia** [comment]
TESTERS: Yay, Slickgrid! Do your best to break the manual entry form.

**Comment by AlanRosenthal** [comment]
http://rsense-dev.cs.uml.edu/projects/211
1) manual entry
2) click new row
3) for lat/long input "12,24"
4) save
5) go back to project
6) click edit
7) lat/long says ","

**Comment by AlanRosenthal** [comment]
if you leave the current time filled in, it says "1 Jan 2015 00:00:00.000 GMT" in the table

**Comment by AlanRosenthal** [comment]
if you leave lat/long blank and go back and edit the dataset it shows "," instead of nothing

**Comment by asalani93** [comment]
I just fixed both of those, thanks for pointing them out.

**Comment by AlanRosenthal** [comment]
Title for /manualEntry and /edit is "Data_sets"

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
Everything looked great! :).. My only thought is that if a user enters invalid data and then clicks save, the data is simply wiped out.  Should we perhaps force them to change (or delete) the data, instead of deleting it and saving before they have the chance to correct the invalid input?

**Comment by kcarcia** [comment]
@JKinsman Will add this to a new issue containing some post-release fixes for Slickgrid.
