### ISSUE TITLE
Testing form UI fix

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1772]
**General description:**
The GitHub links on the testing form do not open in new tabs or windows. This would be super helpful and easy to implement.

**live/dev/localhost:** dev
**iSENSE Version:** N/A
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** N/A
**Browser/Version:** N/A

**Steps to Reproduce:**
1. Go to the testing form on dev.
2. Click the GitHub links, like issue numbers or the GitHub instructions.

**Associated Image(s):**
N/A

**Comment by kcarcia** [comment]
TESTERS: Verify that clicking the links on the testing forms opens those issues in new tabs.

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
