### ISSUE TITLE
Manual testing form does not submit comments if you aren't logged into iSENSE

### ISSUE THREAD

**Issue by JKinsman** [isenseDev/rSENSE#1774]
**General description:**
If a user isn't signed into iSENSE when they click Submit on the Manual Testing Form, they will be redirected to the log in screen.  In that case, no comments will be posted to Github, and all of his or her notes will be deleted.

**live/dev/localhost:** All
**iSENSE Version:** v5.6
**Logged in (Y or N):** N
**Admin (Y or N):**  N

**OS:** Ubuntu
**Browser/Version:** 37.0.2062.120

**Steps to Reproduce:**
1.  Visit rsense-dev.cs.uml.edu/testing **without** logging in.
2.  Fill in the form (including authorization token, user/browser information, etc)
3.  Click Submit
4.  Your comments will not post to Github

**Associated Image(s):**  N/A

**Comment by stowellm** [comment]
Can be closed - visiting the test form while logged out redirects you to the login page *first* so that this doesn't happen.
