### ISSUE TITLE
No pane for tab for "Liked Projects"

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#1795]
**General description:** On the user page, the Liked Projects tab doesn't do anything.

**live/dev/localhost:** live/dev/localhost
**iSENSE Version:** 5.7-74
**Logged in (Y or N):** Y/N
**Admin (Y or N):** Y/N

**OS:** Ubuntu 14.04.1 x64
**Browser/Version:** Chrome 36

**Steps to Reproduce:**
1. Go to a user's page
2. Click on "Projects"
3. Click back to "Liked Projects"
4. Observe as nothing changes

**Associated Image(s):**

**Comment by jaypoulz** [comment]
TESTERS:
Follow the steps to reproduce to verify that the liked projects tab is shown.

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.2 (Mac OSX 10.10).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by kcarcia** [comment]
PASSED testing on Chrome 40.0.2214.91 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).
While this passes for every non-admin user, I found for some reason this is still broken for admin.  Low priority since it only breaks for admins though.

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by kcarcia** [comment]
Still needs to be fixed for admin users.

@stowellm

**Comment by stowellm** [comment]
All set with the above pull request :musical_keyboard:

**Comment by stowellm** [comment]
####TESTERS:####

Login as an admin account and go to the admin's user page.  Click the "My Projects" tab and back to the "Liked Projects" tab.  Ensure they both work and show what they are supposed to.

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1 x64).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
