### ISSUE TITLE
Table y-axis should have a check-all box

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1804]
**General description:**
Table y-axis should have a check-all box. Perhaps visible defaults should be the selected y fields and data point?

**live/dev/localhost:** Live
**iSENSE Version:** v5.7
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04
**Browser/Version:** Firefox 33.0

**Steps to Reproduce:**
Notice the lack of a check all for table y-axis.

**Associated Image(s):** None

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.2 (Mac OSX 10.10).
Table has a check-all box for group selection, but not for visible columns.  I feel like one should be added here too.

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).
Check all box for groups is named "#Check All", check all box for y-axis is named "#Select All" - maybe fix?

**Comment by kcarcia** [comment]
PASSED testing on Chrome 40.0.2214.91 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).
As Anthony already mentioned, one says #check all the other says #select all -- inconsistent

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).
still says SelectAll plz fix

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
