### ISSUE TITLE
Weird Title Sanitization Behavior 

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1824]
**General description:** When you put a < in a title (project, saved vis, etc.), it appears as the HTML entity code (& l t ; - pardon the spaces) when you save it. Oddly enough, this isn't occurring for other characters such as & or >.

**live/dev/localhost:** dev
**iSENSE Version:** v5.8-91-ge3e1326
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** OS X 10.9.4
**Browser/Version:** Chrome v38.0.2125.104

**Steps to Reproduce:**
1. Go to the project you own.
2. Enter "< test" as title.
3. Hit save.

**Associated Image(s):** None

**Comment by jaypoulz** [comment]
@kcarcia would you mind throwing this in testing (patch was merged by Jim)

**Comment by kcarcia** [comment]
TESTERS: Please follow steps to reproduce.

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1 x64).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
