### ISSUE TITLE
When editing project description, clicking on other parts of the page causes you to lose work

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#1828]
**General description:**
Title pretty much says it. If you're editing the project description, and then you click somewhere else, e.g. Edit Fields, the site loses your edits.

**live/dev/localhost:** Live
**iSENSE Version:** N/a
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** All
**Browser/Version:** Any

**Steps to Reproduce:**
Click edit project description, then click edit fields.

**Associated Image(s):** None

**Comment by kcarcia** [comment]
@stowellm Would you feel comfortable addressing this? Not sure what you're queue looks like right now.

**Comment by stowellm** [comment]
Sure - as @kcarcia and I discussed, this can be addressed by a Javascript pop-up that asks the user for confirmation for navigating away if they are currently editing the description so that they don't lose work.

**Comment by stowellm** [comment]
Do we only want this for project description or should it be generalized to any place where we have the summernote editor?  For example, user bio, visualization/data set descriptions, etc.

**Comment by kcarcia** [comment]
TESTERS: The following behavior should occur for any summernote editor:
(1) Type in the editor.
(2) Without saving, click anywhere outside the editor.
An alert should come up asking if you really want to leave the page.

Please be sure to test this anywhere there is summernote. Some places that come to mind: projects page and user page.

Also, be sure to verify this works if you are just adding a text or if you are adding to existing text that is already saved.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
