### ISSUE TITLE
Media block shows up on project vis page

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#1829]
**General description:**
Why does the 'Media' block show up on project vis page? I don't understand why that's there.

**live/dev/localhost:** Live
**iSENSE Version:** N/a
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:**
Got a project's vis page.

**Associated Image(s):** N/a

**Comment by kcarcia** [comment]
@fgmart The current way to add photos to the photo viz is through this media box. If we every re-work photo vis, we can determine if there's a better to prompt users for photos.

**Comment by jaypoulz** [comment]
I love the idea of uploading photos via the photos vis. @stowellm Feel up to it?
