### ISSUE TITLE
iSENSE vises should have a more meaningful tab title

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1834]
**General description:** Every visualization you view says the same up on your browser's tab bar: "iSENSE- Visualizations."  Especially in the case you have multiple visualizations open across tabs, it'd be nice if something like the data set name (or something like "Multiple data sets" if two or more data sets were chosen) was placed as this tab title instead.

**live/dev/localhost:** live
**iSENSE Version:** 5.9
**Logged in (Y or N):** n/a
**Admin (Y or N):** n/a

**OS:** Windows 8.1
**Browser/Version:** Chrome 38

**Steps to Reproduce:** Go to a project with many data sets.  Right click and open each in a new tab. Observe how every tab name is "iSENSE - Visualizations."

**Associated Image(s):**
![isense_tabs](https://cloud.githubusercontent.com/assets/1039162/4877553/249e4e90-62ed-11e4-8908-d7c4adaf9520.png)

**Comment by jaypoulz** [comment]
Testers:
Visit different pages and ensure that they have different titles.

**Comment by JKinsman** [comment]
FAILED testing on Safari 8.0.2 (Mac OSX 10.10).
Viewing a data set shows "iSENSE - Data_sets", and a vis (regardless of the number of data sets, saved or unsaved) says "iSENSE - Visualizations."

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by kcarcia** [comment]
PASSED testing on Chrome 40.0.2214.91 (mac).

**Comment by stowellm** [comment]
@JKinsman - cannot reproduce.  See below image.  Passes for me Safari 8.0.2 OSX 10.10.1.

![screen shot 2015-01-29 at 10 43 08 am](https://cloud.githubusercontent.com/assets/1039162/5960481/b418785c-a7a3-11e4-8a91-3b2f6ff99899.png)

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).

**Comment by kcarcia** [comment]
Once again, I don't think the proper changes were merged onto dev when @JKinsman tested this. We will double-confirm this with a fresh set of testing tomorrow.

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
