### ISSUE TITLE
Annotations for visualizations

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1843]
**General description:**
One of the teachers at the workshop requested the ability to set questions on the screen for a visualization.

**live/dev/localhost:** Live
**iSENSE Version:** N/a
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:** N/a

**Associated Image(s):** None

**Comment by doug-salvati** [comment]
Plan is to allow annotations on a visualization, but we're not building any kind of quizzing/answering system.

**Comment by doug-salvati** [comment]
Testers: Play around and try to break annotations.  See the [video](https://youtu.be/cAYUxuR0_D0) to learn the intended behavior.  Create both types of annotations and try saving a visualization. Put special focus on scatter and add comments to the different fields' points.  Then check/uncheck fields and make sure that each comment remains on its respective field.  Also try disabling points Remember that annotations should persist throughout the visualization session, even when changing tabs and returning.

Also see the [documentation](https://github.com/isenseDev/rSENSE/wiki/Annotations) if necessary.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 59.0.3071.115 (mac).
Tested on Safari and Chrome
