### ISSUE TITLE
Regression lines bounded by data

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1844]
**General description:**
This was originally by design, but Jim noticed that it can be awkward.
Should be redone with regressions.

**live/dev/localhost:** Live
**iSENSE Version:** v5.10
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:**
1. Zoom in.
2. Make a best fit line.

**Associated Image(s):** None

**Comment by stowellm** [comment]
When I zoom out, the regressions don't seem to be bounded by the data.  Can I get confirmation?  If so, close the issue?

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).

**Comment by kcarcia** [comment]
TESTERS: Test regressions on different visualizations with different types of data.

**Comment by stowellm** [comment]
PASSED testing on Chrome 42.0.2311.135 (linux).
DISREGARD THIS IS JUST A TEST

**Comment by bdonald25** [comment]
PASSED testing on Chrome 42.0.2311.135 (mac).

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
