### ISSUE TITLE
Vis with outlier gives better r-squared value

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1845]
**General description:**
A workshop teacher noticed this behavior. Not sure how to reproduce yet, but I'll look into it if I can recreate it.

**live/dev/localhost:** Live
**iSENSE Version:** v5.8
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:**
1. Make a best fit like for a set of points.
2. Add an outlier, and see if it makes it worse.
3. Repeat until reproduced.

**Associated Image(s):** None

**Comment by JKinsman** [comment]
@jaypoulz I was unable to reproduce this bug.

**Comment by kcarcia** [comment]
@jaypoulz @JKinsman This can probably be closed if it cannot be reproduced. Did you look into this, Jeremy?

**Comment by jaypoulz** [comment]
@kcarcia @JKinsman This can be closed assuming it was addressed in @JKinsman's recent regression patch. I remember talking to Jake about what he though was causing the problem, and assuming his patch addresses those concerns, it shouldn't be possible to reproduce this bug in 6.2+ iSENSE.
