### ISSUE TITLE
Office 365 support for uploading data

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1846]
**General description:**
One of the teachers wanted us to look into office 365 support for uploading data.

**live/dev/localhost:** N/a
**iSENSE Version:** N/a
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:** N/a

**Associated Image(s):** None

**Comment by kcarcia** [comment]
Assigning myself to look into this, but marking it as lower priority.

**Comment by kcarcia** [comment]
@stowellm Mike, if you could write what you know about this package here and tag @jdalphon in your response, that would be fabulous.

**Comment by stowellm** [comment]
From what I gathered about Office 365, this is just the name Microsoft applies to the subscription bundle containing Word, Excel, Powerpoint, etc.  By wanting "Office 365" support,  it sounds like really these people want Excel support.  So here's my thoughts:

Excel has a nice feature.  Ya'know, export as CSV.  It just so happens that iSENSE can take CSVs as a file to upload.  Not sure about .xls or .xlsx support though.

Second, even if we were to enable this "Excel support," we'd need a subscription.  Which costs money.  They have a free trial, but only for a month and requires a credit card.  Also, Office 365 is only available for Mac and Windows.  Most of us are on Ubuntu, making development (and testing) hahd.

So overall, I vote **no**.

**Comment by jaypoulz** [comment]
Hmmm. I thought Office 365 referred to an on-line version of Excel. Is that not the case?

**Comment by stowellm** [comment]
I still don't see the need for it.  What are we really asking for support here?  Something like our Google Doc upload where some share link can be used to take an online Excel file to upload?

**Comment by jaypoulz** [comment]
Exactly :)

**Comment by stowellm** [comment]
Solution: export as CSV.

**Comment by jaypoulz** [comment]
Solution: import from URL from Office 360

**Comment by jdalphon** [comment]
Solution: We aren't going to support this at this time. We have very few development cycles in the upcoming months and there is not a high demand for this feature. 

Closing.
