### ISSUE TITLE
Settable min/max for axes

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1849]
**General description:**
Imagine as scatter plot with some y data from 1 to 10. By default x-axis range would be from -1 to 11 or something along these lines. Some teachers want the ability to set hard values for the min/max on the axes.

**live/dev/localhost:** Live
**iSENSE Version:** v5.10
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:** N/a

**Associated Image(s):** None

**Comment by bdonald25** [comment]
Testers: Try setting the bounds of the x-axis and y-axis for scatter.

**Comment by pat-son** [comment]
PASSED testing on Firefox 44.0.2 (Mac OSX Yosemite 10.10.5).
x-axes on Timestamp vis should be a time picker instead of UNIX time. Other than that, it looks good.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).
Works but timestamps should be better than unix timestamps.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).
Works but timestamps should be better than unix timestamps.

**Comment by JasonD94** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).
