### ISSUE TITLE
Best fit lines for individual series

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1850]
**General description:**
Apparently there is a weird rumor going on that best fit lines aren't being linked to individual series. @jaypoulz should look into this.

**live/dev/localhost:** Live
**iSENSE Version:** v5.10
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:**
1. Test best fit lines to see what kind of weird behavior is going on

**Associated Image(s):** None

**Comment by JKinsman** [comment]
Not a bug, per discussion with @jaypoulz .  Turns out I fixed the underlying weird behavior with #1910
