### ISSUE TITLE
Slider selectors for table

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1851]
**General description:**
Some teachers suggested adding sliders for easer filtering in table. This might have some more value now that clipping has been introduced.

**live/dev/localhost:** N/a
**iSENSE Version:** N/a
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:** N/a

**Associated Image(s):** None

**Comment by pat-son** [comment]
Tyler says "Veto"
