### ISSUE TITLE
Group by numerical fields

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1852]
**General description:**
A teacher thought it would be useful for bar charts if you could group by the y-fields themselves. This sometimes makes sense for numerical fields, and should be considered in a grouping overhaul.

**live/dev/localhost:** N/a
**iSENSE Version:** N/a
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:** N/a

**Associated Image(s):** N/a

**Comment by bdonald25** [comment]
Testers: Change the group by options to group by Contributor. Make sure it works for new and old vises, new and old default vises, and new and old saved vises.

Also make sure that all the old saved vises and default vises are the same on live and dev. They should have all the same options for all their tools other than the option to group by contributor. If different things are checked off for a saved vis on live and dev then that is a bug.

**Comment by pat-son** [comment]
PASSED testing on Firefox 44.0.2 (Mac OSX Yosemite 10.10.5).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).
Should not be an option for photo vis though.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).
Should not be an option for photo vis though.

**Comment by JasonD94** [comment]
PASSED testing on Chrome 48.0.2564.97 (Linux Ubuntu 14.04 LTS).

**Comment by bdonald25** [comment]
This pull request needs to be looked at a little more so I am going to hold off until next release.

**Comment by JasonD94** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).
