### ISSUE TITLE
Entering & Exiting FullScreen Breaks the Side Toolbar

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1866]
**General description:** Exiting from fullscreen mode *USING THE ESC KEY ON YOUR KEYBOARD* on a vis causes the toolbar on the side to push further to the right.

**live/dev/localhost:** dev
**iSENSE Version:** v5.8-220-g875ca7e
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Mac
**Browser/Version:** Chrome 39.0.2171.71 (64-bit)

**Steps to Reproduce:** Go to a vis.  Enter full-screen. Exit full-screen *WITH THE ESC KEY*.

**Associated Image(s):** ![screen shot 2014-12-08 at 11 21 58 am](https://cloud.githubusercontent.com/assets/1039162/5342483/7fcc2486-7ecc-11e4-992c-536459618c9d.png)

**Comment by JKinsman** [comment]
FAILED testing on Safari 8.0.2 (Mac OSX 10.10).
Upon exitting full screen, the controls continue to overflow the div on the right-hand side.

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by kcarcia** [comment]
PASSED testing on Chrome 40.0.2214.91 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).

**Comment by kcarcia** [comment]
Now that I think about it, I don't think the proper changes were merged onto dev when @JKinsman tested this. We will double-confirm this with a fresh set of testing tomorrow.

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
