### ISSUE TITLE
Bug Reporting Bug Fixes for v2

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1867]
**General description:** The following issues should be addressed as part of v2 of Bug Reporting:
- [x] <strike>@cur_user should only be set once. (Said by Jim)</strike> Update: this is where it's set.
- [x]  Most of the Authenticator stuff should be in lib/github_authenticator.rb or similar, not directly in the controller. (Said by Jim)
- [x] Increase test coverage back to 90.
- [x] It should not say anonymous user.

**live/dev/localhost:** live
**iSENSE Version:** v5.8-220-g875ca7e
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 39.0.2171.71

**Steps to Reproduce:** You can access bug reporting from the footer.

**Comment by kcarcia** [comment]
TESTERS: Bug reporting on dev should work with and without a GitHub account.

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by kcarcia** [comment]
PASSED testing on Chrome 29.0.1547.57 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
