### ISSUE TITLE
Can View HTML Files as Media Objects

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#1870]
**General description:** Can view HTML files uploaded as media objects

**live/dev/localhost:** live
**iSENSE Version:** v5.8-220-g875ca7e
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Chrome 39.0.2171.71

**Steps to Reproduce:** Uploading HTML files as media objects to projects to see if they break the page.

Uploaded HTML files can run scripts as well.

**Comment by stowellm** [comment]
"Sorry, html is not a supported file type."
Not a bug any more.
May we close?

**Comment by jaypoulz** [comment]
GG well played!
