### ISSUE TITLE
Selecting or Deselecting Fields Removes Filters in Table Vis

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#1875]
**General description:**
Selecting or Deselecting Fields Removes Filters in Table Vis

**live/dev/localhost:** dev
**iSENSE Version:** v5.8
**Logged in (Y or N):** Y/N
**Admin (Y or N):** Y/N

**OS:** Ubuntu 14.04.1 x64
**Browser/Version:** Chrome 39

**Steps to Reproduce:**
* vis a dataset in table
* make sure fields are selected
* apply a sort and/or search to the table
* select or deselect a field
* observe as filters vanish mysteriously

**Associated Image(s):**
nah

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.2 (Mac OSX 10.10).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by kcarcia** [comment]
PASSED testing on Chrome 40.0.2214.91 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
