### ISSUE TITLE
Featured Images on Vis UI Fixes

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1876]
**General description:** The following should be added back now that we feature images on vises:
-  [x] The 'Featured' header would probably be useful now
-  [x] When you select an image, 'Selecting media objects' shows up at the bottom of the screen. This should be removed.

**live/dev/localhost:** live
**iSENSE Version:** v5.8-220-g875ca7e
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 39.0.2171.71

**Steps to Reproduce:** None.

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.2 (Mac OSX 10.10).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by kcarcia** [comment]
PASSED testing on Chrome 40.0.2214.91 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
