### ISSUE TITLE
Photo layout needs rework

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#1895]
**General description:**
Why does the photo layout appear in a single column rather than a grid?

Also, what are the little windowshade bars above each photo?

**live/dev/localhost:** Live
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:**
See attached, from Ivan's cross country bike ride project, http://isenseproject.org/projects/677/data_sets/7240,7239,7238,7237,7236,7235,7234,7232,7231,7230,7229,7228,7227,7226,7225,7224,7223,7222,7221,7220,7219,7218,7176,7175,7174,7173,7172,7168,7167,7166,7165,7164,7156,7155,7154,7150,7149,7147,7140,7139,7138,7137,7136,7135,7134,7133,7132,7131,7130,7129,7127,7126,7124,7123,7121,7120,7119,7118,7117,7115,7114,7111,7110,7109,7108,7107,7106,7105,7104,7103,7102,7101,7094,7093,7092,7091,7090,7089,7088,7087,7086,7085,7057,7056,7055,7054,7053,7052,7051,7050,7049,7006,7005,7004,6977,6976,6975,6962,6960,6959,6958,6957,6956,6955,6954,6953,6952,6948,6947,6946,6896,6895,6894,6893,6892,6882,6881,6877,6876,6875,6874,6871,6870,6869,6868,6867,6866,6865,6864,6863,6862,6748,6747,6746,6740,6739,6738,6737,6729,6728,6727,6725,6724,6723,6722,6721,6720,6715,6714,6713,6688,6687,6686,6685,6682,6681,6678,6677,6676,6645,6644,6643,6640,6639,6638,6637,6635,6634,6633,6632,6622,6621,6620,6619,6618,6617,6594,6593,6592,6584,6583,6582,6581,6580,6579,6578,6577,6576,6575,6563,6562,6561,6555,6554,6553,6552,6551,6550,6549,6548,6544,6542,6541,6540,6539,6538,6537,6536,6535,6534,6533,6532,6531,6530

**Associated Image(s):**
![isense-photo-view](https://cloud.githubusercontent.com/assets/1038856/5454884/5f96b6c0-8504-11e4-9bac-aa40142aaa7d.png)

**Comment by kcarcia** [comment]
TESTERS: Mike made the photo vis beautiful again. Please verify it's working, and it's as beautiful as it could be (so definitely be on the lookout for UI related concerns, too!). It should no longer be one column.

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.115 (linux).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.115 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 40.0.2214.115 (linux).
