### ISSUE TITLE
Error bars on bar chart

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#1896]
**General description:**
It is commonly used in statistics to display error bars on summary bar charts.
E.g, you have a bar that collapses many values into a mean. You get a error bar with one std dev above and one below.

Or the error bar shows the 75th percentile (above mean) and 25th percentile below mean.

This would be a nice feature.

**live/dev/localhost:** N/a
**iSENSE Version:** N/a
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:** N/a

**Associated Image(s):** None

**Comment by stowellm** [comment]
@jaypoulz and/or @fgmart  - To work on this I'll need a face-to-face conversation explaining what we want here and whether or not it is within the scope of my current abilities to work on this.

**Comment by jaypoulz** [comment]
@stowellm Best way to learn vis is just to start doing it :smile_cat: but yes, we will talk in person

**Comment by asalani93** [comment]
TESTERS: Visualize some bar charts and observe that "Mean with Error" shows bar charts with a standard deviation whisker plot thing.  Also, verify that these error bars do not get drawn on pie chart.

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
FAILED testing on Firefox 40.0 (linux).
Breaks for negative (or 0) on logarithmic access

**Comment by bdonald25** [comment]
New bug addressing the problem Jeremy discovered. #2158

**Comment by bdonald25** [comment]
Testers: Visualize some bar charts and observe that "Mean with Error" shows bar charts with a standard deviation whisker plot thing. Also, verify that these error bars do not get drawn on pie chart.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
