### ISSUE TITLE
Histogram as a stacked bar of individual points

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#1897]
**General description:**
For pedagogical reasons, histogram view should be enhanced so that each bar is represented as a stack of individual data items.

This will help people realize what the histogram actually means: for each bin, a count of data elements that fit into that bin.

I realize that some logic will be required to determine how/whether to draw the bar as individual elements; e.g., if there is a bar that's 500px high which represents 1000 elements, the feature should automatically disable.

But assuming it can reasonably be drawn, this would be a big improvement to histogram.

**live/dev/localhost:** N/a
**iSENSE Version:** N/a
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:** N/a

**Associated Image(s):**
![12_01](https://cloud.githubusercontent.com/assets/1038856/5507909/8fabbe0a-8775-11e4-8f1d-faa3e3953ed7.jpg)

**Comment by fgmart** [comment]
Hey all,

This is something I would like to put on the short list. 

Is there a chance that @stowellm can work on this?

Thanks.

**Comment by jaypoulz** [comment]
@fgmart I think @JKinsman would be more comfortable making this type of change for now. Assuming we haven't already added too much to his queue. :smile: Otherwise, we might have to have @stowellm test his mettle against this patch.

**Comment by JKinsman** [comment]
@fgmart @jaypoulz I should have a chance to look into this.  Assuming the regression patch gets merged (once I make the styling change requested), I could do it once I refactor the homepage, which I should be able to finish tonight.

**Comment by kcarcia** [comment]
TESTERS: Try to break historgram!

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).
maybe give each item in the histogram its actual value instead of the column value

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
