### ISSUE TITLE
Resizing columns can break the table

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#1898]
**General description:** Re-sizing columns breaks table.

**live/dev/localhost:** live
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Chrome 39.0.2171.95

**Steps to Reproduce:** If you re-size the columns on a table, it causes the rest of the table to become misaligned. 

![screenshot from 2014-12-19 12 03 51](https://cloud.githubusercontent.com/assets/4121924/5508076/2b363f20-8777-11e4-8498-671ac14bdbcc.png)

393

**Comment by JKinsman** [comment]
FAILED testing on Safari 8.0.2 (Mac OSX 10.10).
Resizing columns forces the next column to become extremely small.  In the worst case, making the columns smaller and then larger can cause columns to become partially cut off.

**Comment by jaypoulz** [comment]
Bah I was hoping updating jqGrid was going to fix this for free. I'll look into this again post the vis layout rework.

**Comment by kcarcia** [comment]
@jaypoulz Jake might have tested this before I pushed to dev. You might want to verify this is still an issue.

**Comment by jaypoulz** [comment]
@kcarcia Good point - but I think I recall @bdonald25 showing me that it was still a bug.

**Comment by bdonald25** [comment]
Yep, it's still there on live.

**Comment by bdonald25** [comment]
This bug no longer exists. I believe it was fixed when #2161 was fixed. 
Chrome must have been having issues with inheriting the width that was causing weird side effects when rendering vises.
