### ISSUE TITLE
API Posting Dataset 

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#1904]
**General description:** When posting datasets with the API the first field sets the size of the dataset so if the second field is longer it gets truncated.

**live/dev/localhost:** dev
**iSENSE Version:** v5.8-238-g084b967
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04
**Browser/Version:** Chrome 39.0.2171.95

**Steps to Reproduce:** Make a post request to a project where the second field is longer.

**Comment by tylerpuleo** [comment]
@bdonald25

**Comment by kcarcia** [comment]
TESTERS: Don't worry about this.
