### ISSUE TITLE
Exponential regressions are broken.

### ISSUE THREAD

**Issue by JKinsman** [isenseDev/rSENSE#1909]
**General description:** Trying to create an exponential regression results in an alert box displaying an error message that the model was unable to create an exponential model for the data, even when the data is inherently exponential in nature.

**live/dev/localhost:** live
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Chrome 38.0.2125.101

**Steps to Reproduce:** 

315

**Comment by kcarcia** [comment]
TESTERS: @JKinsman worked his math magic to fix linear, quadratic, cubic, exponential, and logarithmic regressions on both Timeline and Scatter. To test this and #1299, please test the various types of regressions.

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).
Mostly works - I ran into one instance I couldn't draw an exponential but can't seem to reproduce it now.

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1 x64).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
