### ISSUE TITLE
Admin can press a "Delete" button on a project with data sets with no feedback as to why it failed

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1912]
**General description:** An admin that owns a project with data sets can either navigate to the project's edit page or the admin's projects on the profile page and have the Delete button show up.  However, in both cases, the delete fails since the project contains data sets.  There is no feedback as to why clicking delete does nothing.

**live/dev/localhost:** dev
**iSENSE Version:** v5.8-238-g084b967
**Logged in (Y or N):** Y
**Admin (Y or N):** Y

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 39.0.2171.95

**Steps to Reproduce:**
1. Log in as admin
2. Create a project
3. Add a number field to the project and save
4. Add a data set (one row suffices) and save

Path A:
5. Navigate back to this project's page
6. Click edit
7. Click delete.  Note it did not delete and there is no error pop-up

Path B:
5. Navigate to the admin's profile
6. Click the "My Projects" tab
7. Click delete on the project you just created.  Note it did not delete and there is no error pop-up

**Associated Image(s):**

**Comment by stowellm** [comment]
### TESTERS:

Hi :)

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.2 (Mac OSX 10.10).
I feel like this should be an alert at the top of the page, but there was in fact an error message on the page (under the delete button).

**Comment by asalani93** [comment]
FAILED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).
Now I get exploding beaker man.

**Comment by kcarcia** [comment]
FAILED testing on Chrome 29.0.1547.57 (mac).
Path A: you get the exploding beaker man when you try to delete a project.
Path B: clicking delete is doing nothing at all.

**Comment by kcarcia** [comment]
@stowellm I'm removing this from testing.

**Comment by stowellm** [comment]
@kcarcia :
Path A: that's strange... I'll look into it.
Path B: cannot reproduce.  I can delete a project with no data sets from the admin's user page.  Could you show me how you got this to break?  Even so, I've definitely noticed that before my patch - sometimes clicking delete didn't remove the project from the profile page.

**Comment by kcarcia** [comment]
@stowellm Absolutely will look into path B tomorrow with you.

**Comment by jaypoulz** [comment]
@kcarcia
@stowellm  is correct. I messed this up, and I don't think there was real intention to fix something different here. I was just refactoring, but I accidentally forgot the whole 'can_delete' case.

Here is an alternative version that might fix this.
```
<% del = '<i class="fa fa-times-circle"></i> Delete Project ' %>
<% cls = 'btn btn-danger'; if can_delete? @project then cls += ' disabled' end %>
 <%= link_to raw(del),
    @project,
    { method: :delete, data: { confirm: 'Really delete project?' },
    class: cls } %>
```

**Comment by jaypoulz** [comment]
@stowellm do you want to patch this up or do you want me to do it? (since I broke it) :stuck_out_tongue_closed_eyes:

**Comment by stowellm** [comment]
@jaypoulz - I've patched it and will submit a PR shortly.  Btw, needed to change the line:
`<% cls = 'btn btn-danger'; if can_delete? @project then cls += ' disabled' end %>`
to:
`<% cls = 'btn btn-danger'; if !can_delete? @project then cls += ' disabled' end %>`
:camel:

**Comment by kcarcia** [comment]
TESTERS: Please test both paths discussed listed in Steps to Reproduce in description above.

**Comment by kcarcia** [comment]
@stowellm I can't reproduce my issue with path B. I was testing on a very outdated browser, so that could have been the problem.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
