### ISSUE TITLE
TypeError when trying to report a bug on localhost

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1919]
**General description:** I tried submitting a bug through the 'Report a Bug' feature on the website.  I selected the option that I do have a Github account, and I got this terrifying error page (see below).

**live/dev/localhost:** localhost
**iSENSE Version:** v5.12-83-g45977b5
**Logged in (Y or N):** Y
**Admin (Y or N):** either, but was admin at the time

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome Version 39.0.2171.99 (64-bit)

**Steps to Reproduce:**
1. Go to 'Report a Bug' at the bottom of the page
2. Choose that you have a Github account
3. Break

**Associated Image(s):**
![github_died_on_localhost](https://cloud.githubusercontent.com/assets/1039162/5758775/3b5695ec-9c96-11e4-90b8-fc598b115b57.png)

**Comment by asalani93** [comment]
Reporting a bug from localhost shouldn't be possible - it requires
environment variables that you don't have.

**Comment by jaypoulz** [comment]
As noted by @asalani93, you cannot report a bug on local host. It doesn't even make much sense to, because a local host bug could be a manifestation of your current build and environment.
