### ISSUE TITLE
Bad redirection when reporting a bug on dev

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1920]
**General description:** I tried submitting a bug through the 'Report a Bug' feature on the website.  I selected the option that I do have a Github account, and was redirected to the login page.  After logging in, I clicked that I did have a Github account.  I got brought back to the live website's login page.  Didn't continue further because this is already wrong.

**live/dev/localhost:** dev
**iSENSE Version:** v5.8-238-g084b967
**Logged in (Y or N):** initially no, requires login to produce bug though
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome Version 39.0.2171.99 (64-bit)

**Steps to Reproduce:**
0. Be logged out
1. Go to 'Report a Bug' at the bottom of the page
2. Choose that you have a Github account
3. Login to your account and get redirected to the Report a Bug page
4. Click that you have a Github account again
5. Note you are now on the login screen on isenseproject.org instead of rsense-dev

**Associated Image(s):**

**Comment by kcarcia** [comment]
@stowellm The only place bug reporting should work is on live. Bug reporting is a registered application on GitHub, and it is registered with live's URLs. We can create a separate application to be able to report bugs on dev, but we have agreed to keep the bug reporting only on live to minimize maintenance/work.
