### ISSUE TITLE
Slickgrid: Stuck on 'Saving...' when entering data for project

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1921]
**General description:** I was adding data via manual entry to a project.  First issue I noticed is I was able to delete my only row of data.  You need at least one row.  Curious as I now have no data, I hit `Save`.  I got a pop-up saying there was an error, and the button remained disabled, stating `Saving...`.  I can add real data now but can't save it.

**live/dev/localhost:** localhost
**iSENSE Version:** v5.12-83-g45977b5
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS 
**Browser/Version:** Chrome Version 39.0.2171.99 (64-bit)

**Steps to Reproduce:**
1. Create project
2. Add number field
3. Go to manual entry
4. Delete row - note it actually deleted
5. Click save - note error and fact the save button is stuck on `Saving...`

**Associated Image(s):**

**Comment by kcarcia** [comment]
TESTERS: Follow those exact steps listed above to test.

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by kcarcia** [comment]
PASSED testing on Chrome 29.0.1547.57 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).
Fine, but there should be feedback indicating why clicking that 'X' with only a single row won't delete it (i.e. a message that says something like "Must have one row of data")

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
