### ISSUE TITLE
Slickgrid: Saving Data Doesn't

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1922]
**General description:** Trying to use manual entry for data with Slickgrid.  Entered a single number, hit Save, and there was no data in my data set.  Went back, tried entering two numbers, and the last one doesn't save.  It seems any field that's currently being edited when `Save` is pressed doesn't save.  I believe in the old table, clicking save first resigns focus of anything being edited and then saves (or so it appeared visually).

**live/dev/localhost:** localhost
**iSENSE Version:** v5.12-83-g45977b5
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome Version 39.0.2171.99 (64-bit)

**Steps to Reproduce:**
1. Create project
2. Add number field
3. Go to manual entry
4. Enter data set name
5. Enter a number or two
6. Click save while *keeping focus on one field*
7. Note the field that was being edited did not save

**Associated Image(s):**

**Comment by kcarcia** [comment]
TESTERS: Follow those exact steps listed about to test.

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by kcarcia** [comment]
PASSED testing on Chrome 29.0.1547.57 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
