### ISSUE TITLE
Slickgrid: Entering data with latitude and longitude freezes save button with extra row

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1924]
**General description:** I've set up a project with a number, latitude, and longitude field.  To start, the latitude and longitude fields were combined into one entry column, which is fine.  But I have no indicator as to how I'm supposed to enter the data.  I took a guess (see screenshot), and when I hit `Save`, it froze.

**live/dev/localhost:** localhost
**iSENSE Version:** v5.12-84-g67f731b
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome Version 39.0.2171.99 (64-bit)

**Steps to Reproduce:**
1. Create project
2. Add number and location fields
3. Go to manual entry
4. Enter a data set name, a number, and some lat/lon data
5. Add another row and click on one of those cells so that you are no longer editing the first row
6. Note button says `Saving...` with no feedback and freezes

**Associated Image(s):**
![wat_lat_lon](https://cloud.githubusercontent.com/assets/1039162/5760766/eef81c98-9ca4-11e4-8064-3d5e583c5e88.png)

**Comment by kcarcia** [comment]
TESTERS: Follow those exact steps listed above to test.

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by kcarcia** [comment]
PASSED testing on Chrome 29.0.1547.57 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).
Only note here (unrelated to this issue, however): if you enter an invalid lat/lon and click 'add row', the invalid data gets erased with no feedback.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.35 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
