### ISSUE TITLE
Debugging Statements Clean Up

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1941]
**General description:** A general console.log, logger, puts, print, etc. clean up would be nice. Just by doing a quick grep, I have identified several areas in need of clean up.

**live/dev/localhost:** live
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 29.0.1547.57

**Steps to Reproduce:** 

5

**Comment by kcarcia** [comment]
TESTERS: Nothing too specific to test here. Just please be on the lookout for any unusual behavior across the web site.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
