### ISSUE TITLE
Datasets are clipped if there are too many

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#1942]
**General description:** If you have too many datasets, they get cut off on the bottom when you visualize them.

**live/dev/localhost:** live/dev/localhost
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y/N
**Admin (Y or N):** Y/N

**OS:** Ubantu 14.05.2, Wondows 8.2
**Browser/Version:** Chrome 55

**Steps to Reproduce:**
* Go to http://isenseproject.org/projects/805/data_sets/7407,7403,7402,7401,7399,7398,7397,7396,7395,7394,7374
* Go to scatter charts if you haven't already
* Select all datasets
* Deselect all but one of the visible ones
* Observe as there are two datasets displayed but only one visible one selected

**Associated Image(s):**
![image](https://cloud.githubusercontent.com/assets/7584534/5931780/4de70fc8-a670-11e4-90f0-a24b35e0dfe8.png)

**Comment by bdonald25** [comment]
@asalani93 I am not able to reproduce this.

**Comment by kcarcia** [comment]
@asalani93 I also can't reproduce this. At some point can you show me this in person please? There we go :)

**Comment by asalani93** [comment]
No problem.

**Comment by bdonald25** [comment]
@asalani93 I am not able to reproduce it on my local host after pulling from upstream. Maybe the issue has since been fixed?

**Comment by asalani93** [comment]
Yep, apparently this was fixed in the last patch of PRs.  Nevermind then.
