### ISSUE TITLE
Table vises have broken links for default media objects

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#1944]
**General description:** Saving a table vis creates a vis with a broken URL as its first media objects

**live/dev/localhost:** dev
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04.1
**Browser/Version:** Today

**Steps to Reproduce:**
* save a table vis
* the default media object is a broken image

**Associated Image(s):**

**Comment by kcarcia** [comment]
@asalani93 I also can't reproduce this. At some point can you show me this in person please?

**Comment by asalani93** [comment]
Yes.

**Comment by kcarcia** [comment]
Derp, wait I commented on the wrong issue. One sec....

**Comment by kcarcia** [comment]
@asalani93 I think all default images for tables are actually broken right now. Good catch.

**Comment by kcarcia** [comment]
TESTERS: Go to a table vis and make sure the first image in the media box is no longer broken.

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).
Well, creating a table vis doesn't even create a media object :smile: but this passes

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1 x64).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.94 (Max OSX 10.9.4).
