### ISSUE TITLE
Calendar Changing Month Incorrectly

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#1949]
General description: Calendar picker changes months incorrectly.

live/dev/localhost: dev
iSENSE Version: v5.12
Logged in (Y or N): Y
Admin (Y or N): N

OS: Ubuntu 14.04.1
Browser/Version: Chrome 38.0.2125.111

Steps to Reproduce:

Click on gray day in calendar picker (as in a day that belongs to the previous month). Then click a black day in the current month. The calendar will move to the next month.

**Comment by kcarcia** [comment]
@asalani93 Think you'll have time to address this before Friday's release?

**Comment by asalani93** [comment]
Just fixed this - I've made a pull request for it.  Should I just merge my own pull requests, or should somebody review them?

**Comment by jaypoulz** [comment]
@asalani93 You have my permission to review you're own code this time. If you could move the patch to the iSENSE better-* repo, and submit a patch with these repos as the basis for the new Gem, that would be awesome!
