### ISSUE TITLE
Logarithmic Y Axis option does not appear on toolbar

### ISSUE THREAD

**Issue by jdaigneau** [isenseDev/rSENSE#1950]
General description: The Logarithmic Y Axis does not appear as an option for any of the visualizations.

**live/dev/localhost**: dev
**iSENSE Version**: v5.12
**Logged in (Y or N)**: Y
**Admin (Y or N)**: N

**OS**: OSX 10.9.4
**Browser/Version**: Chrome v40

**Steps to Reproduce**:

Create a new project.
Upload datasets.
Visualize all the datasets.
Logarithmic Y Axis is missing.

Project 1042

**Comment by kcarcia** [comment]
@jaypoulz @jdaigneau I can't seem to reproduce this. Can someone else chime in on this?

**Comment by jaypoulz** [comment]
This is not technically a bug. I've added some notes to about Design Notes wiki page on the subject. The long and short of it is that we can't show a logarithmic Y axis unless the values are log safe. Still, I want to look into to the implementation of our log safe function before closing this.

**Comment by jaypoulz** [comment]
Closing as documented here: https://github.com/isenseDev/rSENSE/wiki/Design-Notes#logarithmic-y-axis
