### ISSUE TITLE
Improve Message on Liked Projects Pane w/ No Projects

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1951]
**General description:** When a user doesn't like a project, "No Contributions" appears in the Liked projects pane. It might be nice to improve this text by saying something like "No Liked Projects" since liking a project isn't a contribution.

**live/dev/localhost:** live
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 40.0.2214.91

**Steps to Reproduce:** Go to a Liked projects pane on a user profile page of a user that that has liked no projects.

**Associated Images:**
![screen shot 2015-01-26 at 10 03 45 pm](https://cloud.githubusercontent.com/assets/1798956/5913050/55eb92b8-a5ab-11e4-8620-90436ddcbd67.png)

**Comment by kcarcia** [comment]
TESTERS: View user page and check text displayed when you have no liked projects.

**Comment by stowellm** [comment]
FAILED testing on Internet Explorer 11.0 (windows 7).
Always says "No Results" even when there are projects/data sets/visualizations, but no liked projects.  Once I liked a project, the user page loaded with the text "Page 1 of 1", but once I switched tabs to "My Projects," it went back to "No Results."

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1 x64).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
FAILED testing on Safari 8.0.3 (Mac OSX 10.10.2).
Same issue that @stowellm mentioned.

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.94 (Max OSX 10.9.4).
