### ISSUE TITLE
Google Doc Contribution Dialogue Box Needs Some UI Love

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1952]
**General description:** The dialogue box used to contribute data via a Google Doc needs some UI work. See the image below.

**live/dev/localhost:** live
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 40.0.2214.91

**Steps to Reproduce:**
1. Go to a project.
2. Click Google Doc to contribute data.

**Associated Images:**
![screen shot 2015-01-26 at 10 35 56 pm](https://cloud.githubusercontent.com/assets/1798956/5913100/1e36cfa8-a5ac-11e4-8772-20794a7f7997.png)

**Comment by stowellm** [comment]
I was just about to make an issue about this until I saw you already made one.  What I wanted to mention is that the `Save` button should be on the right.  Convention appears to be to always put positive action buttons on the right, negative on the left.

**Comment by kcarcia** [comment]
@stowellm +1 !

**Comment by kcarcia** [comment]
TESTERS: Alignment on the Google Doc box should be fixed. Also, the Save should be on the right. Cancel on the left.

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1 x64).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.94 (Max OSX 10.9.4).
