### ISSUE TITLE
Delete button overflows in media panel

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#1962]
**General description:** Delete button on media object overflows

**live/dev/localhost:** live
**iSENSE Version:** v5.12-208-gdd7f7af
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.35

**Steps to Reproduce:** Project's page. You have to minimize the width of the browser.

![screen shot 2015-01-30 at 11 21 21 am](https://cloud.githubusercontent.com/assets/4121924/5979523/79078a04-a876-11e4-99b1-de5c7f8c1295.png)

418

**Comment by jaypoulz** [comment]
TESTERS: Verify that the "Edit | Delete" stay together in the projects media box when you minimize the browser.

**Comment by stowellm** [comment]
Looks good for media... but now it's not consistent with data sets.

![hooplah](https://cloud.githubusercontent.com/assets/1039162/6872529/456111da-d480-11e4-84c0-58b058174dbc.png)

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
