### ISSUE TITLE
Checkboxes on heat map disappear after resizing radius.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#1963]
**General description:** Heat map check boxes disappear.

**live/dev/localhost:** live
**iSENSE Version:** v5.12-208-gdd7f7af
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.35

**Steps to Reproduce:** Changing the radius on the heat map.

Before
![screen shot 2015-01-30 at 11 50 51 am](https://cloud.githubusercontent.com/assets/4121924/5979580/dfa10664-a876-11e4-9750-b73241dec24b.png)
After
![screen shot 2015-01-30 at 11 56 40 am](https://cloud.githubusercontent.com/assets/4121924/5979604/17932f84-a877-11e4-8d9e-74aaef70ca05.png)

418

**Comment by kcarcia** [comment]
TESTERS: On a heat map, resize the radius. Verify the checkboxes under Other are still present.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 42.0.2311.135 (mac).

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
