### ISSUE TITLE
After removing a location field you can't add another one.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#1966]
**General description:** After deleting a location field you can't add another one without saving.

**live/dev/localhost:** live
**iSENSE Version:** v5.12-208-gdd7f7af
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.35

**Steps to Reproduce:** On manual entry page.

![screen shot 2015-01-30 at 12 11 32 pm](https://cloud.githubusercontent.com/assets/4121924/5979868/5e6a5b2e-a879-11e4-8741-b8d1bfe6a885.png)

418

**Comment by kcarcia** [comment]
TESTERS: Verify that adding then deleting a location or timestamp field disables/enables the location/timestamp buttons respectively without having to refresh the page.

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.115 (linux).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.115 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 40.0.2214.115 (linux).
