### ISSUE TITLE
Contact Page Fine Adjustments

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1971]
**General description:**
Anything found in the contact page that should be adjusted after the Friday, 1/30/15 release should be noted here:

- [x] Add 2015 to Jake's BS receive date

**live/dev/localhost:** any
**iSENSE Version:** 1/30/15's release
**Logged in (Y or N):** n/a
**Admin (Y or N):** n/a

**OS:** n/a
**Browser/Version:** n/a

**Steps to Reproduce:** n/a

**Associated Image(s):** n/a

**Comment by stowellm** [comment]
@JKinsman When testing, just make sure you have your graduation date next to your contact info :smile_cat:

**Comment by JKinsman** [comment]
Yay! 😄.. Thanks Mike!

Sent from my iPhone

On Feb 10, 2015, at 2:26 PM, Mike Stowell <notifications@github.com<mailto:notifications@github.com>> wrote:


@JKinsman<https://github.com/JKinsman> When testing, just make sure you have your graduation date next to your contact info [:smile_cat:]

**Comment by kcarcia** [comment]
TESTERS: Jake's graduation date should now be included.

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1 x64).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.94 (Max OSX 10.9.4).
