### ISSUE TITLE
Long Data Set Names are Clipped in the Vis Controls

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1972]
**General description:** Having a single data set with a long name is clipped in the "Groups" section of the vis controls.

(Assigned right now to @jaypoulz because I know he's re-doing the vis UI)

**live/dev/localhost:** dev
**iSENSE Version:** v5.12-208-gdd7f7af
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** OSX Yosemite 10.10.1
**Browser/Version:** Chrome 40

**Steps to Reproduce:**
- Create project
- Add fields
- Add a data set with a long name
- Visualize the data set

**Associated Image(s):**
![screen shot 2015-01-30 at 12 04 15 pm](https://cloud.githubusercontent.com/assets/1039162/5981509/aa8bb62e-a888-11e4-85f4-0470ae03ecd7.png)

**Comment by kcarcia** [comment]
TESTERS: Please follow the steps to reproduce to test this one. Your very long data set name should no longer by clipped.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 42.0.2311.135 (mac).

**Comment by JKinsman** [comment]
FAILED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).
Looks good in the controls section, but the title then overflows :(

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).

**Comment by kcarcia** [comment]
New issue addressed in #2124
