### ISSUE TITLE
Slickgrid v2 Enhancements

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1973]
**General description:** The following enhancements should be made to v2 of Slickgrid:

- [x] Feedback indicating why clicking that 'X' with only a single row won't delete it (i.e. a message that says something like "Must have one row of data")

- [x] Feedback why entering an invalid lat/lon and click 'add row' erases data.

- [x] If a user enters invalid data and then clicks save, the data is simply wiped out. We probably should disable save if input is invalid or show error messages on save or some variation of this.

- [x] More specific title for /manualEntry /edit. Current title is "Data_sets"

- [x] Add Cancel button which takes you back to the project page.

- [x] Default to 10 rows of data.

**live/dev/localhost:** live
**iSENSE Version:** v6.0
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 40.0.2214.94

**Steps to Reproduce:** 
1. Go to a project.
2. Click manual entry.

**Comment by asalani93** [comment]
In regards to the third bullet point, this is currently not possible with the current way I have the code structured.  There is either no way to force the grid to valid its data, or the documentation is lacking even more than I thought it was.

However, it is important to fix that.  Therefore, I've decided to go back and refactor/redo a lot of the slickgrid stuff.  The other three are super easy fixes, though.  This should be done before the next release.

**Comment by jaypoulz** [comment]
@asalani93 is it not possible to have a backup copy of the data made on save, and repopulate the grid with the backup upon failure?

**Comment by asalani93** [comment]
There's no way to do that without either allowing invalid data to leak into
the dataset, or killing compatibility with any non-in-house editors.

**Comment by jaypoulz** [comment]
@asalani93 so slickgrid has limited export / import capabilty? I mean, export has to be there for uploading to the website, but import isnt?

**Comment by asalani93** [comment]
Importing/exporting isn't the problem - that's incredibly easy.  The problem is that when saving, I currently force the current edit to try and commit.  If it's an invalid edit, it's discarded.  This is mostly all default Slickgrid behavior

Repopulating the grid would put the data as the initial loaded value for the editor, which is implicitly accepted as valid.  You could put an invalid latitude and longitude into a dataset, click save, the editor remembers the current edit, it fails validation, it puts back the invalid edit and opens the editor.

I have found a solution - you can get the object representing the current editor, which is required to have a validate method.  I'll have to get a lot of Slickgrid's functionality to run in roundabout ways, but it'll work.

**Comment by jaypoulz** [comment]
Neat. This clarification definitely shines some light on the issue. SlickGrid is kind of a pain, isn't it haha? :smiley_cat: I mean, theoretically, you could just run the validate method on the data you've exported, sanitize it, and then reimport it. I don't know which is easier, but the flaw with this suggestion is that validation occurs twice.

**Comment by kcarcia** [comment]
@asalani93 I've added the 3 minor things we talked about you addressing at the meeting today. Is this something you'll think you'll have in for Friday's release?

**Comment by asalani93** [comment]
I don't have time to finish the patch by this Friday.

However, I do have some questions:

1) where do you want the cancel button?  Should it go where the save
buttons are?

2) the column headers are pulled from the field names.  Should I make a
special case for timestamps?

**Comment by kcarcia** [comment]
@asalani93 

1) It show go the left of the Add Row and Save buttons. (Unless that looks bad. If it does, ping me.)

2) Yes, please.

**Comment by kcarcia** [comment]
TESTERS: Please verify all the items in the description are complete.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).
Notes:
- [ ] "An error occurred: Datasets require data" -- "data sets" is two words

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
