### ISSUE TITLE
Images in description boxes shouldn't fill width if they are not actually that wide

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1976]
**General description:**
See the image below of a tutorial - the image of the green plus and "Add Description" are *way* too big.

**live/dev/localhost:** live
**iSENSE Version:** v6.0
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Windows 8.1
**Browser/Version:** Chrome 40.0

**Steps to Reproduce:**
- Go to http://isenseproject.org/tutorials/1
- Note the images are huge

**Associated Image(s):**
![isense_tutorial1](https://cloud.githubusercontent.com/assets/1039162/6027087/8ae2254c-abad-11e4-8d22-4ff98898b377.png)

**Comment by stowellm** [comment]
Looks like this issue is already resolved.  I deleted and re-uploaded the images in a tutorial on dev (http://rsense-dev.cs.uml.edu/tutorials/1) and they re-size correctly.

@kcarcia I'm thinking of closing this issue and opening a new one that addresses one of the following:
1) deletes and reuploads the images to size correctly in our tutorials 
-or-
2) re-doing the main tutorials completely now that our website looks so different

I prefer 2) over 1), but let me know what you think.

**Comment by kcarcia** [comment]
@stowellm I definitely think 2 is the way to go! That would be great. We did those tutorials awhile ago. They definitely need to be updated.

**Comment by stowellm** [comment]
Created a new issue to address this - closing this one.
