### ISSUE TITLE
Website sees contrib key post as a user post when using the API in Python

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#1983]
General description: Website sees contrib key post as a user post when using the API in Python.

live/dev/localhost: dev
iSENSE Version: v6.0
Logged in (Y or N): Y
Admin (Y or N): N

OS: Ubuntu 14.04
Browser/Version: Chrome 41.0.2272.35

Steps to Reproduce: Use Python script to make a post request to the API using a contributor key.

**Comment by bdonald25** [comment]
@jaypoulz The bug clearly exists on Dev (I reproduced it on multiple projects) but I can not reproduce it locally. I ran the same python code to upload data to dev and my localhost. I just pulled, so my branch is not behind. Any ideas?

**Comment by jaypoulz** [comment]
Without comparing the server logs, I have not idea what could be going on. I can take a look at it with you next time our hours coincide.

**Comment by bdonald25** [comment]
This bug was fixed somewhere along the way. Tyler's python code was uploading data with no field ID and that was somehow causing the bug. Now it fails to upload as it should.
