### ISSUE TITLE
Can enter a key while logged in

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#1985]
**General description:** Can enter a key when I am logged in.

**live/dev/localhost:** live
**iSENSE Version:** v6.0
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.43

**Steps to Reproduce:** On my project's page that I just created. I created a project and added a key to it.

On the right hand side I can enter a key even though I am logged in.

If you then type in a key -> add fields -> upload data the dataset will have the icon that is a picture of a key but the user name will be your username.

You can't type in a key once there are fields.

![screen shot 2015-02-07 at 2 43 53 pm](https://cloud.githubusercontent.com/assets/4121924/6093696/1b0eac6c-aed8-11e4-9c87-7fc8cd86b330.png)

10

**Comment by kcarcia** [comment]
TESTERS: Create a new project, and create a contributor key for that project. Do not set up fields at this point. And then, 
(1) Go to the project's page and verify the option to contribute data using a key doesn't exist.
(2) Logout. Verify the option to contribute data using a key still doesn't exist.

Now, log back in. Set up fields. And then,
(1) Go to the project's page and verify the option to contribute data using a key still doesn't exist.
(2) Logout. Verify the option to contribute data using a key DOES exist.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).
What is the point of contributor name though?  The label is now showing up next to the data set name instead of the contributor name.  Has this always been like this?  Or is that a bug this introduced?

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
