### ISSUE TITLE
API Extra Project calls not listed

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#1987]
General description: The API has extra calls to projects that aren't listed in the Docs. "/api/v1/projects"

live/dev/localhost: live
iSENSE Version: v6.0
Logged in (Y or N): Y
Admin (Y or N): N

OS: Ubuntu 14.04 (Posting with Javascript)
Browser/Version: Chrome 41.0.2272.43

Steps to Reproduce: N/A

**Comment by jaypoulz** [comment]
I think what is meant here is that the are optional parameters to projects -> index that are not listed in the documentation

**Comment by tylerpuleo** [comment]
Yes, that's a much better way of explaining it thank you Jeremy.

**Comment by jaypoulz** [comment]
TESTERS: There is a lot of new documentation here. If you work a lot with the API, I'd appreciate it if you could glance over the documentation and try to find typographical errors or inconsistencies. If we find any, we'll follow this up with a cleanup patch.

**Comment by JKinsman** [comment]
FAILED testing on Safari 8.0.3 (Mac OSX 10.10.2).
Documentation looks good, although the information that appears when an API call is clicked overflows the main page.
