### ISSUE TITLE
API has no error for making contrib key if key already exists

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#1988]
General description: If contrib key already exists and you try to make another contrib key with the same name there is no error message thrown "/api/v1/projects/XX/add_key"

live/dev/localhost: live
iSENSE Version: v6.0
Logged in (Y or N): Y
Admin (Y or N): N

OS: Ubuntu 14.04 (Javascript)
Browser/Version: Chrome 41.0.2272.43

Steps to Reproduce: Run this Javascript:

    var apiUrl = 'http://isenseproject.org/api/v1/projects/835/add_key';

    var upload = {

        'email': 't@t.t',
        'password': 't',
        'contrib_key': {'name' : 'key','project_id' : 835, 'key' : 'key'}
    }
    $.post(apiUrl, upload);

**Comment by jaypoulz** [comment]
TESTERS: You can go ahead and ignore this issue. @tylerpuleo Would you mind trying out a few of your JS requests against the API and verifying this?

**Comment by tylerpuleo** [comment]
Absolutely

**Comment by tylerpuleo** [comment]
Bug no longer a bug
