### ISSUE TITLE
Title included but doesn't do anything /api/v1/data_sets/append (contrib key one)

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#1991]
General description: Title included but doesn't do anything /api/v1/data_sets/append (contrib key one)

live/dev/localhost: live
iSENSE Version: v6.0
Logged in (Y or N): Y
Admin (Y or N): N

OS: Ubuntu 14.04
Browser/Version: Chrome 41.0.2272.43

Steps to Reproduce: N/A

**Comment by kcarcia** [comment]
TESTERS: Go to http://rsense-dev.cs.uml.edu/api/v1/docs and make sure title is not listed in /api/v1/data_sets/append

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.94 (Max OSX 10.9.4).
