### ISSUE TITLE
Tutorials Dropdown is Unreadable When Highlighted

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#1992]
**General description:**
Looks like someone just update the tutorials dropdown in the menu to be dark blue instead of grey.  It looks nice, but now when you hover over a tutorial, the light-grey highlight on the white text makes it near impossible to read.

**live/dev/localhost:** dev
**iSENSE Version:** v5.12
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu
**Browser/Version:** Chrome 40

**Steps to Reproduce:** 
1. Go to dev
2. Click Tutorials
3. Hover over item
4. Squint while trying to read it

**Associated Image(s):**
![iohgeoihgehoieoiegiogewohi](https://cloud.githubusercontent.com/assets/1039162/6135019/35670048-b133-11e4-9d30-4060c0e1caa9.png)

**Comment by kcarcia** [comment]
Closing because this is actually an issue with the new homepage. I wlil talk to @JKinsman about this.
