### ISSUE TITLE
Change API Mouse over cursor

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#1995]
General description: When you mouse over the get and post in the API you get a text cursor.

live/dev/localhost: both
iSENSE Version: v6.0
Logged in (Y or N): both
Admin (Y or N): N

OS: Ubuntu
Browser/Version: Chrome 40

Steps to Reproduce: Go to the API mouse over a POST or GET label.

**Comment by jaypoulz** [comment]
lolololololololol

**Comment by kcarcia** [comment]
TESTERS: Go to http://rsense-dev.cs.uml.edu/api/v1/docs and verify the cursor changes when you mouse over the POSTs/GETs. They should look clickable.

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1 x64).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on 40.0.2214.94. (Mac OSX 10.9.4)
