### ISSUE TITLE
Edit_fields UI Makeover

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2002]
**General description:** The Edit Fields page is getting a makeover. Changes will include the following:
- [x] Add header to page.
- [x] Buttons to add fields instead of a dropdown list.
- [x] Buttons moved to bottom of page.
- [x] Option to add more than one Number and Text field at a time.
- [x] Delete button should match delete button on Slickgrid.
- [x] Restrictions and Units columns should be hidden in mobile.
- [x] Restriction input boxes should be hidden for everything but text fields.  Unit input boxes should be hidden for everything but number fields.
- [x] Change Save button to match Save button Slickgrid.

**live/dev/localhost:** live
**iSENSE Version:** v6.0
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 40.0.2214.111

**Steps to Reproduce:** None.

**Comment by kcarcia** [comment]
TESTERS: Verify everything in the list above has been accomplished.

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
Looks great, and behaves appropriately :)

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.115 (linux).
Notes:
- Using a project with some fields and data sets, I am warned I cannot delete fields.  But I can add them.  If I add a new field, I should be able to delete that field before saving it.  However, I cannot.

**Comment by kcarcia** [comment]
@stowellm Nice catch, Mike. Will be addressed in my next patch. :)

**Comment by jdaigneau** [comment]
FAILED testing on Chrome 40.0.2214.115 (mac).
The buttons to add fields is at the top of the page rather than the bottom, as it was intended.

**Comment by kcarcia** [comment]
@jdaigneau Good catch. I should've removed that from the issue. For this particular iteration, the buttons should be at the top.

**Comment by bdonald25** [comment]
FAILED testing on Chrome 40.0.2214.115 (linux).
If you minimize the width of the page too much, you lose the notes and the ability to add more than one field at a time.

**Comment by kcarcia** [comment]
@bdonald25 These things are both intended. Otherwise, the page become unusable.
