### ISSUE TITLE
Hiding and unhiding projects from liked/my projects is SSLLOOWW

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2003]
**General description:** Unhiding a project in particular takes forever.  Sometimes changing the tab makes it go faster.

**live/dev/localhost:** dev
**iSENSE Version:** 6.1
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04.1 x64
**Browser/Version:** Chrome 39.0 x64

**Steps to Reproduce:**
* create a project
* click on your profile
* switch to my projects tab
* click "hide"
* click "unhide"
* observe as it stays unhidden

**Associated Image(s):**

**Comment by jaypoulz** [comment]
@asalani93 I might have fixed this accidentally in my ajax killa patch.

Wanna see if you can reproduce this?

**Comment by jaypoulz** [comment]
TESTERS: Try to reproduce this - hiding and unhiding should be instantaneous.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
