### ISSUE TITLE
Duplicate colorpickers

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2004]
**General description:** Clicking on the colorpicker buttons in a certain way makes two colorpickers.  It's not that bad because only two at max can stay open, and when you do anything, at least one will go away.

**live/dev/localhost:** dev
**iSENSE Version:** 6.1
**Logged in (Y or N):** Y/N
**Admin (Y or N):** Y/N

**OS:** Ubuntu 14.04.1 x64
**Browser/Version:** Chrome 39.0 x64

**Steps to Reproduce:**
* Open a vis w/ more than one dataset
* Switch to timeline/scatter/whatever
* Open colorpicker
* Change S or V (not hue, basically)
* Before you mouse up, move the mouse outside of the colorpicker pane
* Release the mouse
* Click on a different colorpicker icon
* Observe as there are now two open colorpickers

**Associated Image(s):**
![selection_005](https://cloud.githubusercontent.com/assets/7584534/6191415/4479e0be-b377-11e4-9f50-4cf64c8dcd81.png)

**Comment by bdonald25** [comment]
Testers: Follow the steps above and make sure you do not end up with two color pickers.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
