### ISSUE TITLE
Field matching suggests a text field for timestamps

### ISSUE THREAD

**Issue by JKinsman** [isenseDev/rSENSE#2005]
**General description:** If you upload fields for a project from a file, timestamp fields will be matched as text fields.

**live/dev/localhost:** dev
**iSENSE Version:** 6.1
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Mac OSX 10.10.2
**Browser/Version:** Safari 8.0.3

**Steps to Reproduce:**
1.  Use a CSV with a timestamp field to create fields for a project (template.csv is fine)
2.  Field matching will suggest it is a text field.

**Associated Image(s):**

**Comment by kcarcia** [comment]
@jdalphon Ok so as it turns out, when you export csv and xls files from Google drive, it changes the timestamp format to mm/dd/yyyy, and this explains why timestamp matching is not working. Does this mean we should extend the regex to recognize dates in that format?

**Comment by kcarcia** [comment]
So this is a Google problem.

However, it would be nice if we could allow users to specify the format of their timestamps on the field matching form. So say their data is in the form mm/dd/yyyy... we would take that information to field match and convert their timestamp to the format we require for parsing. That way we avoid parsing hell, and everyone wins.

This would be a nice-to-have feature but is low priority.

**Comment by bdonald25** [comment]
Testers: Upload data with time formats mm/dd/yyyy and dd/mm/yyyy and make sure they both work as expected.

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
PASSED testing on Firefox 40.0 (linux).
