### ISSUE TITLE
API Documentation Copyedits

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2006]
**General description:**
- [x] /api/v1/projects/XX --- "•XX should be replaced with the ID for the project. Or set id as a GET variable" --- incoherent
- [x] /api/v1/fields/XX --- same as above
- [x] /api/v1/projects --- "Response: Projects (array)" --- JSON format this please
- [x] /api/v1/fields --- "•restrictions - Currently text fields only. Defines accepted values "blue,green,red" will force the project to accept only those values" --- incoherent
- [x] /api/v1/data_sets/append --- put "none" or "n/a" or something instead of blank space under "Notes"
- [x] /api/v1/users/myInfo --- same as above
- [x] /api/v1/media_objects --- "•type - either "project", or "data_sets" --- cringe-worthy grammar

**live/dev/localhost:** live
**iSENSE Version:** v6.0
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 40.0.2214.111

**Steps to Reproduce:** None.

1

**Comment by jaypoulz** [comment]
TESTERS: Once again, only check this out if you are working on/with the API. Please be on the lookout for any spelling mistakes or inconsistencies.

**Comment by stowellm** [comment]
The build thingy in the top right run off the page.  Can it just be pushed left like 20px?

![build_thing](https://cloud.githubusercontent.com/assets/1039162/6872276/9a08eb06-d47e-11e4-9656-ace290263874.png)

**Comment by stowellm** [comment]
FAILED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).
`Example (HTML) **originial** code by Scott Cytacki`

Again, still worth pulling.  Make a new issue for this though.
