### ISSUE TITLE
Edit_fields Table v2: Should Only Submit Data on Save

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2009]
**General description:** Currently, the edit_table form submits every time we add a field, and ajax is used to delete fields. The form should submit only on save. Any request to the server should only be made on save. Therefore, I will be redoing the form using Coffeescript. When I am done users will be able to do the following:

- [x] Add fields.
- [x] Delete fields.
- [x] Submit the form ONLY on save.

As a result, the following UI changes will be made:

- [x] Add a cancel bottom.
- [x] New rows highlighted on save.

**live/dev/localhost:** live
**iSENSE Version:** v6.15
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** Macintosh
**Browser/Version:** Chrome 40.0.2214.111

**Steps to Reproduce:**  None.

**Comment by kcarcia** [comment]
TESTERS: Go to the edit fields table, and do your best to break it! Make sure you specifically take note of timestamp and location fields—both should only be added once.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 42.0.2311.135 (mac).

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
