### ISSUE TITLE
Tutorials should be reworked

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2014]
**General description:** The tutorials on our live website (e.g. http://isenseproject.org/tutorials/1) are out of date.  Also, the images are huge (they would scale correctly if you simply remove and reupload them however).  As discussed in #1976, it would be best to redo the main tutorials and even possibly integrate the video tutorials into the main tutorials.

**live/dev/localhost:** live
**iSENSE Version:** 6.15
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu
**Browser/Version:** Chrome 40

**Steps to Reproduce:** Go to http://isenseproject.org/tutorials/1.  Note it's outdated.

**Associated Image(s):**

**Comment by jdalphon** [comment]
@stowellm All tutorials should be video tutorials where possible. However, this should be put on hold until the homepage is done.

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (linux).
Have been reworked, tutorials need to be uploaded
