### ISSUE TITLE
Add user info to the data set toHash

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#2018]
**General description:** Add owner's name, id, and contributor key to the data set's to hash function.

**live/dev/localhost:** live
**iSENSE Version:** v6.15
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Firefox 37.0

**Steps to Reproduce:** When preforming a get request for projects with recur = true as json, we should see these values.

9

**Comment by kcarcia** [comment]
TESTERS: Don't worry about this.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 40.0.2214.115 (linux).
