### ISSUE TITLE
Color Picker (with combo of others) makes vis disappear

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2023]
**General description:** Through some strange combination of playing with timeline, I can successfully make the timeline vis disappear after using the color picker every time I follow the steps to reproduce listed below.

**live/dev/localhost:** dev
**iSENSE Version:** v6.0-154-g1423f40
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 40.0

**Steps to Reproduce:**
1. Follow the rSENSE-dev Manual Tests to create a project with the appropriate fields/amount of data
2. Go to timeline
3. Click "Draw Best Fit Line"
4. Click "Logarithmic Y Axis"
5. Click "Out" (for zooming)
6. Change the field called "correct"s color using the color picker
7. Note the vis disappeared

**Associated Image(s):**

**Comment by jaypoulz** [comment]
@stowellm You and I should take a look at this together next time we can a chance.

**Comment by stowellm** [comment]
@jaypoulz Well, despite having been able to reproduce this over and over on testing day, I can't seem to get this to work again today.  Let me know if you can reproduce it - otherwise it may not be an issue after all.
