### ISSUE TITLE
Field restrictions should default in database as empty array

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#2024]
**General description:** Field restrictions should default to empty array

**live/dev/localhost:** live
**iSENSE Version:** v6.15-24-g6a35ce4
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Firefox 37.0

**Steps to Reproduce:** Migration 20141015152508_remove_whitespace_from_restrictions brought attention to the fact that there were actually 3 kinds of representations for empty field restrictions.  It would be nice if we changed this to a singular representation. The representation chosen by the new version of the migration is empty array. See #2022 for more details.

9

**Comment by bdonald25** [comment]
testers: Add restrictions for a text field on a project. Make sure the restrictions are working correctly.

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
PASSED testing on Firefox 40.0 (linux).
