### ISSUE TITLE
Deleting an image from a data set redirects to project page

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2025]
**General description:** When visualizing a single data set with media, deleting the media redirects you back to the project's show page instead of the data set visualization.

**live/dev/localhost:** dev
**iSENSE Version:** v6.0-156-gb3d8fba
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 40.0

**Steps to Reproduce:**
1. Visualize a **single** data set
2. Add media
3. Remove the media
4. Note you aren't redirected back to the visualization you were just on, but rather the project page

**Associated Image(s):**

**Comment by kcarcia** [comment]
TESTERS: Follow the steps to reproduce to test this.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
