### ISSUE TITLE
Reorder tabs on user page

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2032]
**General description:** The order of the tabs on the user page should be as follows:
My Projects
Data Sets
Visualizations
Liked Projects

**live/dev/localhost:** live
**iSENSE Version:** v6.3
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 40.0.2214.115

**Steps to Reproduce:**
1. Login.
2. Go user page.

**Comment by kcarcia** [comment]
TESTERS: The Liked pane should now be the last tab on the user's page.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
