### ISSUE TITLE
Modernizr console warnings/errors on every rsense-dev page

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2035]
**General description:** On every page I visit on rsense-dev, I'm seeing some `modernizr` issues in the console.

**live/dev/localhost:** dev
**iSENSE Version:** v6.0-316-g896eb33
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu LTS 14.04
**Browser/Version:** Chrome 40

**Steps to Reproduce:** Go to any page on rsense-dev with your console open.

**Associated Image(s):**
![modernizr](https://cloud.githubusercontent.com/assets/1039162/6527098/ec96f47a-c3e5-11e4-930e-1d73446a9fbb.png)

**Comment by kcarcia** [comment]
That first error message "document.body doesn't exist" is referring to the fact that we load modernizr in the head before we load the body. However, I've read loading modernizr in the body can cause problems, though. Any thoughts @jdalphon ?

**Comment by jdalphon** [comment]
modernizr probably updated on last bundle install. This does not seem to be an issue any longer. Please test this tomorrow.

**Comment by stowellm** [comment]
Testers should just leave their JS console open while testing tomorrow and make sure none of this wonky stuff shows up anywhere on the site.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
