### ISSUE TITLE
Can't template fields with a CSV that has only headers

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2036]
**General description:** I tried setting up fields for a project using a CSV that had only headers.  Got an error (see image). However if I add even one number to the row below the headers, all is fine.

**live/dev/localhost:** dev
**iSENSE Version:** v6.0-316-g896eb33
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu LTS 14.04
**Browser/Version:** Chrome 40

**Steps to Reproduce:**
1. Create new project
2. Setup fields by uploading file
3. Choose a CSV with only headers (no data)
4. Observe error as seen in the image below

**Associated Image(s):**
![something](https://cloud.githubusercontent.com/assets/1039162/6527177/bb508c40-c3e6-11e4-9821-5281ac834113.png)

**Comment by jdalphon** [comment]
Its trying to figure out what the types  are and needs to see data

On Fri, Mar 6, 2015 at 9:54 AM, Mike Stowell <notifications@github.com>
wrote:

> *General description:* I tried setting up fields for a project using a
> CSV that had only headers. Got an error (see image). However if I add even
> one number to the row below the errors, all is fine.
>
> *live/dev/localhost:* dev
> *iSENSE Version:* v6.0-316-g896eb33
> *Logged in (Y or N):* Y
> *Admin (Y or N):* N
>
> *OS:* Ubuntu LTS 14.04
> *Browser/Version:* Chrome 40
>
> *Steps to Reproduce:*
> 1. Create new project
> 2. Setup fields by uploading file
> 3. Choose a CSV with only headers (no data)
> 4. Observe error as seen in the image below
>
> *Associated Image(s):*
> [image: something]
> <https://cloud.githubusercontent.com/assets/1039162/6527177/bb508c40-c3e6-11e4-9821-5281ac834113.png>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/isenseDev/rSENSE/issues/2036>.
>



-- 
--------------------------------
James Dalphond
UML Computer Science
Engaging Computing Group

**Comment by stowellm** [comment]
Yup - I believe I just fixed this.  It need data only for timestamp/text fields, so I switched the ordering to check for latitude/longitude first (since this only requires the name of the field), then checks if the data column is nil.  If so, it continues the loop rather than failing.

**Comment by kcarcia** [comment]
TESTERS: Verify you can setup fields for a project by trying to upload a CSV with only file headers.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).
should default to text

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
I agree with Anthony, should default to text :)

**Comment by stowellm** [comment]
There is a new issue open for defaulting to text.  I'd say release with this anyways, I'll fix that next patch.
