### ISSUE TITLE
Box headers should show a pointer cursor

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2040]
**General description:** Box headers should use a pointer cursor to guide users into clicking them and discovering you can expand/collapse these context boxes.

**live/dev/localhost:** dev 
**iSENSE Version:** v6.15-4-g0ccf671
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 40

**Steps to Reproduce:**
1. Go to any page with content boxes (e.g. a project)
2. Note when hovering over a box header, no "clicky hand" cursor shows indicating that you can click it and have the page respond

**Associated Image(s):**
The "Fields" bar is what I'm talking about, e.g.
![box header](https://cloud.githubusercontent.com/assets/1039162/6530686/02313956-c401-11e4-99eb-64a294f1cd99.png)

**Comment by kcarcia** [comment]
TESTERS: When you hover over the grey box headers, the cursor should be a pointer.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
