### ISSUE TITLE
In manual entry, units should be shown

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2044]
I am setting up for my 91.204 for class to enter data from their experimental work. Here is the data entry form, partially filled in:

![partially-filled](https://cloud.githubusercontent.com/assets/1038856/6543376/726e2a12-c4e7-11e4-9471-18b0111cf7de.png)

I actually didn't remember whether I set up the experiment with CPU speed in MHz or GHZ, and *there are no units!*

Please let's display units on this entry form.

**Comment by fgmart** [comment]
They should be on a new line below the field names, and with parenthesis; e.g:

cpu-speed        string-length        time-to-solution
  (MHz)                                             (seconds)

**Comment by kcarcia** [comment]
TESTERS: Test the manual entry table with a project that has units specified for some field. These units should be present on the manual entry table.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
