### ISSUE TITLE
Contributor key icon is disproportionately scaled

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2045]
The contributor key looks bad because it's not proportionally scaled. Here's how it looks on the web site:

![contrib-key-squashed](https://cloud.githubusercontent.com/assets/1038856/6543542/8f8651dc-c4ed-11e4-9714-088ceff0284a.png)

Here's the actual image:

![key](https://cloud.githubusercontent.com/assets/1038856/6543545/a4994692-c4ed-11e4-8607-b371a656d6bd.png)

The key shown should be proportionally scaled so it's not stretched vertically.

**Comment by kcarcia** [comment]
Also, the Submit key button and key input box need some margin. https://cloud.githubusercontent.com/assets/1039162/6802342/f77185da-d205-11e4-8521-b9d93ea11dc6.png

**Comment by jaypoulz** [comment]
TESTERS: Verify that the "Submit Key" button has some margin, and that the contributor key image is no longer being stretched.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).
