### ISSUE TITLE
Units should be displayed in datapoint detail popup

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2046]
Subject line is the whole story. 

E.g., we should see the units -- MB -- next to the *memory-used* field in this pop-up:

![units-in-tooltips](https://cloud.githubusercontent.com/assets/1038856/6543575/f2c8358e-c4ee-11e4-8a20-6336b53b5308.png)

Note, here there should *not* be parens. In this case, you want to see "25 MB".

**Comment by jaypoulz** [comment]
@JKinsman use the 'fieldTitle' function in vis utils - should by a 1 line patch in each file

**Comment by JKinsman** [comment]
@jaypoulz I'm finishing up the patch now.  The fieldTitle won't work here, as Fred wants the tooltip formatted differently.

**Comment by kcarcia** [comment]
TESTERS: Units should be displayed in datapoint detail popup on vises.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
