### ISSUE TITLE
Pie chart titles are backwards ("group by field" as opposed to "field by group")

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2050]
**General description:** In pie charts, when you group by some group, the title of the chart becomes "`group` by `field`" instead of "`field` by `group`".  This is wrong

**live/dev/localhost:** live
**iSENSE Version:** 6.3
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04
**Browser/Version:** Chrome 41

**Steps to Reproduce:**
1. Create a project with 2 numbers and one text field.
2. Add 4 data points: 2 data points should have the same text field name.
3. Go to pie.
4. Choose the text field as your group.
5. Note the name of the pie chart: ensure it is `field` by `group`.

**Associated Image(s):**
http://isenseproject.org/visualizations/472 (should by Drive Capacity by Manufacturer)

**Comment by kcarcia** [comment]
TESTERS: Follow the steps to reproduce to test.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
