### ISSUE TITLE
Can't edit data set name

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2053]
**General description:** I can't rename a data set. It flashes red when I try to save.  
Also, from the Edit Data interface, it makes me think that it's working (no red flashes), but when I save the whole thing, it doesn't actually rename.

**live/dev/localhost:** live
**iSENSE Version:** v6.3
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 40.0.2214.111

**Steps to Reproduce:** Doing the above.

12

**Comment by jaypoulz** [comment]
Awesome - that's for using the report a bug button! :smile: 

Could we possibly get the project + data set you were working on as well?

**Comment by kcarcia** [comment]
@fgmart @jaypoulz Looks like this is actually happening across the board.

**Comment by jaypoulz** [comment]
Excellent - let's up it to high priority and let @stowellm loose on it!

**Comment by jdalphon** [comment]
We were setting the url for the ajax request, then throwing it away.
``` javascript
href = location.pathname
```
fix
```javascript
 href = if ($ @).attr('href')? then ($ @).attr('href') else location.pathname
```

Testing now

**Comment by kcarcia** [comment]
TESTERS: Verify editing a data set name works now.

**Comment by asalani93** [comment]
PASSED testing on Chrome 40.0.2214.115 x64 (Ubuntu 14.04.1 x64).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (linux).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (linux).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (linux).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (linux).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
