### ISSUE TITLE
in My Profile view, Liked Projects should be last tab

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2056]
because it's the least important thing.

**Comment by fgmart** [comment]
high priority because it's trivial to fix, yes?

**Comment by kcarcia** [comment]
@fgmart Already this is already fixed :)

https://github.com/isenseDev/rSENSE/issues/2032

**Comment by stowellm** [comment]
Closing as duplicate as @kcarcia mentioned.
