### ISSUE TITLE
Logging out when viewing a vis creates an "unauthorized" error flash

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2057]
**General description:** When you visualize two data sets you own on a project you on, all is great.  Until you log out.  You get not only the "Logged Out" success flash but get redirected a *second* time with an "Unauthorized" error flash.

**live/dev/localhost:** localhost (so this bug was introduced by someone's PR before release!! because I can't reproduce on current dev)
**iSENSE Version:** v6.3-109-g87615e9
**Logged in (Y or N):** Y
**Admin (Y or N):** Y

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 41

**Steps to Reproduce:**
1. Create project with a number field
2. Create 2 data sets
3. Visualize both data sets
4. Log out
5. Note double redirect and an "Unauthorized" error flash
6. Note hitting back in the browser will not bring you back to the project page until you hit it *twice*

**Associated Image(s):**

**Comment by stowellm** [comment]
Note to @jaypoulz: #2048 is what broke this.  I reverted every commit in that PR and this issue goes away.

**Comment by kcarcia** [comment]
TESTERS: Follow the steps to reproduce to test.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.89 (Ubuntu 14.04 LTS).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.89 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.89 (mac).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.89 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.89 (mac).

**Comment by stowellm** [comment]
I think it passed testing for @bdonald25

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.89 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.89 (mac).
