### ISSUE TITLE
Project and vis thumbnails are inconsistent

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2059]
**General description:** Project thumbnails use a fit scaling.  Visualization thumbnails use a fill scaling. Consistency is nice.

**live/dev/localhost:** dev
**iSENSE Version:** 6.3.something
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 41.something

**Steps to Reproduce:**
1. Create a project
2. Add media and feature it
3. Create a vis
4. Add media and feature it
5. Note inconsistencies

**Associated Image(s):**
![roflgoats](https://cloud.githubusercontent.com/assets/1039162/6641661/96709c78-c975-11e4-9801-bced0002ab91.png)

**Comment by stowellm** [comment]
Another issue that I've addressed that should be tested: Note how you can click a user's name on a vis box but not a project box (see screenshot above)?  *cringe*

**Comment by jaypoulz** [comment]
TESTERS: Make sure the user name in the project index page for each project box is clickable (and directs you to the correct user).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
