### ISSUE TITLE
Default type for empty CSVs should be number, not text

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2062]
**General description:** Currently, empty CSV fields default to number, not text.  Text is more general.

**live/dev/localhost:** dev
**iSENSE Version:** v6.3
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu
**Browser/Version:** Chrome

**Steps to Reproduce:**
Upload an CSV with no fields.  Observe as they default to number.

**Associated Image(s):**
:dog:

**Comment by stowellm** [comment]
We decided number is a better default.  iSENSE likes numbers.  Nevertheless, I improved the field matching for CSVs.  See the PR for details.

**Comment by jaypoulz** [comment]
Yesh. Text might be more generic than numbers, but numbers are more useful than text when generating visualizations. As much as possible, our goal is to encourage users to generate meaningful vises. As a general concept, the barrier between the two types will erode as we introduced numbers as grouping fields, and text as enums.

**Comment by kcarcia** [comment]
TESTERS: Upload a CSV with only headers. Every field should match to a number, except a column with the header "Time" (in that case, it should match to timestamp)

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
