### ISSUE TITLE
Add Indication on Map Markers of Data Sets that Contain Photos

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2063]
**General description:** When a data set includes a picture that is visible on the map, it'd be nice to add some type of indication it exists on the markers. Maybe a font awesome photo icon of some sort? Like a camera.

**live/dev/localhost:** live
**iSENSE Version:** v6.3
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.89

**Steps to Reproduce:**

**Comment by bdonald25** [comment]
Testers: Upload an image to a data set. Make sure the symbol on the map is now a camera instead of a circle. 

Test this with multiple data sets. Make sure that the ones with images have cameras and the ones without images have circles.

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).
YES THIS IS GOOD
