### ISSUE TITLE
Flashing Red Error Indication Removal

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2064]
**General description:** Remove all remnants of flashing red errors. Like on the edit a data set title.

**live/dev/localhost:** live
**iSENSE Version:** v6.3
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.89

**Steps to Reproduce:** Example:
1. Go to a project with a data set.
2. Edit the title of that data set.
3. Type in <strong></strong>
Notice the flashing red.

1

**Comment by bdonald25** [comment]
Testers: Try and find flashing red errors by entering invalid values in various places on the site. (enter characters for numbers, leave things blank, ect.)

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
PASSED testing on Firefox 40.0 (linux).
