### ISSUE TITLE
Datasets -> Data Sets

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2066]
**General description:** Datasets should be Data Sets. Everywhere. Well, not in code but in copy.

**live/dev/localhost:** live
**iSENSE Version:** v6.3
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.89

**Steps to Reproduce:**

**Comment by kcarcia** [comment]
TESTERS: Anywhere that previously said Dataset should now say Data Set.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 41.0.2272.89 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 41.0.2272.89 (mac).
