### ISSUE TITLE
Contributor keys are inconsistent

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2067]
**General description:** Contributor names are not used.  At all.  Anywhere.  They seem entirely useless when using a contributor key through the site.  The name that shows up next to the data set name in the data set list has become the label for the key - I feel like it *should* be the contributor name.  

Also, uploading through the API with a contributor key produces inconsistent results.  Not only does a gravatar icon show up instead of the key icon, but *now* the contributor name shows.  

**live/dev/localhost:** dev
**iSENSE Version:** 6.3.something
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 41.something

**Steps to Reproduce:**
Read the description.

**Associated Image(s):**

**Comment by bdonald25** [comment]
Testers: Give a project a contributor key. Upload data using that key and make sure that the contributor name shows up as expected.
 Also, try uploading data with one of the android applications using a contributor key.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
FAILED testing on Safari 8.0 (mac).

**Comment by jaypoulz** [comment]
There is no commit associated with this patch... was it ever really in testing?

**Comment by bdonald25** [comment]
Anthony and I thought it was fixed a long time ago so we just threw it in
testing to find out. Turns out it was not fixed.

**Comment by jaypoulz** [comment]
Hahaha ok :+1: :smile_cat:

**Comment by bdonald25** [comment]
Testers: Give a project a contributor key. Upload data using that key and make sure that the contributor name shows up as expected.
Also, try uploading data with one of the android applications using a contributor key.

**Comment by qianacurcuru** [comment]
FAILED testing on Chrome 43.0.2357.132 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.132 (linux).

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.130 (linux).
