### ISSUE TITLE
Can't submit testing forms through dev, only live

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2068]
**General description:** Read the title. Gets 404 page.

**live/dev/localhost:** dev
**iSENSE Version:** v6.3.something
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** any
**Browser/Version:** any

**Steps to Reproduce:** Submit bugs.

**Associated Image(s):**

**Comment by kcarcia** [comment]
TESTERS: SAVE YOUR TESTING NOTES! This hasn’t officially been tested, and I’m going to have you test this just by using it. Since it hasn’t “passed” testing, there’s no guarantee it’ll work, so once again, save your testing notes!

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.118 (Ubuntu 14.04 LTS).
If this shows up, it passed.  Otherwise... :(

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 41.0.2272.118 (mac).
