### ISSUE TITLE
When a project is cloned the fields are not copied

### ISSUE THREAD

**Issue by scytacki** [isenseDev/rSENSE#2071]
I first thought that was the just the way cloning was supposed to work.
But this issue describes it otherwise: https://github.com/isenseDev/rSENSE/issues/1233

And it doesn't make sense (to me) that the data sets could be copied but the fields would not be copied.

**Comment by jdalphon** [comment]
Wow. The fields are one of the only things that should be copied. Will look
into this tomorrow.

**Comment by jdalphon** [comment]
@scytacki yes it does not make sense. The fact that they worked is based solely on the fact that ruby did not reorder the hash when saving, because the data sets had no keys.

**Comment by jaypoulz** [comment]
TESTERS: Clone projects should work correctly - including the clone of fields.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.104 (mac).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 41.0.2272.104 (mac).
