### ISSUE TITLE
Hitting enter on manual entry form adds a number instead of saving the form

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2082]
**General description:** As the title says.  Go add some fields to a project, then hit enter.  It adds a number instead of "Save & Return."

**live/dev/localhost:** dev
**iSENSE Version:** 6.5-80
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 40

**Steps to Reproduce:** Description.

**Associated Image(s):**

**Comment by kcarcia** [comment]
TESTERS: Hitting enter on the fields page should save the form.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.118 (Ubuntu 14.04 LTS).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 41.0.2272.118 (mac).
