### ISSUE TITLE
News console error

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2083]
**General description:** While on the news page. Console gives an error telling me my chrome extension is invalid.

**live/dev/localhost:** live
**iSENSE Version:** v6.5
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.104

**Steps to Reproduce:** News Page.

10

**Comment by jdalphon** [comment]
@bdonald25 I get no such error.  Does anybody else see this error?

**Comment by kcarcia** [comment]
TESTERS: Verify you get no console error on the news page. Also verify you can post a news article.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.118 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 41.0.2272.118 (mac).
