### ISSUE TITLE
Tutorial console error

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2084]
**General description:** On any tutorial page. I get an error in the console "Uncaught TypeError: undefined is not a function"

**live/dev/localhost:** live
**iSENSE Version:** v6.5
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.104

**Steps to Reproduce:** Any of the tutorial pages.

10

**Comment by kcarcia** [comment]
TESTERS: Verify you get no console error on the tutorials page. Also verify you can post a tutorial.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.118 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 41.0.2272.118 (mac).
