### ISSUE TITLE
API Styles and Copyedits V2

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2085]
**General description:**
- "Example (HTML) **originial** code by Scott Cytacki"
- Documentation looks good, although the information that appears when an API call is clicked overflows the main page.

**live/dev/localhost:** dev
**iSENSE Version:** v6.5-80-ge79ccd5
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 40

**Steps to Reproduce:**

**Associated Image(s):**

**Comment by jdalphon** [comment]
@stowellm Is this actually a change to the API or just docs?

**Comment by bdonald25** [comment]
@jdalphon just docs

**Comment by kcarcia** [comment]
TESTERS: Verify the concerns noted in the issue description above have been addressed.

**Comment by stowellm** [comment]
PASSED testing on Chrome 42.0.2311.135 (linux).
DISREGARD THIS IS JUST A TEST

**Comment by bdonald25** [comment]
PASSED testing on Chrome 42.0.2311.135 (mac).

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
