### ISSUE TITLE
Edit | Delete Inconsistent between data sets and media

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2086]
**General description:** There's no pipe between Edit and Delete for data sets.  Also the Edit Delete for data sets doesn't fit #1962

**live/dev/localhost:** dev
**iSENSE Version:** v6.5-80
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu LTS 14.04
**Browser/Version:** Chrome 41

**Steps to Reproduce:**

**Associated Image(s):**
![thing](https://cloud.githubusercontent.com/assets/1039162/6872529/456111da-d480-11e4-84c0-58b058174dbc.png)

**Comment by kcarcia** [comment]
TESTERS: Please verify the edit | delete controls for data sets matches the edit | delete controls in the media box. The controls should also be consistent responsively.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.118 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 41.0.2272.118 (mac).
