### ISSUE TITLE
Improved iSENSE Footer

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2094]
**General description:** iSENSE footer facelift!

**live/dev/localhost:** live
**iSENSE Version:** v6.6
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.104

**Steps to Reproduce:** 

1

**Comment by kcarcia** [comment]
TESTERS: Please verify all the links in the footer work. Check how it works responsively. Proof it.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.118 (Ubuntu 14.04 LTS).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 41.0.2272.118 (mac).
