### ISSUE TITLE
Remove stock images, replace with titles

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2095]
**General description:** Stock images are removed from project index page. Projects without images should have their title as an image.

**live/dev/localhost:** live
**iSENSE Version:** v6.6
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.104

**Steps to Reproduce:** 

1

**Comment by kcarcia** [comment]
TESTERS: Please verify all the links in the footer work. Check how it works responsively. Proof it.

**Comment by kcarcia** [comment]
TESTERS: On the projects index page, verify projects without images have their titles as images. Test with long titles and longtitleswithoutspaces. Also try creating a new project and verify this works for both cases.

**Comment by stowellm** [comment]
This looks goofy for featured projects:

![featured2](https://cloud.githubusercontent.com/assets/1039162/6982372/f4927852-d9de-11e4-8afe-0d2fb993acf2.png)

Aren't they all supposed to look more like:

![featured3](https://cloud.githubusercontent.com/assets/1039162/6982380/0d03d6b0-d9df-11e4-8754-ebce24ff0099.png)

@jdalphon

**Comment by jdalphon** [comment]
@stowellm I just came across this myself. The for placeholder is in projects.css.scss because they were only ever supposed to show up on the projects page. 

We should not be featuring projects without images in practice, but the new users page I am working on shows the tiles as well, so I will move it over

**Comment by kcarcia** [comment]
TESTERS: On the projects index page, verify projects without images have their titles as images. Test with long titles and longtitleswithoutspaces. Also try creating a new project and verify this works for both cases. Also please verify the images for all featured projects on the homepage look nice. Featured projects should all have actual images, though.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.118 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
FAILED testing on Safari 8.0.3 (mac).

**Comment by jdaigneau** [comment]
FAILED testing on Chrome 41.0.2272.118 (mac).
Title overflows
