### ISSUE TITLE
iSENSE logo no longer collapses to iS when page is resized

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2099]
**General description:** The iSENSE logo should no longer collapse to iS when the page is resized.

**live/dev/localhost:** live
**iSENSE Version:** v6.6
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.118

**Steps to Reproduce:**

**Comment by kcarcia** [comment]
TESTERS: Please resize the page and verify the iSENSE logo is responsible.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.118 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 41.0.2272.118 (mac).
