### ISSUE TITLE
Table colors by value not by column

### ISSUE THREAD

**Issue by jdaigneau** [isenseDev/rSENSE#2109]
General description: When viewing data in the table vis sorted by Danger Type, if a Danger Type is the same value as a latitude or longitude, the value in lat or long will be colored the same way as the Danger Type.
![screen shot 2015-04-10 at 12 27 20 pm 2](https://cloud.githubusercontent.com/assets/7584533/7092675/df475e7e-df81-11e4-9fc6-9db353d5f2ea.png)

live/dev/localhost: dev
iSENSE Version: v6.6
Logged in (Y or N): Y
Admin (Y or N): N

OS: Mac OSX 10.9.4
Browser/Version: Chrome 41.0.2

Steps to Reproduce: Upload data to a project with the same Danger Type value as a longitude of latitude. Visualize the data as a table and sort by Danger Type. Notice the color similarity.

**Comment by jdalphon** [comment]
@jdaigneau @jaypoulz That....That is an interesting bug.

**Comment by bdonald25** [comment]
@jaypoulz This appears to be fixed. Did you fix it in your vis overhaul patch?

**Comment by jaypoulz** [comment]
No I'm pretty sure it's still a bug. I'll check the table code and let you know

**Comment by asalani93** [comment]
@jaypoulz you never let us know

**Comment by jaypoulz** [comment]
@asalani93 Apparently I fixed this as part of d4d92c1d19e68e87178b000cd379aa2eeabc33f2, although I have no recollection of doing so.

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.132 (mac).

**Comment by bdonald25** [comment]
![screenshot from 2015-07-17 10 36 26](https://cloud.githubusercontent.com/assets/4121924/8749478/c9a11994-2c6f-11e5-838f-f5744a218781.png)

**Comment by bdonald25** [comment]
FAILED testing on Chrome 43.0.2357.132 (linux).

**Comment by asalani93** [comment]
FAILED testing on Chrome 43.0.2357.130 (linux).

**Comment by pat-son** [comment]
PASSED testing on Firefox 44.0.2 (Mac OSX Yosemite 10.10.5).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by JasonD94** [comment]
PASSED testing on Chrome 48.0.2564.97 (Linux Ubuntu 14.04 LTS).
