### ISSUE TITLE
Picture uploaded multiple times in project description

### ISSUE THREAD

**Issue by jdaigneau** [isenseDev/rSENSE#2110]
General description: When adding a picture to the description of a project, I hit save and the page didn't update, so I clicked it once more. The page then loaded and in the media section on the right side of the page, the picture had uploaded three times.

live/dev/localhost: dev
iSENSE Version: v6.6
Logged in (Y or N): Y
Admin (Y or N): N

OS: Mac OSX 10.9.4
Browser/Version: Chrome 41.0.2

Steps to Reproduce: Add picture to project description. Hit save multiple times.

**Comment by kcarcia** [comment]
@JKinsman @jaypoulz @jdalphon So this is real and live. If you click save multiple times when you're editing a description w/ a media object, the media object is saved multiple times. No idea what's causing this. Anyone have any ideas off the top of their head? (Mostly looking at you Jake since you know Summernote)

**Comment by asalani93** [comment]
TESTERS: Try to get two of the exact same images into a project, visualization, or anything that can have images uploaded to it.  Also, try other media objects.

**Comment by KatherineBrunelle** [comment]
FAILED testing on Safari 8.0 (mac).
Pictures don't upload at all.

**Comment by asalani93** [comment]
FAILED testing on Chrome 42.0.2311.90 (linux).
Pictures don't upload, old duplicates still exist

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
