### ISSUE TITLE
Long project names overflow the user page

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2111]
**General description:** Creating a project with a long name overflows the user page.

**live/dev/localhost:** dev
**iSENSE Version:** v6.5-105-g7898c6d
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 41

**Steps to Reproduce:** Make long titled project.  Visit your page.  Note overflow.

**Associated Image(s):**
![IMAGE](https://cloud.githubusercontent.com/assets/1039162/7093522/faff0fe4-df87-11e4-99d6-aed3aa3e8732.png)

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).

**Comment by kcarcia** [comment]
TESTERS: Make a really long project name. Go to your user page. Verify this long project name doesn't break the layout.

**Comment by stowellm** [comment]
PASSED testing on Chrome 42.0.2311.135 (linux).
DISREGARD THIS IS JUST A TEST

**Comment by stowellm** [comment]
PASSED testing on Chrome 42.0.2311.135 (linux).
TESTING

**Comment by bdonald25** [comment]
PASSED testing on Chrome 42.0.2311.135 (mac).

**Comment by JKinsman** [comment]
FAILED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).
Still overflows on small screens, when the user has a long name that is not truncated. :(

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
