### ISSUE TITLE
Edit fields page: can add multiple timestamps

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2114]
**General description:** Made a project, went to add fields, incremented the amount of numbers I wanted to add to "10."  Then I decided, "No, I'm actually going to hit 'Add Timestamp' now."  It added 10 timestamps.

**live/dev/localhost:** dev (any)
**iSENSE Version:** 6.5
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu LTS 14.04
**Browser/Version:** Chrome 41

**Steps to Reproduce:** See description.

**Associated Image(s):**
![2manytiemstmpas](https://cloud.githubusercontent.com/assets/1039162/7159255/e33714f4-e34e-11e4-8221-abe5c9d77b33.png)

**Comment by kcarcia** [comment]
TESTERS: You shouldn’t be able to add multiple timestamps (or location fields) to the table.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 42.0.2311.135 (mac).

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
