### ISSUE TITLE
Data set check boxes misaligned on project#show page

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2115]
**General description:** See image - I'm logged in as "User A" at the time.  Perhaps the "Edit | Delete" buttons are getting a `View.GONE` flag as opposed to `View.INVISIBLE` (sorry, Android terminology - I don't know the web equivalent)?

**live/dev/localhost:** localhost
**iSENSE Version:** 4-15-15 (??)
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 41

**Steps to Reproduce:** Create a project.  Contribute data with 2 users.  Note misaligned checkboxes in the data sets box.

**Associated Image(s):**
![dataset10omelletes](https://cloud.githubusercontent.com/assets/1039162/7159444/2677fc14-e350-11e4-88a9-f874ae5e1ec9.png)

**Comment by kcarcia** [comment]
TESTERS: Add data to a project as 2 different users (one who owns the project and one who doesn't). Then, make sure the layout of the data sets portion of the page doesn't break like it does as shown above.

**Comment by stowellm** [comment]
PASSED testing on Chrome 42.0.2311.135 (linux).
DISREGARD THIS IS JUST A TEST

**Comment by stowellm** [comment]
FAILED testing on Chrome 42.0.2311.135 (linux).
TESTING

**Comment by bdonald25** [comment]
PASSED testing on Chrome 42.0.2311.135 (mac).

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
