### ISSUE TITLE
Setting map to default vis breaks timeline

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2116]
**General description:** When visualizing data sets with a valid map and timeline, setting the map to the default vis causes the timeline to break with a console error of `Uncaught TypeError: Cannot read property 'getCenter' of undefined`.  This occurs in both Vis1.0 and Vis2.0.

**live/dev/localhost:** dev
**iSENSE Version:** 6.5
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu LTS 14.04
**Browser/Version:** Chrome 41

**Steps to Reproduce:** Create project.  Add data with time, numbers, locations.  Visualize.  Look at timeline.  Note it works.  Go to map and hit "Make Default."  Go back to timeline.  Note it shows up blank.  Refreshing brings it back though.

**Associated Image(s):**

**Comment by kcarcia** [comment]
TESTERS: Create a project, and add ad data with time, numbers, locations. Verify that the timeline works. Go to map and hit "Make Default." Go back to timeline, and verify it is still there. Also please check the console for any errors.

**Comment by bdonald25** [comment]
FAILED testing on Chrome 42.0.2311.135 (mac).
Timeline works but I still get the console error.

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).

**Comment by kcarcia** [comment]
Issue for console error is here #2126
