### ISSUE TITLE
API docs don't have how to log in

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2117]
**General description:** There's no indication in the API docs on how to make a request to log in.
EDIT: I've discovered it's via "/api/v1/users/myInfo", but that's not obvious.  Should update text so users can know.

**live/dev/localhost:** dev
**iSENSE Version:** v6.5-299-g38fc196
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Mac OS X
**Browser/Version:** Chrome 41

**Steps to Reproduce:** Go to API docs.  Note no login info.

**Associated Image(s):**

**Comment by bdonald25** [comment]
This isn't a bug. You don't log in with our api. Every request requires a username and password. The myInfo request does not log you in, it just gives you information about your user and your gravatar.
