### ISSUE TITLE
Saved vises with regressions from many generations are all broken

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#2118]
**General description:** 
- Bad things are happening with pre-Jake's-migration era saved vises with regressions
http://rsense-dev.cs.uml.edu/visualizations/117
http://isenseproject.org/visualizations/117

- Bad things are happ:goat:ing with post-Jake's-migration as well
http://rsense-dev.cs.uml.edu/visualizations/477 -> TypeError: data.fields[savedReg.yAxis] is undefined
http://rsense-dev.cs.uml.edu/visualizations/475 -> TypeError: window.subtract is not a function

- I don't even know what to say about this one
http://rsense-dev.cs.uml.edu/visualizations/471

**live/dev/localhost:** live
**iSENSE Version:** v6.7
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Firefox 39.0

**Steps to Reproduce:** Browse old saved vises who:elephant:  thumbnails shows regression lines.

**Comment by stowellm** [comment]
Cutoff point on live:
Broken: http://isenseproject.org/visualizations/210
Warning: http://isenseproject.org/visualizations/230

**Comment by JKinsman** [comment]
I believe @jaypoulz and I determined this is not actually a bug, but rather a result of me running a version of my migration that I (thought) worked on dev breaking things a few weeks ago.  Everything looked okay when we tested the current version of the migration on a backup of live on Thursday.

**Comment by kcarcia** [comment]
@jaypoulz @JKinsman This okay to be closed then?

**Comment by JKinsman** [comment]
As far as I'm concerned, but I'd verify with @jaypoulz first.

**Comment by jaypoulz** [comment]
We can't close this because we should look into saved vises prior to the regression patch. However, it is no longer high priority.
