### ISSUE TITLE
Long data set names cause overflow

### ISSUE THREAD

**Issue by jdaigneau** [isenseDev/rSENSE#2124]
General description:
Entering a long dataset name and then visualizing the dataset causes the project name, dataset name, and user name to overflow off the page.

live/dev/localhost: dev
iSENSE Version: v6.7
Logged in (Y or N): Y
Admin (Y or N): N

OS: Mac OSX 10.9.5
Browser/Version: Chrome 42.0

Steps to Reproduce: Create a dataset with really long name.

**Comment by pat-son** [comment]
PASSED testing on Chrome 52.0.2743.116 (Ubuntu 16.04 LTS).
