### ISSUE TITLE
Edit fields table v2.0

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2125]
**General description:** For the second iteration of the edit fields table, rows should be able to be reordered. I envision adding a second column to the table (all the way to the left) with up and down arrows. Clicking up will move the row up once. Clicking down will move the row down once. A few things to note:

Up/down arrows can be found on font awesome.

In app/views/projects/edit_fields.html.erb, be sure to add an additional < th > before the first column, < th >Name< /th >. You also have to add an additional row with these buttons in the actual table in this file.

In app/assets/javascripts/projects/edit_fields.js.coffee, the code to make rows reorder is as follows:
```
$('#fields_table').on 'click', '.up, .down', ->
      row = $(@).parents('tr:first')
      if $(@).is('.up')
        row.insertBefore(row.prev())
      else
        row.insertAfter(row.next())
```

In app/assets/javascripts/projects/edit_fields.js.coffee, you must also add an additional column to the rows being dynamically added on click. Basically, you will need to add another parameter to the addRow call, and modify that function accordingly.

You will need to add a field in the database to individual fields. With every field, a display field id should be associated with it.

When you reorder fields their display id should change.

Fields in the table and in the fields box on the projects page should be reordered by this display id field.

**live/dev/localhost:** live
**iSENSE Version:** v6.7
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** Macintosh
**Browser/Version:** Chrome 42.0.2311.90

**Steps to Reproduce:**

**Comment by bdonald25** [comment]
Testers: Re-order fields from the edit fields menu. Make sure that the fields are in the new order everywhere in the project.

**Comment by pat-son** [comment]
FAILED testing on Chrome 45.0.2454.99 (mac).
Does not work; not with template fields nor manually entered fields

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).
