### ISSUE TITLE
Console error on timeline vis

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2126]
**General description:** Console error on timeline visualization: Uncaught TypeError: Cannot read property 'getCenter' of undefined

**live/dev/localhost:** live
**iSENSE Version:** v6.7
**Logged in (Y or N):** Y
**Admin (Y or N):** N/A

**OS:** Macintosh
**Browser/Version:** Chrome 42.0.2311.90

**Steps to Reproduce:** 1. Create project.
2. Add data with time, numbers, locations.
3. Visualize.
4. Look at timeline. Note it works.
5. Go to map and hit "Make Default."
6. Go back to timeline. Note console message.

1

**Comment by asalani93** [comment]
Already fixed by #2116
