### ISSUE TITLE
histogram tooltip should show exact value of sample (not bin-rounded value)

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2127]
The tooltip popup on histogram does a lovely job highlighting that you're inspecting exactly one sample.

But, I'd like it to show the exact value of the sample that has been binned. Right now, it seems to round off to fit into the bin.

See below, from http://isenseproject.org/projects/395/data_sets/8618.

![screen shot 2015-05-09 at 11 46 51 am](https://cloud.githubusercontent.com/assets/1038856/7550888/5253e7fe-f641-11e4-9b29-79f7b78fc2ff.png)

**Comment by asalani93** [comment]
TESTERS: However over values and make sure that it shows both the bin the block corresponds to, and its value.

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
PASSED testing on Firefox 40.0 (linux).
