### ISSUE TITLE
browser window title capitalizes name of data set when it should not

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2128]
See attached. In the tab, the name of the window/dataset is "Ps...".  It should be "ps...".

![screen shot 2015-05-09 at 11 57 00 am](https://cloud.githubusercontent.com/assets/1038856/7550906/85fa1fe6-f642-11e4-8e39-1f2d8e72d896.png)

**Comment by bdonald25** [comment]
Testers: Go to a vis for a single data set. Make sure the data set name in the browsers tab is not capitalized.

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
PASSED testing on Firefox 40.0 (linux).
