### ISSUE TITLE
Certain data sets cause histogram to make browser freeze

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2132]
**General description:** At least one known data set causes the histogram to make the browser become unresponsive.  This occurs when you select histogram as a vis from the list of vises.

**live/dev/localhost:** dev/localhost
**iSENSE Version:** 6.7?
**Logged in (Y or N):** Y/N
**Admin (Y or N):** Y/N

**OS:** Ubuntu 14.04, x64
**Browser/Version:** Chrome 42, 64-bit

**Steps to Reproduce:**
* Visualize any histogram aside from the one linked below
* Observe that the page works when you click things
* Go to: http://rsense-dev.cs.uml.edu/projects/1005
* Alternatively, download that CSV file and upload it elsewhere
* Visualize the data set
* Switch to histogram
* Observe as the page no longer responds to user input and CPU usage spikes to 100%

**Associated Image(s):**
nah

**Comment by jaypoulz** [comment]
This is a good example of freezy mcfreeze.
http://rsense-dev.cs.uml.edu/projects/1004/data_sets/8709

I'll look into this tomorrow.

**Comment by bdonald25** [comment]
Testers: Go to the data set posted above. Make sure it doesn't freeze when you look at the histogram.

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
PASSED testing on Firefox 40.0 (linux).
