### ISSUE TITLE
Can't change data set name from vis page

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2136]
**General description:** Giving a data set a title longer than 128 characters from the vis page causes a redirect to the manual entry page with console errors.

**live/dev/localhost:** dev
**iSENSE Version:** 6.7
**Logged in (Y or N):** Y
**Admin (Y or N):** Y/N

**OS:** Ubuntu 14.04 x64
**Browser/Version:** Chrome 42 x64

**Steps to Reproduce:**

First, do this to observe correct (read: sensible) behavior:
* Visualize a data set that you own
* Click "Edit"
* Click "Edit Title"
* Change the title to something other than what it is now, but make sure it is less than 128 characters
* Click the floppy disk
* Note that you are redirected back to the vis page and the title has changed

Now, the incorrect behavior:
* Visualize a data set that you own
* Click "Edit"
* Click "Edit Title"
* Change the title to something longer than 128 characters
* Click the floppy disk
* Note that you are redirected to a broken manual entry table with the title you provided
* Click back to the project
* Note that the title didn't actually change

**Associated Image(s):**

**Comment by pat-son** [comment]
This issue was also present when renaming visualizations. It has been fixed in #2469.

**Comment by pat-son** [comment]
Testers: Try to give a data set/visualization a name longer than 128 characters and make sure it redirects you back to the same page with the correct error message.

**Comment by pat-son** [comment]
PASSED testing on Chrome 52.0.2743.116 (Ubuntu 16.04 LTS).
