### ISSUE TITLE
Can upload media objects via API to any project or data set

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2139]
**General description:** The API currently allows any logged in user to upload media to any project or data set that they feel like.

**live/dev/localhost:** live/dev/localhost
**iSENSE Version:** all
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 x64
**Browser/Version:** Chrome 42 x64

**Steps to Reproduce:**
* upload a media object to a project from a user that shouldn't be allowed to upload media to, via the API
* observe as the media uploads

**Associated Image(s):**

**Comment by jdalphon** [comment]
@asalani93 I can see that you split up the api testing, which is probably for the best. But did you write/modify any of the tests to actually test for this bug?

**Comment by asalani93** [comment]
Yes, lines 64-76 of api_v1_media_objects_test.rb.

**Comment by asalani93** [comment]
TESTERS: This is an API thing.  Don't bother testing it.

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
PASSED testing on Firefox 40.0 (linux).
