### ISSUE TITLE
no way to select field in mobile view

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2140]
Hey, Mobile view of data looks pretty good now.

But there is no way to switch fields.

Can we fix? This is pretty important - we will have a bunch of iPad users this fall.

![screenshot_2015-05-19-07-27-10](https://cloud.githubusercontent.com/assets/1038856/7701802/aa358496-fdf8-11e4-9eb7-f059cbc6b7a0.png)

**Comment by jaypoulz** [comment]
This was actually by design, since the tools became cumbersome to use on mobile. My suggested fix is to make it so that in a mobile layout, tools are either full screen or totally invisible. iPads in landscape mode probably have enough room to accommodate the landscape view.

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (Ubuntu 15.04).
