### ISSUE TITLE
Spider vis

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2142]
**General description:** The labels make pi chart cluttered on mobile. It would be more useful to have a bigger pie chart. You can get the same info by pressing on each section of the chart.

**live/dev/localhost:** live
**iSENSE Version:** v7.0
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** Macintosh
**Browser/Version:** Chrome 42.0.2311.152

**Steps to Reproduce:** Go to pie chart on a project with a lot of data sets on mobile.

![screenshot_2015-05-20-23-32-55](https://cloud.githubusercontent.com/assets/4121924/7741109/0fd281d6-ff49-11e4-862f-b1cf10032f9c.png)

393

**Comment by jaypoulz** [comment]
I don't think there is much we can do for this. We simple don't have the screen real-estate. Maybe we could tweak it so that labels are in a legend on small screens?

**Comment by bdonald25** [comment]
Testers: Make sure pie chart looks sane on all screen sizes.
