### ISSUE TITLE
User page unprocessable entity for invalid char in username

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#2155]
**General description:** On your users page, if you change your name to include an unsupported character (like unicode), you'll get an error flash of "Unprocessable Entity"

**live/dev/localhost:** live
**iSENSE Version:** v7.0
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Firefox 40.0

**Steps to Reproduce:** Changing my name on my user page

9

**Comment by bdonald25** [comment]
Testers:  Try changing your username to one that contains unicode characters. Make sure the error message is reasonable.  Here's some unicode snowman ☃☃☃☃

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.132 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.132 (linux).

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.130 (linux).
