### ISSUE TITLE
Table vis search box is cut off on mobile

### ISSUE THREAD

**Issue by KatherineBrunelle** [isenseDev/rSENSE#2156]
**General description:** The mobile version doesn't show the text box for searching the table visualization.

**live/dev/localhost:** live
**iSENSE Version:** v7.0
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Safari 8.0

**Steps to Reproduce:** Release testing

3006

**Comment by bdonald25** [comment]
![screenshot_2015-06-10-10-49-10](https://cloud.githubusercontent.com/assets/4121924/8085578/e5c18d9e-0f5e-11e5-9906-4d839c0910d2.png)

**Comment by bdonald25** [comment]
@jaypoulz I think you mentioned at one point that you were working on a patch to make the number of columns based on the screen size. Is that still true? If so then that would address this bug.

**Comment by jaypoulz** [comment]
I haven't gotten around to it yet since I've been working on data clipping. If you want to go ahead with this, please do so as my hours are about to get cut even shorter.

**Comment by bdonald25** [comment]
Testers: Look at table visualization on a project that has a lot of fields. The number of columns should be reasonable based on your screen size. Test this using your phone and pc.
