### ISSUE TITLE
Slickgrid text field values not persisting across edits

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2157]
**General description:** Selecting a value from a text field in either the data set edit table or manual entry table makes that value vanish.

**live/dev/localhost:** dev
**iSENSE Version:** 7.1
**Logged in (Y or N):** Y
**Admin (Y or N):** Y/N

**OS:** Ubuntu 14.04 x64
**Browser/Version:** Chrome 42 x64

**Steps to Reproduce:**
* Edit a data set with text fields
* Highlight a text field
* Observe as the text field vanishes

**Associated Image(s):**

**Comment by bdonald25** [comment]
Testers: Edit data -> click on a text field -> verify data did not disappear

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
