### ISSUE TITLE
Error bars on bar chart don't when data is logarithmic and negative

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2158]
**General description:** See title

**live/dev/localhost:** dev
**iSENSE Version:** 7.1
**Logged in (Y or N):** Y/N
**Admin (Y or N):** Y/N

**OS:** Ubuntu 14.04 x64
**Browser/Version:** Chrome 42 x64

**Steps to Reproduce:**
* Visualize a bar chart with error bars such that the analysis type would end up displaying negative numbers
* Observe as High Charts throws a fit trying to plot it

**Associated Image(s):**

**Comment by bdonald25** [comment]
1. Visualize "Mean with Error" on a bar chart with negative numbers. Verify that it works the same as with positive numbers. 

2. Visualize "Mean with Error" on a bar chart that contains a logarithmic y-axis (you set this under tools). The error bar should only be shown on the top half of the graph.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
