### ISSUE TITLE
Bar chart zero line doesn't stand out

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2160]
**General description:** Bar charts with positive and negative bars look like abstract art.  Make the bar thicker to delineate where zero is.  Otherwise, it looks like you have floating bars and that's weird.

**live/dev/localhost:** yes
**iSENSE Version:** 7.1
**Logged in (Y or N):** Y/N
**Admin (Y or N):** Y/N

**OS:** Ubuntu 14.04 x64
**Browser/Version:** Chrome 42 x64

**Steps to Reproduce:**
* Visualize bar chart on a combination of data sets that have both positive and negative means
* Switch analysis type to mean

**Associated Image(s):**
![abstract-art](https://cloud.githubusercontent.com/assets/7584534/7913646/acc279a2-083f-11e5-808f-a7edd1575329.png)

**Comment by bdonald25** [comment]
Testers: Make sure the origin line in bar chart is always darker. Try looking at a bar chart that contains negative numbers like the one above.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
