### ISSUE TITLE
On chrome 43, vises are sometimes cut in half.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2161]
**General description:** On chrome 43, vises sometimes are cut in half.

**live/dev/localhost:** live
**iSENSE Version:** v7.1
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 43.0.2357.81

**Steps to Reproduce:** Looking at vises.

393

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).
