### ISSUE TITLE
Barchart should sort by selected field

### ISSUE THREAD

**Issue by jdalphon** [isenseDev/rSENSE#2163]
**General description:** Barchart should sort by the selected field when only one field is selected. This used to happen and is now undone. 

**live/dev/localhost:** live
**iSENSE Version:** v7.1
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Chrome 40.0.2214.115

**Steps to Reproduce:** Go to any visualization of a bar chart. Select a single field to view. The sort order should be automatically set to that field. 

1

**Comment by bdonald25** [comment]
Testers: Go to a barchart. If only one field is selected then it should sort by that field by default.

**Comment by pat-son** [comment]
PASSED testing on Firefox 44.0.2 (Mac OSX Yosemite 10.10.5).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by JasonD94** [comment]
PASSED testing on Chrome 48.0.2564.97 (Linux Ubuntu 14.04 LTS).
