### ISSUE TITLE
Button to select bin size on histogram.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2168]
**General description:** Button to select bin size.

**live/dev/localhost:** live
**iSENSE Version:** v7.1.1
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 43.0.2357.81

**Steps to Reproduce:** 

393

**Comment by jaypoulz** [comment]
This is *facepalm*. But do what you must.

**Comment by bdonald25** [comment]
Testers: Change the bin size of histogram and check that the save button works as expected.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).
the button stays clicked after you click it

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
