### ISSUE TITLE
Icons on the bottom of the project boxes overflow.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2169]
**General description:** Icons on the bottom of project boxes overflow.

**live/dev/localhost:** live
**iSENSE Version:** v7.1.1
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 43.0.2357.81

**Steps to Reproduce:** On the project index page.

![overflow](https://cloud.githubusercontent.com/assets/4121924/7992248/1082f12c-0acc-11e5-8db5-6fb9fa591035.png)

393

**Comment by bdonald25** [comment]
Testers: Try re-sizing the width of your browser and verify that the icons no longer overflow like in the image above.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).
Doesn't work for 3 different 5-digit numbers

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
