### ISSUE TITLE
Data set search button cuts off on mobile.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2171]
**General description:** Search data set button cut off on mobile.

**live/dev/localhost:** live
**iSENSE Version:** v7.1.1
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 43.0.2357.81

**Steps to Reproduce:** On a Project's page looking at it's data sets.

393

**Comment by bdonald25** [comment]
Testers: Re-size the width of your browser to verify that the search button for searching data sets on a project page no longer cuts off on small screens.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
FAILED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
