### ISSUE TITLE
should be able to sort "my projects" by creation date

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2174]
Hi all, I'm not even sure the default sort order.

But I'd *definitely* like reverse-chronological (newest-created first), as an option (by clicking on "Created").

Probably as a default.

**Comment by bdonald25** [comment]
Testers: Try sorting your contributions on your profile page.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
