### ISSUE TITLE
"Showing Multiple Data Sets" should be shortened (and display a number)

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2177]
The phrase "Showing Multiple Data Sets" uses up lots of screen real estate, esp. on school-sized monitors.

Let's revise it to say (e.g.) "3 Data Sets" <project name>

Also, change "of" to "from".

![multiple-data-sets](https://cloud.githubusercontent.com/assets/1038856/8059190/a3c6a26c-0e8c-11e5-9784-da525dd9124d.png)

**Comment by bdonald25** [comment]
Testers: Verify that visualizations for multiple data sets now have a title that indicates the number of data sets.

**Comment by fgmart** [comment]
Hey all, what happened to this, is it still in the works?

**Comment by bdonald25** [comment]
It's done but not on live yet. It will be in the next release.

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.132 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.132 (linux).

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.130 (linux).
