### ISSUE TITLE
bargraph view should default to mean

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2178]
It's the most common use of bar.

right now the default of total is confusing.

probably mean should first in the list too.

**Comment by bdonald25** [comment]
Testers: Make sure bar graph defaults to mean and that mean is the first analysis type.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).
