### ISSUE TITLE
Add a period option to timeline

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2179]
**General description:** When comparing periodic data on the timeline vis (like temperatures or something), it would be useful to be able to visual this data periodically, ie: it displays data starting from January 1st to December 31st, and then once the next year starts it wraps around back to January 1st and starts on the left side of the vis again.
There could be options for different periods (yearly, monthly, daily, etc...), too.
One use case for this is the boat house: the tablet applications wouldn't need to set the year to 2010 just to have the data be comparable on timeline.

**live/dev/localhost:**
**iSENSE Version:**
**Logged in (Y or N):**
**Admin (Y or N):**

**OS:**
**Browser/Version:**

**Steps to Reproduce:**

**Associated Image(s):**

**Comment by jdalphon** [comment]
+1

**Comment by bdonald25** [comment]
Testers: Make sure time period options work and grouping by time period.

**Comment by VictoriaAlbanese** [comment]
Couldn't find any bugs with the time period stuff
-Passed

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).

**Comment by doug-salvati** [comment]
Period appears for all visualizations but only seems to do anything on timeline.

I assume when I pick "monthly" it is showing all months on top of each other.  It would be nice to be able to filter by month.
As far as I can tell, it is not possible to save a Date filter without getting something like "Date contains Invalid Date"

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.86 (OSX 10.11.3).
Wow, this is a great feature. Whoever wrote this is pretty good.

**Comment by pat-son** [comment]
@doug-salvati The period option for other vises is for the group-by option.
