### ISSUE TITLE
Trouble with deleting projects that were cloned

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2180]
**General description:** Deleting a project that was cloned renders the resulting cloned projects unviewable.  This is because the `is_deleted?` function in `projects_helper.rb` still relies on the old way we deleted things (ie: not deleting them).  It will ALWAYS return false (as in not deleted), so then code will try and access that project that doesn't exist.

**live/dev/localhost:** live/dev/localhost
**iSENSE Version:** v7.1
**Logged in (Y or N):** Y/N
**Admin (Y or N):** Y/N

**OS:** Ubuntu 14.04 x64
**Browser/Version:** Chrome 43 x64

**Steps to Reproduce:**
* create a project with no data sets (so you can delete it)
* clone the project
* delete the project you cloned from
* view the project that is a clone
* observe the oops

**Associated Image(s):**

**Comment by asalani93** [comment]
TESTERS:
Make a project with field but no data.  Clone that project.  Delete the original project.  View the cloned project.  Does this work correctly?

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
FAILED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).

**Comment by bdonald25** [comment]
Quina failed it because she couldn't delete a cloned project. The reason she couldn't was because it had data. That is a feature not a bug.
