### ISSUE TITLE
Can't sort photos

### ISSUE THREAD

**Issue by smichalka** [isenseDev/rSENSE#2187]
**General description:**
The Water SCIENCE program would like to be able to have the same "Group by" option for the Photos to allow them to look at a particular team's photos.

**live/dev/localhost:**
**iSENSE Version:**
**Logged in (Y or N):**
**Admin (Y or N):**

**OS:**
**Browser/Version:**

**Steps to Reproduce:**

**Associated Image(s):**

**Comment by bdonald25** [comment]
Testers: Upload images to different data sets. When you visualize them together you should be able to group by data set. Make sure this works as expected.

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.81 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.125 (linux).

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by smichalka** [comment]
Awesome.  This looks great.  Thanks so much everyone (especially Bobby, I
assume)!

**Comment by jaypoulz** [comment]
@smichalka Actually Anthony did the work for this one :smile: Go go @asalani93
