### ISSUE TITLE
Local HTML5 validation

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#2194]
**General description:** Our HTML5 validator has a bad track record for uptime. We should either use the same validation locally or find another option we can use locally.

**live/dev/localhost:** live
**iSENSE Version:** v7.1.1
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Firefox 40.0

**Steps to Reproduce:** Looked at some reasonable pull requests, and noticed the were failing tests because of validation timeouts.

9

**Comment by pat-son** [comment]
Closing as this issue has not been observed in the year that I've been here.
