### ISSUE TITLE
Crash the iSENSE project index with this one weird trick!

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2196]
**General description:** You can crash the iSENSE project index page by uploading, deleting and featuring a media object in that order.  This renders the project index unviewable by literally anyone that wants to use it.

**live/dev/localhost:** live/dev/localhost
**iSENSE Version:** 7.1?
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 x64
**Browser/Version:** Chrome 34 x64

**Steps to Reproduce:**
* Create a project
* Upload a media object that that project
* Open that project in two different tabs
* In one of the tabs, delete the media object
* In the other of the two tabs, feature the media object (must be done in this order)
* This sets the project's featured media object id to something that was deleted, which causes a 500 error when the project index page goes looking for it
* Go to the project index page and observe beakerman
* Don't do this on live

**Associated Image(s):**

**Comment by bdonald25** [comment]
Testers: Try and break iSENSE using the method above.

**Comment by asalani93** [comment]
FAILED testing on Chrome 43.0.2357.81 (linux).
doesn't work on vis page

**Comment by bdonald25** [comment]
FAILED testing on Chrome 43.0.2357.125 (linux).
Doesn't work for saved vises.

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.130 (mac).

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).

**Comment by bdonald25** [comment]
#2202 New bug for saved vises
