### ISSUE TITLE
Can crash the vis index the same way as the project index

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2202]
**General description:**
Same as #2196, but for the vis index page this time.

**live/dev/localhost:** live
**iSENSE Version:** 7.2
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 x64
**Browser/Version:** Chrome 43 x64

**Steps to Reproduce:**
* Same as before

**Associated Image(s):**

**Comment by bdonald25** [comment]
Testers: Follow the steps on #2196 but for saved vises.

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.132 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.132 (linux).

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.130 (linux).
