### ISSUE TITLE
Detailed tool tips on timeline don't show

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2203]
**General description:**
It's like some sort of bug or something.

**live/dev/localhost:** live
**iSENSE Version:** 7.2
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 x64
**Browser/Version:** Chrome 43 x64

**Steps to Reproduce:**
* Click "Detailed Tooltips"
* Mouse over a timeline
* Observe the lack of tooltips

**Associated Image(s):**

**Comment by bdonald25** [comment]
Testers: Verify that detailed tool tips work on scatter.

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.132 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.132 (linux).

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.130 (linux).
