### ISSUE TITLE
Visualization search has no placeholder text.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2207]
**General description:** Visualization search does not have a placeholder.

**live/dev/localhost:** live
**iSENSE Version:** v7.2
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 43.0.2357.130

**Steps to Reproduce:** On vis index page.

![screenshot from 2015-06-25 10 24 01](https://cloud.githubusercontent.com/assets/4121924/8356628/871604d8-1b24-11e5-80f2-8473855db0a4.png)
![screenshot from 2015-06-25 10 23 48](https://cloud.githubusercontent.com/assets/4121924/8356629/871b4c72-1b24-11e5-9b18-6b47079a257a.png)

393

**Comment by bdonald25** [comment]
Testers: Verify that visualization search box had placeholder text now.

**Comment by qianacurcuru** [comment]
PASSED testing on Chrome 43.0.2357.132 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.132 (linux).

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.130 (linux).
