### ISSUE TITLE
Scatter touchscreen issue

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2211]
**General description:** Scatter plot has touch screen problem with dragging graph.

**live/dev/localhost:** live
**iSENSE Version:** v7.2
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 43.0.2357.130

**Steps to Reproduce:** 
Scatter lets you pinch to zoom. That works fine.
It also lets you drag the graph, but when you lift your finger it resets.

393

**Comment by pat-son** [comment]
I think it's supposed to do that. It only resets if you try to move the view to an area with no data, i.e. it tries to keep the chart bounds from going past the furthest data points.

**Comment by bdonald25** [comment]
@pat-son I just checked and it seems to work fine now. 

I remember looking into this at one point in time and I found the same thing you did, where you could not move the view past the data.  However, at that point in time, we would filter the data when you zoomed in so the data outside the view did not exist. That meant you couldn't move the view at all when you zoomed in. It looks like we don't do that anymore.

**Comment by bdonald25** [comment]
By "we don't do that anymore" I mean "Pat does not do that anymore" :)
