### ISSUE TITLE
Side effects from time zone changes

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#2212]
**General description:** Timestamps for project 65 have all gone whacky. Many of them now appear as if data was collected at 8pm, when almost all  info is collected in 8-11 am (some data collected from 11am - 3pm). 

**live/dev/localhost:** live
**iSENSE Version:** v7.2
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Windows
**Browser/Version:** Chrome 43.0.2357.81

**Steps to Reproduce:** visualizing the data and looking at particular entries using timeline & table visualizations

281

**Comment by bdonald25** [comment]
The issue here is that we assume uploaded data is GMT in timezone if they do not provide timezone info. We need a better way for users to specify the timezone for their data at upload time.

**Comment by bdonald25** [comment]
Time stamps were previously elusively in GMT timezone. 

Now they are displayed in local timezone, manual entry is done in local timezone, and uploaded files are considered GMT if there is no timezone info.

The issue is that people were previously entering in time in GMT but assuming it to be local. Now they are confused as to why the time is now different. 

We are conflicted about how to handle these cases as some people were aware that they were entering time in GMT and others assumed it to be local.

**Comment by jaypoulz** [comment]
Proposed - three part fix
1. Project option: Display Time Zone (DTZ)
```
Defaults to: localtime
Addresses timezone used for display
```

2. Data set option: Recorded Time Zone (RTZ)
```
Defaults to: GMT for existing data sets, localtime for new data sets
Modifies (at runtime) or migrates the underlying time values for the data set to the correct GMT
```

3. Multi data set option: Migrate Time Zones
```
Allows for multiple data sets to be selected and sets their RTZ to a user chosen value
```

- Rationale -
Old data was assumed to be recorded in GMT. To change the default RTZ on pre-existing data would be punishing the users that recorded correctly. New data should be assumed to be recorded in localtime, although perhaps a UI note should be displayed at upload time reminding them of this. The migrate time zone option will allow users to update their time data for data sets that they uploaded incorrectly. My presumption is that running through the data on the server side to adjust time values according to the RTZ prior to sending it to the vis is the right way to handle this - this way data never gets modified.

**Comment by bdonald25** [comment]
We ended up deciding that the way we do timezones now (local time zones) is correct and although some users might have misunderstood that it was GMT before and not their local time zones we can handle those cases on a case by case basis if they ever come up.
