### ISSUE TITLE
Visualizations page should default to 

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2216]
Presently it sorts by last-modified.

That's the right default for projects, but viz's typically aren't modified after they're created, so we really want creation-date sort to bring the newer ones to the top.

Right?

**Comment by bdonald25** [comment]
Testers: Make sure the visualization index page is sorting by creation date by default.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.132 (linux).

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.130 (linux).
