### ISSUE TITLE
Color picker hue bar descends too far

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2221]
**General description:** The bar that picks the hue on the colorpicker can end up way far away from where it should be

**live/dev/localhost:** live
**iSENSE Version:** 7.1
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu 14.04.1 x64
**Browser/Version:** Chrome 43 x64

**Steps to Reproduce:**
* go to a vis w/ a colorpicker
* click the colorpicker
* try and find the bar that changes the hue
* hint: it's at the bottom of the page

**Associated Image(s):**

**Comment by bdonald25** [comment]
Testers: Test that the vis page height does not grow when color picker is opened.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.132 (linux).

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.130 (linux).
