### ISSUE TITLE
Enter on Google Docs form doesn't submit

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2222]
**General description:** see title

**live/dev/localhost:** live
**iSENSE Version:** 7.1
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04.1 x64
**Browser/Version:** Chrome 43 x64

**Steps to Reproduce:**
* go to upload a google doc spreadsheet
* press enter
* nothing happens

**Associated Image(s):**

**Comment by bdonald25** [comment]
Testers: Press the enter key after adding a google doc link and make sure it submits instead of canceling.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.132 (linux).

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.130 (linux).
