### ISSUE TITLE
Submitting a data set w/ case-incorrect contributor key lists data set as by owner

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2224]
**General description:** Submitting a data set with the contributor spelled with a different casing (ie: "sor" instead of "SOR") causes the data set's "key" field to be nil, and ends up listing the data set as by the owner of the project, and not from the contributor key.

**live/dev/localhost:** dev
**iSENSE Version:** 7.1.1
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu 14.04.1 x64
**Browser/Version:** Chrome 43 x64

**Steps to Reproduce:**
* submit data to isense through the API with a differently cased but otherwise correct version of a valid contributor key
* observe the lack of a key symbol next to the name of the data set, and the presence of the gravatar

**Associated Image(s):**

**Comment by bdonald25** [comment]
Testers: Upload data through api and use the correct key but with different casing and make sure it works. ie. If the key is "Apple" use "APPLE". 

The name that shows up next to the data set should be the contributor name and the icon should be a key.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 43.0.2357.132 (linux).

**Comment by asalani93** [comment]
PASSED testing on Chrome 43.0.2357.130 (linux).
