### ISSUE TITLE
API returns internal server error for get requests to some projects.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2231]
**General description:** API returns internal server error for get requests to some projects. (Projects that were deleted?)

**live/dev/localhost:** live
**iSENSE Version:** v7.2.2
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 44.0.2403.107

**Steps to Reproduce:** http://rsense-dev.cs.uml.edu/api/v1/projects/500

![screenshot from 2015-07-29 12 57 05](https://cloud.githubusercontent.com/assets/4121924/8964070/7912500c-35f1-11e5-97bf-6df5fe9dc062.png)

393

**Comment by bdonald25** [comment]
Testers: This fixes some projects such as isenseproject.org/projects/500 that gave the beaker man because the user who created the project was deleted.

If this project works on dev then the issue was fixed. rsense-dev.cs.uml.edu/projects/500

**Comment by pat-son** [comment]
PASSED testing on Firefox 44.0.2 (Mac OSX Yosemite 10.10.5).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by JasonD94** [comment]
PASSED testing on Chrome 48.0.2564.97 (Linux Ubuntu 14.04 LTS).
