### ISSUE TITLE
saved vis's don't have nice icons anymore

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2236]
hey, sometime after June 23, saved vis's no longer get mini-screens of the vis anymore.

i know that we never did this for maps, but we used to do this for bar, scatter, histo, etc.

See below... what happened? 

![screen shot 2015-08-12 at 2 16 50 pm](https://cloud.githubusercontent.com/assets/1038856/9232660/e941bac8-40fc-11e5-9725-d3fd1cbc1505.png)

**Comment by bdonald25** [comment]
Testers: Save a vis and make sure the thumbnails are mini-images of the vis. (does not work with maps)

**Comment by pat-son** [comment]
PASSED testing on Chrome 45.0.2454.99 (mac).
