### ISSUE TITLE
news page only provides one screen of results

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2237]
The news page only displays the most recent 10 items. It does not provide a way of paging to earlier items.

Please fix.

**Comment by fgmart** [comment]
this bug also exists for tutorials:

https://isenseproject.org/tutorials

shows 8, but there are more than this.

**Comment by bdonald25** [comment]
Testers: Make sure news and tutorial index pages have more than one page of results.

**Comment by pat-son** [comment]
PASSED testing on Chrome 45.0.2454.99 (mac).
