### ISSUE TITLE
Saving a vis redirects to weird URL

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2238]
**General description:**
Saving a visualization on dev redirects to:
`http://rsense-dev/visualizations/{{visualization-id}}`
Should be:
`http://rsense-dev.cs.uml.edu/visualizations/{{visualization-id}}`

Saving a visualization on live redirects to:
`https://isenseproject.orgvisualizations/{{visualization-id}}`
Should be:
`https://isenseproject.org/visualizations/{{visualization-id}}`

*Update:* On Firefox, saving a visualization doesn't even successfully redirect.

**live/dev/localhost:** live/dev
**iSENSE Version:** 7.2.2
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Chrome 45 x64
**Browser/Version:** Ubuntu 14.04.1 x64, Window 8 x64

**Steps to Reproduce:**
* Save a visualization

**Associated Image(s):**

**Comment by asalani93** [comment]
TESTERS:
There are two fixes for this issue, neither of which are pull requests.  Test live and dev separately.

**Comment by pat-son** [comment]
PASSED testing on Chrome 45.0.2454.99 (mac).
