### ISSUE TITLE
Deleting same saved vis twice from user profile gives unhelpful error message

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2239]
**General description:**
Clicking "delete" on a vis from the show users page gives "[object Object]" as the error message.

This is exceptionally minor, but I thought I'd just throw it up here so I can lump this in with the rest of the stuff I'm fixing

**live/dev/localhost:** live/dev
**iSENSE Version:** 7.2.2
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 14.04.1 x64
**Browser/Version:** Chrome 43 x64

**Steps to Reproduce:**
* save a vis
* open your user profile in two tabs
* in the first one, delete the saved vis
* in the second one, delete the same saved vis
* observe the default JS object toString() return value being reported as a bug

**Associated Image(s):**

**Comment by bdonald25** [comment]
FAILED testing on Chrome 49.0.2623.87 (linux).
It silently blows up.

**Comment by tylerpuleo** [comment]
FAILED testing on Chrome 49.0.2623.87 (linux).

ERROR: Failed to load resource: the server responded with a status of 406 (Not Acceptable)

**Comment by pat-son** [comment]
PASSED testing on Chrome 49.0.2623.87 (OSX 10.11.3).
Technically passed: originally stated issue was fixed.
