### ISSUE TITLE
Arrows in table vis point up

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2245]
**General description:** The arrows in the table vis point up.  This is not ideal, as up is not a valid navigation direction.

**live/dev/localhost:** live/dev/localhost
**iSENSE Version:** 7.2.2
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu 14.04.3 x64
**Browser/Version:** Chrome 43 x64

**Steps to Reproduce:**
* go to table vis

**Associated Image(s):**
![advanced](https://cloud.githubusercontent.com/assets/7584534/9389598/f6f75090-4739-11e5-8698-e917196ecaa8.png)

**Comment by bdonald25** [comment]
Testers: Go to table visualization and make sure the arrows in the image above are no longer pointing up.

**Comment by pat-son** [comment]
PASSED testing on Chrome 45.0.2454.99 (mac).
