### ISSUE TITLE
Deleting a project doesn't delete its fields

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2252]
**General description:** Really annoying

**live/dev/localhost:** localhost
**iSENSE Version:** ???
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu 15.04 x64
**Browser/Version:** Chrome x64 some version

**Steps to Reproduce:**
* delete a project with fields
* record the ID
* open the rails console and find the project with that ID
* observe that the project doesn't exist
* try and find all fields from the project ID
* observe that they do exist
* observe why this is really annoying

**Associated Image(s):**

**Comment by jdalphon** [comment]
@asalani93 @bdonald25 Whoever fixes this, its half a line of code. In the projects model just change the has_many for fields. 

 ```ruby
has_many :fields, :dependent => :destroy
```

**Comment by bdonald25** [comment]
Testers: Ignore this.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).

**Comment by tylerpuleo** [comment]
Ignored
