### ISSUE TITLE
Searching a data set with a number only searches ids

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2257]
**General description:** Searching a data set with a number only searches ids

**live/dev/localhost:** live
**iSENSE Version:** v7.2.2
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 45.0.2454.99

**Steps to Reproduce:** 

393

**Comment by pat-son** [comment]
PASSED testing on Chrome 45.0.2454.99 (mac).
