### ISSUE TITLE
this project breaks viz badly

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2261]
check it out team: http://isenseproject.org/projects/1350/data_sets/12204,12203,12010,12009

yikes?

![screen shot 2015-09-28 at 12 16 38 pm](https://cloud.githubusercontent.com/assets/1038856/10141513/ea0d09f0-65da-11e5-8054-04e7adea642d.png)

All of FF, Chrome, Safari are unhappy

**Comment by jdalphon** [comment]
@fgmart This is fixed temporarily on live. The fix was to turn off error bars for where there is null values. @asalani93 the problem is when you are computing error bars, null values are not handled correctly.

**Comment by pat-son** [comment]
Testers: Download the data from the above project. Go to the bar graph. Group by "Method", and choose Weight of Aluminum Block for Y-axis. Turn on Mean With Error and make sure that everything renders correctly.

**Comment by pat-son** [comment]
PASSED testing on Chrome 52.0.2743.116 (Ubuntu 16.04 LTS).
