### ISSUE TITLE
Map visualization is enabled when there is no location data.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2262]
**General description:** Map visualization is enabled when there is no location data. 

**live/dev/localhost:** live
**iSENSE Version:** v7.3.0
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 45.0.2454.101

**Steps to Reproduce:** 

393

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (Ubuntu 15.04 x64).
==yes==

**Comment by bdonald25** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).

**Comment by tylerpuleo** [comment]
FAILED testing on Chrome 45.0.2454.101 (Mint).
Datasets uploaded before the location fields were added still enable the map.

Steps to reproduce: Create a project with number and or text fields. Upload a dataset using these fields. Add location fields. Look at old datasets and map will be enabled.

# NO

**Comment by bdonald25** [comment]
@pat-son 
We are still going to release the current fix you made because it does fix the problem for every case except data sets that already existed. I will leave this issue open for you to fix that last issue.

**Comment by bdonald25** [comment]
Testers: Create a project that contains location fields. Upload data that contains data for other fields but does not contain location data. Make sure the map visualization is not enabled.
