### ISSUE TITLE
Capitalization lost in "Group by" function

### ISSUE THREAD

**Issue by smichalka** [isenseDev/rSENSE#2265]
When text is entered into a data set, the capitalization pattern is lost in the "Group by" function.  This is important for classroom use, as it often results in proper nouns without capitalization.

For example see:
http://isenseproject.org/projects/1386/data_sets/12477,12468,12467
and group by country.

**Comment by bdonald25** [comment]
Testers: Make sure the capitalization in in the "Group by" drop down on the visualization page is correct.

**Comment by asalani93** [comment]
FAILED testing on Chrome 45.0.2454.101 (linux).

**Comment by pat-son** [comment]
FAILED testing on Chrome 46.0.2490.80 (Mac OSX 10.10.5).

**Comment by JasonD94** [comment]
FAILED testing on Chrome 46.0.2490.80 (linux).

**Comment by bdonald25** [comment]
Testers: Make sure capitalization is correct for the group by options.

**Comment by pat-son** [comment]
Testers: Make sure that the capitalization is preserved in the Group-By labels, and that all aspects of the vis are working as expected.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Ubuntu 16.04).
