### ISSUE TITLE
Heat maps break when they are loaded without visible points on the screen

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2268]
**General description:** 
Heat maps break when they are loaded with no points visible on the screen.

1. Look at a heatmap.
2. Move the map so that you cannot see any of the points.
3. Set it as default vis.
4. Reload the page and try to zoom the map in or out. 
5. Notice that the map is frozen.

**live/dev/localhost:** live
**iSENSE Version:** v7.3.0
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 45.0.2454.101

**Steps to Reproduce:** 

393

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).
