### ISSUE TITLE
Uploading data set while templating uploads empty rows

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2271]
**General description:** Choosing to upload a data set when you template fields uploads a blank data set.

**live/dev/localhost:** live
**iSENSE Version:** 7.3
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 15.04 x64
**Browser/Version:** Chrome 45 x64

**Steps to Reproduce:**
* Create a project
* Template the fields from a CSV with data
* Choose to upload the data from the CSV as well
* Observe that there are no data in the new data set

**Associated Image(s):**

**Comment by bdonald25** [comment]
Testers: Template fields by uploading a csv. Make sure the option to create a data set at the same time is checked. After saving the data set should be created and contain data.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).

**Comment by pat-son** [comment]
PASSED testing on Chrome 48.0.2564.116 (OSX 10.10.5).
