### ISSUE TITLE
Filtering issues

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2272]
**General description:**
* text filters show "NaN", not the value you're filtering by
* text searching from table vis is case-insensitive, but filtering is case-sensitive

**live/dev/localhost:** dev
**iSENSE Version:** 7.4
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu 15.04 x64
**Browser/Version:** Chrome 45 x64

**Steps to Reproduce:**
* filter by text and observe thing

**Associated Image(s):**

**Comment by bdonald25** [comment]
Testers: Make sure filtering by text field is no longer cap sensitive. Make sure filters show the correct thing you are filtering by and not "NaN".

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (Ubuntu 15.04 x64).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).
