### ISSUE TITLE
Contributor name is not cleared from session after logging in.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2274]
**General description:** Contributor name is not cleared properly after logging in.

**live/dev/localhost:** live
**iSENSE Version:** v7.4.0
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Chrome 46.0.2490.71

**Steps to Reproduce:** Enter a contributor key and name. Login. Upload data. Notice the username that shows up next to the data set is the one you entered for a contributor name before logging in.

393

**Comment by bdonald25** [comment]
Testers: 
1. Enter a contribution key and name into a project. 
2. Login
3. Upload data
4. Make sure name next to data set is your user name and not the contributor name.

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (Ubuntu 15.04 x64).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).
