### ISSUE TITLE
this project breaks the visualization - media box at top, no data appears

### ISSUE THREAD

**Issue by smichalka** [isenseDev/rSENSE#2276]
This is not good:
![image](https://cloud.githubusercontent.com/assets/5709961/10645521/266e6b36-77fc-11e5-99b9-a32869bb95b7.png)

Project number 891.  However, when I cloned the project with data, everything looks fine (project 1450).

**Comment by bdonald25** [comment]
Testers: Make sure http://rsense-dev.cs.uml.edu/projects/891/data_sets/8083 is not broken.

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).
there's not data now, but it's still better than before

**Comment by pat-son** [comment]
Works fine for me
![screen shot 2015-11-13 at 2 00 59 pm](https://cloud.githubusercontent.com/assets/8462638/11155018/d046ff08-8a10-11e5-9d6d-a7850d84892a.png)

**Comment by tylerpuleo** [comment]
Works fine for me as well
