### ISSUE TITLE
Can't re-upload downloaded CSVs from projects with commas in the field names

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2277]
**General description:** The comma in the field name breaks CSV parsing when re-uploading.  This is because the field name gets split once per comma, causing a mismatch in the number of fields and the data points.  I used this data set:
http://isenseproject.org/projects/891/data_sets/8083
The ideal fix would be to escape the commas when exporting.  However, the fact that the site actually crashes when it fails uploading is a problem as well.

**live/dev/localhost:** localhost (probably live and dev as well)
**iSENSE Version:** 7.4
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 15.04 x64
**Browser/Version:** Chrome 46 x64

**Steps to Reproduce:**
* download the data set listed above as a CSV
* create a new project
* template the fields from the data set
* upload the data set
* observe the crash

**Associated Image(s):**

**Comment by pat-son** [comment]
Testers: Create a project that has at least one field name containing a comma. Add some data, and make at least one data point a text entry with a comma in it. Export that data set, make a new project, and try to template fields from that data set. Make sure the data gets uploaded the way it was originally written.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Ubuntu 16.04).
