### ISSUE TITLE
American-format dates uploaded via spreadsheet are misinterpreted when the day of the month is greater than 12.

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#2284]
**General description:** When i upload excel files or google sheet, the files display different dates on iSense than what they display on my original file. The original files' dates are all in 2014; but iSense gives some of the entries dates of Dec 31, 2013. None of my entries on any of the three files I've uploaded have the date Dec 31, 2013.

**live/dev/localhost:** live
**iSENSE Version:** v7.4.1
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Windows
**Browser/Version:** Chrome 46.0.2490.80

**Steps to Reproduce:** I was uploading data files to project #1516. 

281

**Comment by bdonald25** [comment]
I emailed William asking for the spread sheet. I will post it here once I have it.

**Comment by bdonald25** [comment]
"One of the problems is that even when I try to enter the timestamp info the way that I think iSense wants it (say, 2015/10/29) , Excel and google Sheets change the format back to 10/29/2015. 

I have attached the three files I've tried to upload. All three result in dates of Dec 31, 2013 showing up on my iSense visualizations." - William

[2013.xlsx](https://github.com/isenseDev/rSENSE/files/23704/2013.xlsx)
[2014.xlsx](https://github.com/isenseDev/rSENSE/files/23705/2014.xlsx)
[2015.xlsx](https://github.com/isenseDev/rSENSE/files/23706/2015.xlsx)

**Comment by pat-son** [comment]
Looks like it's defaulting some of the values to 12 AM on January 1st, 2014, then some weird timezone stuff happens and 5 hours are subtracted from that date, resulting in 7 PM December 31st 2013

**Comment by pat-son** [comment]
I just found something very weird - if you input dates using William's format, then the resulting dates shown in the vis are different depending on the browser used. Use [this project](http://rsense-dev.cs.uml.edu/projects/2205/data_sets/19207) to test that out. If you peek at the underlying data, the numerical timestamps are different in each browser.

**Comment by pat-son** [comment]
Testers: Upload a spreadsheet with dates in the American format (Month/Day/Year). Make sure that they are interpreted correctly on the vis page (check the Table vis).

**Comment by pat-son** [comment]
PASSED testing on Chrome 52.0.2743.116 (Ubuntu 16.04 LTS).
