### ISSUE TITLE
Error bars are broken

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2285]
**General description:** Error bars are broken

**live/dev/localhost:** live
**iSENSE Version:** v7.4.1
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 46.0.2490.80

**Steps to Reproduce:** 

393

**Comment by asalani93** [comment]
If someone else decides to do this before I do, the problem is that a function signature was changed without testing error bars, and error bars still uses the old signature.

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (Ubuntu 15.04).
