### ISSUE TITLE
Numbers with spaces on manual entry gives error "enter valid number"

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2287]
**General description:** Numbers with spaces on manual entry gives error "enter valid number".

**live/dev/localhost:** live
**iSENSE Version:** v7.4.1
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 46.0.2490.80

**Steps to Reproduce:** 

393

**Comment by pat-son** [comment]
Is a number with a space in it supposed to be a valid number?

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (Ubuntu 15.04).
