### ISSUE TITLE
Scatter plots prints are cut off

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#2290]
**General description:** When printing visualizations of scatter plots it is not printing the whole plot

**live/dev/localhost:** live
**iSENSE Version:** v7.4.1
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Windows
**Browser/Version:** Firefox 41.0

**Steps to Reproduce:** Printing from Free-Fall Pogil

3234

**Comment by bdonald25** [comment]
PASSED testing on Chrome 49.0.2623.87 (linux).
They are no longer cut off but all the visualizations now span two pages high. Is this what we want? 

It is better than 1.1 pages high and part of the width missing.

**Comment by tylerpuleo** [comment]
FAILED testing on Chrome 49.0.2623.87 (linux).

I'm still getting the issue when I try to print something landscape.

http://rsense-dev.cs.uml.edu/projects/106/data_sets/2801

Try printing that vis in landscape.

**Comment by pat-son** [comment]
I didn't consider printing in landscape, but I don't thinks that's an issue that can be easily fixed with the way it's set up right now, but I'll look into it. @bdonald25 Are you getting cut-off prints in portrait?
