### ISSUE TITLE
Canceling printing for a vis breaks the vis.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2291]
**General description:** Canceling printing for a vis breaks the vis.

**live/dev/localhost:** live
**iSENSE Version:** v7.4.1
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 46.0.2490.80

**Steps to Reproduce:** Click Print in the vis tools for any vis. Cancel printing. Watch the vis break.

393

**Comment by bdonald25** [comment]
Testers: Go to a visualization -> try to print it from the tools on the left -> cancel the print -> verify the visualization looks sane and the page is not broken

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).

**Comment by pat-son** [comment]
PASSED testing on Chrome 48.0.2564.116 (OSX 10.10.5).
