### ISSUE TITLE
Little rectangles appear on screen

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2292]
**General description:** little rectangles are appearing in field, media, and other areas of the projects view.

**live/dev/localhost:** live
**iSENSE Version:** v7.4.1
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Chrome 46.0.2490.71

**Steps to Reproduce:** just viewing http://isenseproject.org/projects/1346

3087

**Comment by fgmart** [comment]
![screenshot 2015-11-09 at 5 01 49 pm](https://cloud.githubusercontent.com/assets/1038856/11048113/fef0af76-8703-11e5-927d-53a53177aef7.png)

**Comment by bdonald25** [comment]
Does anyone else get this? I can't reproduce with Chrome or Firefox on either my desktop or laptop.

**Comment by fgmart** [comment]
This problem has gone away with a Chrome update.
