### ISSUE TITLE
additional user prompt when setting up Timeline field

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2293]
Sam and I both just lost 15+ mins ea trying to figure out why a teacher's project wouldn't come up with Timeline, even though she had done everything properly in terms of formatting dates.

The answer was: her CSV did not have any numeric data to display.  (ARGHHHHH!)

Let's please add the following (highlighed in bold, but don't add it in bold) to the help-text below Timeline when setting up fields:

> Data and time values in the form yyyy/mm/dd hh:mm:ss. Limit 1 per project. **Project must have at least one Number field.**

Thanks.

**Comment by bdonald25** [comment]
Testers: Go to a visualization that timeline will be disabled for. Make sure the error message clearly explains why timeline is disabled. 

For timeline to be enabled you need a number field, timestamp, and at least 3 data points.

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).

**Comment by pat-son** [comment]
PASSED testing on Chrome 46.0.2490.80 (Mac OSX 10.10.5).

**Comment by JasonD94** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).
