### ISSUE TITLE
improve error message when Timeline isn't displayed

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2294]
Presently it says this:

> Either a time field was not found or there were not enough data 
> Cannot display Timeline visualization

As a trivially easy improvement, I would like to revise to:

> Either Timestamp field or Number field is missing from project
> Cannot display Timeline visualization

Thanks.

**Comment by bdonald25** [comment]
Testers: When manually adding fields to a project, make sure it is clearly documented what fields you need for timeline to work.

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).
can still get the screen if you don't have data in all three data points

**Comment by pat-son** [comment]
PASSED testing on Chrome 46.0.2490.80 (Mac OSX 10.10.5).

**Comment by JasonD94** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).
