### ISSUE TITLE
Visualizations tell you the wrong number of data sets that you are viewing.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2304]
**General description:** Visualizations tell you the wrong number of data sets that you are viewing.

**live/dev/localhost:** live
**iSENSE Version:** v7.4.1
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 46.0.2490.80

**Steps to Reproduce:** On a vis.

393

**Comment by bdonald25** [comment]
Testers: Go to a project with a lot of data sets. Check off 3 of them and visualize. Make sure it says "Showing 3 data sets".

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).

**Comment by pat-son** [comment]
PASSED testing on Chrome 46.0.2490.80 (Mac OSX 10.10.5).

**Comment by JasonD94** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).
