### ISSUE TITLE
Material Design Continued

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#2305]
Further material design changes. EDIT THIS WHEN YOU FIND A CHANGE
- [x]  Vis title headers should be centered along the y-axis
- [ ]  Edit project title save button
- [ ] "Set up fields manually" page is not material buttons
- [x] Google spreadsheets modal

**Comment by tylerpuleo** [comment]
"Set up fields manually page" not material buttons

**Comment by asalani93** [comment]
FAILED testing on Chrome 45.0.2454.101 (Ubuntu 15.04).
was not addressed
merge anyway
