### ISSUE TITLE
Project / Vis Index page UI tweak

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#2309]
**General description:** Change the number of projects displayed on the Projects/Visualizations pages to a multiple of 12.

This will guarantee that if there are more entries than the cut off, the scree doesn't awkward cut stop half way through the row. The reason you need a multiple of 12 is that you need to ensure that the page will look good with 4, 3, 2 or 1 tiles on it (because of Bootstraps grid system).
My recommendation is 48, but 36 or 60 are other options to be considered.

**live/dev/localhost:** live
**iSENSE Version:** 7
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Windows :goat: 
**Browser/Version:** Firefox 42.0 :+1: 

**Steps to Reproduce:** On the Projects/Vis Index pages, with a wide screen, scroll to the bottom and notice that the last row is incomplete.

9

**Comment by jdalphon** [comment]
This is also a problem when you log in and it adds a tile for the create
project. Creates an off by 1

On Fri, Nov 13, 2015 at 4:06 PM, Jeremy Poulin <notifications@github.com>
wrote:

> *General description:* Change the number of projects displayed on the
> Projects/Visualizations pages to a multiple of 12.
>
> This will guarantee that if there are more entries than the cut off, the
> scree doesn't awkward cut stop half way through the row. The reason you
> need a multiple of 12 is that you need to ensure that the page will look
> good with 4, 3, 2 or 1 tiles on it (because of Bootstraps grid system).
> My recommendation is 48, but 36 or 60 are other options to be considers.
>
> *live/dev/localhost:* live
> *iSENSE Version:* 7
> *Logged in (Y or N):* Y
> *Admin (Y or N):* N
>
> *OS:* Windows
> *Browser/Version:* Firefox 42.0
>
> *Steps to Reproduce:* On the Projects/Vis Index pages, with a wide
> screen, scroll to the bottom and notice that the last row is incomplete.
>
> 9
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isenseDev/rSENSE/issues/2309>.
>



-- 
--------------------------------
James Dalphond
UML Computer Science
Engaging Computing Group

**Comment by jaypoulz** [comment]
@jdalphon :+1: Let's make sure we catch that edge case.

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (Ubuntu 15.04).

**Comment by bdonald25** [comment]
I updated the cards on the index pages to look nicer. I also partially fixed this bug. (I did not address the extra box when logged in) I will fix this last issue if we do not go with the fab button for creating projects at the bottom right of the screen.

**Comment by pat-son** [comment]
Testers: Make sure the new button behaves nice on different browsers.

**Comment by tylerpuleo** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10082140-141443373_3-s4-v1.png?transparent=1&width=246)

**Comment by tylerpuleo** [comment]
Github has bitmoji support!!!

**Comment by pat-son** [comment]
I think it just uploads it as an image

**Comment by tylerpuleo** [comment]
![image](https://cloud.githubusercontent.com/assets/7584536/17226481/b75c81c4-54d7-11e6-80e8-7e8e5c5d48f5.png)

But I have the little bitmoji thing

**Comment by pat-son** [comment]
I stand corrected

**Comment by pat-son** [comment]
PASSED testing on Chrome 52.0.2743.116 (Ubuntu 16.04 LTS).
