### ISSUE TITLE
creating fields and importing data set at the same time seems to not work

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2310]
Try this:

1. make new project
2. upload the attached data set
2a. keep the box checked to import the data
3. the project will be created, and a data set will be created, but the data set will be empty.

File at https://drive.google.com/file/d/0B41atXlV0KHKRkVYVGpBYnp4R3c/view

**Comment by pat-son** [comment]
This bug already has an [issue page](https://github.com/isenseDev/rSENSE/issues/2271).

**Comment by bdonald25** [comment]
Closing duplicate issue.
