### ISSUE TITLE
Heatmap has no scale/legend

### ISSUE THREAD

**Issue by smichalka** [isenseDev/rSENSE#2316]
The heatmap function has no scale bar to indicate the values tied to each color.  For example, does red mean 1 m/s^2 or .237 m/s^2?  A student is looking to do a project looking at light pollution, but a map without an actual heatmap scale would not be acceptable for their project. 

![image](https://cloud.githubusercontent.com/assets/5709961/11336696/707977b6-91b5-11e5-9d19-32680970e9b3.png)

**Comment by tylerpuleo** [comment]
I looked into this feature and unfortunately we are not able to create this feature. We do not have access to what the colors represent. We pass Google a relatively weighted set of data points and they do the rest.
