### ISSUE TITLE
Can delete fields in a project with data

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2319]
**General description:**
Deleting fields is only validated on the client side.  If the user manages to find a way to click the X button to remove the field from the page, the field will delete regardless of whether or not the field has data.  This has no terrible side effects, aside from the goofiness that is an data set with data but no fields.  Also, vis still works but lacks any data aside from row count to visualize.

**live/dev/localhost:** live/dev
**iSENSE Version:** 7.5
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 15.04 x64
**Browser/Version:** Chrome 45 x64

**Steps to Reproduce:**
* Create a project with some fields
* Create a data set that has at least a couple of rows of data
* Re-open the field creation window
* Open the debug tools to remove the class '.not-active' from the X button
* Click the X button to remove the row
* Do this for all of the fields
* Click save

**Associated Image(s):**
![hey everybody its tim - google chrome_002](https://cloud.githubusercontent.com/assets/7584534/11375385/0855737a-92a9-11e5-99bd-3636f1a01294.png)
![editing a data set - google chrome_003](https://cloud.githubusercontent.com/assets/7584534/11375409/3b2c2640-92a9-11e5-8178-c05faa2666a9.png)

**Comment by pat-son** [comment]
Testers: Follow the steps above to try to replicate the bug. Make sure it's fixed.

**Comment by pat-son** [comment]
PASSED testing on Chrome 51.0.2704.103 (Windows 10).
