### ISSUE TITLE
If you go to the edit fields page for a project you don't own, you get a blank page.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2320]
**General description:** If you go to the edit fields page for a project you don't own, you get a blank page. 

Go to http://isenseproject.org/projects/716/edit_fields while signed in as a user other than "mobile u"

**live/dev/localhost:** live
**iSENSE Version:** 7
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Windows
**Browser/Version:** Chrome 46.0.2490.86

**Steps to Reproduce:** 

10

**Comment by pat-son** [comment]
Testers: Go to a project you don't own and view the edit_fields page. Check out the new message that appears.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Ubuntu 16.04).
