### ISSUE TITLE
Can't select groups of data sets using the contributor key

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2321]
**General description:** You can't select groups of data sets using the contributor key. When you pull down the menu, the possible contributor keys do appear, but choosing one of them does not cause the corresponding data sets to be selected.

**live/dev/localhost:** live
**iSENSE Version:** 7
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Chrome 46.0.2490.71

**Steps to Reproduce:** http://isenseproject.org/projects/1346

12

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (Ubuntu 15.04).
