### ISSUE TITLE
On scatter, tooltip reveals data of point obscured by point above it

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2322]
**General description:** On scatter, if two points have the same x and y value and thus overlap, the color of the upper point is displayed, but the pop-up tooltip displays the values for the lower data point.

**live/dev/localhost:** live
**iSENSE Version:** 7
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Chrome 46.0.2490.71

**Steps to Reproduce:** At http://isenseproject.org/projects/1717/data_sets, turn on Detailed Tooltips. Then hover over the data point X=3, Y=100. This point displays as orange, indicating there is a entry for (3,100) in group "none". But the tooltip shows 3,100,light. 

There is such a datapoint. But the tooltip should reveal info about the one drawn on top, which is 3,100,none.

12

**Comment by pat-son** [comment]
Testers: Make sure the above bug cannot be replicated. Also make sure that the tooltips don't act up.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Ubuntu 16.04).
