### ISSUE TITLE
Must double click to return focus to previously active cell after clicking outside the manualEntry table

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2323]
**General description:** If the cursor is in the Data Set Name field, in order to gain focus on a constrained text field, you must double-click.

If the cursor is in an existing numeric field, then only a single click is required for the text field's pulldown menu to appear.

The need for double-click should be removed. No one expects this and it feels broken.

**live/dev/localhost:** live
**iSENSE Version:** 7
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Chrome 46.0.2490.71

**Steps to Reproduce:** Test at http://isenseproject.org/projects/1717/manualEntry .

Click into the Data Set Name field and type something.
Then single-click in the middle column "Exercise."
Nothing happens.

12

**Comment by bdonald25** [comment]
It doesnt appear to be caused by the text pulldown. 

It appears that switching focus from the dataset title to the manual entry table sometimes requires a double click. This appears to be random. Sometimes it will require a double click, other times it will not require a double click for the same cell.

**Comment by tylerpuleo** [comment]
I also noticed that sometimes going from the edit title box to the table will require a double click and sometimes only a single click. However, If you click free white space outside of the table then click the table you always need a double click.

**Comment by pat-son** [comment]
Here's exactly how to reproduce it: If your focus is in a table cell and you click anywhere outside the table, it will require a double click to bring focus back to that cell, but only a single click for any other cell.

**Comment by pat-son** [comment]
Testers: Make sure that you cannot reproduce the above bug, and make sure that the manual entry page still works/uploads data.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Ubuntu 16.04).
