### ISSUE TITLE
Display Markers box on Map vis should be checked when map first opens

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2326]
**General description:** Go to this project and click on map: http://isenseproject.org/projects/1612

The map markers appear, but the "Display Markers" box is not checked.

It should be.

**live/dev/localhost:** live
**iSENSE Version:** v7.6.0
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 47.0.2526.73

**Steps to Reproduce:** See above

12

**Comment by bdonald25** [comment]
Testers: Go to a map vis. If the map markers appear, the "Display Markers" box should be checked.

**Comment by pat-son** [comment]
PASSED testing on Firefox 44.0.2 (Mac OSX Yosemite 10.10.5).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by JasonD94** [comment]
PASSED testing on Chrome 48.0.2564.97 (Linux Ubuntu 14.04 LTS).
