### ISSUE TITLE
Heat map radius crashes browser

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#2334]
General description: If you add some zeros to the largest heat map radius it crashes the browser. Should probably limit radius.

live/dev/localhost: live
iSENSE Version: 7.6.0
Logged in (Y or N): Y
Admin (Y or N): N

OS: Ubuntu 14.04
Browser/Version: Chrome 46.0.2490.71

Steps to Reproduce: Add a few zeros to the heat map radius. About 10 zeros should be enough. Then hit enter and watch your browser die.

**Comment by bdonald25** [comment]
Testers: Try and crash a heat map on the map visualization by entering a large number for the radius.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).

**Comment by pat-son** [comment]
PASSED testing on Chrome 48.0.2564.116 (OSX 10.10.5).
