### ISSUE TITLE
 Pre-populate data set name with username + timestamp.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2338]
**General description:** Pre-populate data set name with username + timestamp.

**live/dev/localhost:** live
**iSENSE Version:** v7.6.0
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 48.0.2564.82

**Steps to Reproduce:** 

393

**Comment by bdonald25** [comment]
Testers: Create a new data set, then make sure the name of the data set is pre-populated with your username and a timestamp. Test this again with a contributor key and make sure it is pre-populated with the contributor name and a timestamp.

**Comment by pat-son** [comment]
PASSED testing on Firefox 44.0.2 (Mac OSX Yosemite 10.10.5).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by JasonD94** [comment]
PASSED testing on Chrome 48.0.2564.97 (Linux Ubuntu 14.04 LTS).
