### ISSUE TITLE
Filter out specific data points

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#2343]
**General description:** Can no longer export data; cannot delete outlying points when attempting to visualize and draw lines of best fit.

**live/dev/localhost:** live
**iSENSE Version:** v7.6.0
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Windows
**Browser/Version:** Chrome 47.0.2526.111

**Steps to Reproduce:** Attempting to do line of best fit x=tibia, y=fibula on Bone Lab for Teachers.  Five outliers are destroying the line of best fit and I cannot get rid of them.  

66

**Comment by pat-son** [comment]
Testers: Try out the new feature. Disable points, re-enable them, make sure nothing is broken.

**Comment by pat-son** [comment]
PASSED testing on Chrome 51.0.2704.103 (Windows 10).
