### ISSUE TITLE
Items in Table search drop-down menu get highlighted twice

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2349]
General description: When highlighting a menu item, we don't need to add the "ui-state-hover" class to the text, because the box itself is already highlighted. See image.

live/dev/localhost: live
iSENSE Version: v7.7.0
Logged in (Y or N): Y
Admin (Y or N): N

OS: Ubuntu
Browser/Version: Chrome

Steps to Reproduce: Hover over a dropdown item on the table vis, and watch as it is highlighted twice.

![dropdown_bug](https://cloud.githubusercontent.com/assets/8462638/13265344/6f962078-da40-11e5-9071-3761f4e06d55.png)

**Comment by bdonald25** [comment]
Testers: Make sure the items in the drop-down menu shown in the image above no longer double highlight. The drop-down menu is located on the table visualization.

**Comment by tylerpuleo** [comment]
PASSED

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).

**Comment by pat-son** [comment]
PASSED testing on Chrome 48.0.2564.116 (OSX 10.10.5).
