### ISSUE TITLE
The row that is selected in the table is a terrible color.

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2358]
**General description:** The row that is selected in the table is a terrible color. I am not sure what color it should be. 

You can reproduce this by clicking on a cell in the table visualization.

![table](https://cloud.githubusercontent.com/assets/4121924/13446529/55a910c4-dfe2-11e5-83ed-bd7106d0c7ee.png)

**live/dev/localhost:** live
**iSENSE Version:** v7.7.0
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 48.0.2564.116

**Steps to Reproduce:** Table Vis.

393

**Comment by bdonald25** [comment]
PASSED testing on Chrome 49.0.2623.87 (linux).

**Comment by tylerpuleo** [comment]
PASSED Chrome (mint)

**Comment by pat-son** [comment]
PASSED testing on Chrome 49.0.2623.87 (OSX 10.11.3).
I'm not really sure about the blue border, but it's better than before.
