### ISSUE TITLE
Zoom on scatter plot causes page to crash

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2364]
**General description:** Zooming in too far causes the page to crash.

**live/dev/localhost:** live
**iSENSE Version:** 7.7.1
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu
**Browser/Version:** Chrome 46.0.2490.71

**Steps to Reproduce:** Go to any scatter plot.  Click-and-drag a square to zoom on the plot.  Repeat until webpage crashes (shouldn't take too long).

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Windows 10).
