### ISSUE TITLE
Filtering by timestamp on table is done in unix timestamp

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#2365]
General description: When filtering by a timestamp it is done in unix timestamp

![selection_010](https://cloud.githubusercontent.com/assets/7584536/13616023/13231132-e546-11e5-8d54-e1da81cb00bf.png)

live/dev/localhost: live
iSENSE Version: v7.7.0
Logged in (Y or N): N/A
Admin (Y or N): N/A

OS: mint
Browser/Version: Chrome

Steps to Reproduce: Go to timeline. Turn filters on and click set current filters. Notice that the filter is created in unix timestamp.

**Comment by bdonald25** [comment]
PASSED testing on Chrome 49.0.2623.87 (linux).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 49.0.2623.87 (linux).

**Comment by pat-son** [comment]
PASSED testing on Chrome 49.0.2623.87 (OSX 10.11.3).
