### ISSUE TITLE
Vis issue with identically named fields

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2368]
**General description:** If you have two fields in a vis with the exact same name, certain parts of vis behave strangely.  For example, in the table vis, hiding one of the fields will hide the other one as well.

**live/dev/localhost:** live/dev/localhost
**iSENSE Version:** current
**Logged in (Y or N):** doesn't matter
**Admin (Y or N):** there should be an option on these for "is irrelevant to the issue"

**OS:** laptop
**Browser/Version:** internet

**Steps to Reproduce:**
* Create a new project. Give it a good, not garbage name.
* Create some fields.  Make sure one of the fields has the name "Data Point (id)". Make another field named literally anything other than "Data Point (id)".  These can be literally any type you want.  Don't get too hung up on this step, there's more important stuff coming later.
* Enter some data so we can actually visualize stuff.  Doesn't matter what the data is.  Just type things.
* Go to the table visualization.  Observe how checking and unchecking the first of the two "Data Point (id)" fields does absolutely nothing.  Observe how checking and unchecking the second of the two "Data Point (id)" fields toggles both of them.  This is an issue.

**Associated Image(s):**
:100:

**Comment by pat-son** [comment]
Testers: Make sure that you cannot name fields any of the following names:
'Data Point', 'Data Set Name (id)', 'Combined Data Sets', 'Number Fields', 'Contributors', and 'Time Period'.

**Comment by pat-son** [comment]
PASSED testing on Chrome 51.0.2704.103 (Windows 10).
