### ISSUE TITLE
Settable axes for timeline

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2371]
**General description:** Settable axises for timeline
**live/dev/localhost:** live
**iSENSE Version:** 7.7.2
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 49.0.2623.87

**Steps to Reproduce:** 

393

**Comment by VictoriaAlbanese** [comment]
@asalani93 Hey Anthony!  Would you be able to give me a few tips about how to use your custom datetime picker? I've been looking at how it is used in the manual entry for timestamp data (can't seem to find it anywhere else) but I could use some help as to how to apply it to other places.

**Comment by doug-salvati** [comment]
Testers: make sure selecting dates (Press Enter!) changes bounds.

Make sure an error message is raised if the first date is earlier than the other

**Comment by doug-salvati** [comment]
PASSED testing on Safari 11.0 (mac).
Great work getting bounds to work.  Date picker UI is still annoying to me(e.g. shifts the date values everytime you click), but that's unrelated......

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 61.0.3163.100 (mac).
