### ISSUE TITLE
map zoom when there is one data point should be set to 200 km

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2373]
it's been a long term annoyance that when maps shows a single data point, it defaults to fully zoomed-in, and the user has no perspective on where the point is.

i request that the default zoom when there is only one data point be set to 200 km.

e.g., when you have a bogus data point of 0,0, you would be able to see that you're off in the ocean of Africa.

![2016-04-07](https://cloud.githubusercontent.com/assets/1038856/14355760/2d94f374-fcb0-11e5-9de3-335b8f8ea28d.png)

**Comment by bdonald25** [comment]
Testers: Create a map vis that just shows one point and make sure that it is not zoomed in too far.

**Comment by VictoriaAlbanese** [comment]
This worked just fine for me
-Passed

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).

**Comment by doug-salvati** [comment]
PASSED on Chrome Mac OSX

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.86 (OSX 10.11.3).
Works like a charm.
