### ISSUE TITLE
lots of data sets => long url => Apache forbidden message

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2376]
- [x] PART 1

**General description:** If you try to visualize a lot of data sets at one the server gives you a forbidden message.
For example with the Plinko project http://isenseproject.org/projects/2156, there are over 1000 data sets so the url would end up something like http://isenseproject.org/projects/2156/datasets/1,2,3,4,5,6,7,8,9.....1000 and because the url is so long the apache server just returns forbidden before the request even makes it to the rails server.

We could have it go to http://isenseproject.org/projects/2156/data_sets when all the data sets are selected which  shows all the data sets for the project, but if a single one is not selected then the problem will come up again.

**live/dev/localhost:** live
**iSENSE Version:** 7.7.2
**Logged in (Y or N):** N
**Admin (Y or N):** N/A

**OS:** Windows
**Browser/Version:** Chrome 49.0.2623.110

**Steps to Reproduce:** http://isenseproject.org/projects/2156 and clicked visualize with all the data sets selected.

- [x] PART 2
General description: When attempting to export data from a project, if there is a large number of data sets (around 700+), then the file(s) will not download, and an HTTP error appears (403/414). Some example projects for which this occurs:

http://isenseproject.org/projects/866
http://isenseproject.org/projects/1264
http://isenseproject.org/projects/864
A helpful link: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error

live/dev/localhost: live
iSENSE Version: v8.2.5
Logged in (Y or N): Y/N
Admin (Y or N): N

OS: Ubuntu 16.04
Browser: Google Chrome, Firefox

**Comment by pat-son** [comment]
Testers: Check that the URL for visualizing has no data sets appended when all the data sets are selected. Once it's pushed to live, also check that the Plinko project works when all data sets are selected.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Ubuntu 16.04).

**Comment by pat-son** [comment]
Hotfix is applied, but leaving the issue open until the permanent solution is found.

**Comment by pat-son** [comment]
One possible permanent solution is as such:
Say the user wants to visualize 1000 data sets, so they would usually go to the page isenseproject.org/projects/100/data_sets/1,2,3...1000. But instead, when the website recognizes that the user is trying to visualize so many data sets, it would create a new field in the project that maps lists of data sets to short unique strings. So the list 1,2,3,...1000 could map to the string "ax3gh" and then the user would visit isenseproject.org/projects/100/data_sets/ax3gh

**Comment by doug-salvati** [comment]
Best solution would be to not put these IDs in the URL at all, and use a POST request instead of GET.

Navigating directly to /data_sets/ should still show all data sets.

This should also be the case with #2583.  They should both be fixed together.

**Comment by doug-salvati** [comment]
Good point, that's exactly what we have visualizations are for so I think it's not a huge issue

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 60.0.3112.113 (mac).

**Comment by mck529** [comment]
PASSED testing on Chrome 61.0.3163.79 (windows).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 60.0.3112.113 (Windows 10).

**Comment by mdibello** [comment]
PASSED testing on Chrome 55.0.2883.87 (linux).
