### ISSUE TITLE
Cant "Report a Bug"

### ISSUE THREAD

**Issue by jdalphon** [isenseDev/rSENSE#2387]
I can not report a bug from the report a bug page. I hope the irony is not lost here. 

To reproduce, log in to iSENSE with google. 
Click on "Report a Bug"

Select either option. 

Get the message "You are already logged in." See image

<img width="1169" alt="screen shot 2016-05-13 at 2 55 20 pm" src="https://cloud.githubusercontent.com/assets/1268772/15258665/ddc56220-191a-11e6-9c71-2f6036b48993.png">

Tested:
Chrome 50.0 on OSX 10.11.4

**Comment by bdonald25** [comment]
@pat-son I might fix this out of the kindness of my heart because I feel bad you are the only one there all summer.

**Comment by pat-son** [comment]
@bdonald25 I would appreciate that greatly.

**Comment by pat-son** [comment]
Testers: This fix is already live, but doesn't work correctly on the dev server due to the way that Devise works. Go to live and verify that it works there.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Windows 10).
