### ISSUE TITLE
"Edit" links should not appear next to data sets you do not own

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2393]
It seems that now all data sets not created with contributor keys are displaying an "edit" link next to them.

This is true whether you're logged in (and don't own them) or not even logged in.

This should be fixed.

See screenshots below. First is logged into a project that's not mine; second shows logged out view, indicating that data sets uploaded with contributor key don't have this problem.

![loggedin](https://cloud.githubusercontent.com/assets/1038856/15333732/f48cac5e-1c38-11e6-9909-ed951602b76c.png)

![loggedout](https://cloud.githubusercontent.com/assets/1038856/15333737/f90e5052-1c38-11e6-8a88-08c2a868c518.png)

**Comment by pat-son** [comment]
Testers: This fix is already live, but just double check that you cannot edit other users' exisiting datasets, both logged in and logged out.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Windows 10).
