### ISSUE TITLE
new viz that combines histogram and bar (Histogram Density)

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2399]
I was watching the kids try to answer questions using bar graph at the Boathouse today, and it struck me how profoundly bar graph collapses a whole set of data into a single value.

It would sort of be better if the bar were a single point. But because it's a bar, it's visually imposing -- a big rectangle of color -- and you don't realize what's behind the scenes.

We were switching among different settings for the bar -- e.g. mean, median, min -- and the kids' attention was wandering.

Then I imagined, what if the bar were superimposed over a point-cloud of the underlying data themselves. 

The bar itself would be drawn over the points, so you'd really see what it was representing. It should look like this:

![vertical-histogram-bar_1](https://cloud.githubusercontent.com/assets/1038856/15364839/029fd146-1cec-11e6-8691-2f2268ee648e.jpg)

Some other details:

* the view should auto-scale to always include all of the points being displayed. This way, when you switch between different bar settings (mean, median, min, max), the view would _not_ resize.

* I'm imagining the points themselves being drawn with a solid square outline and a partially-transparent color fill. As more and more points stack on top of each other, the fill would appear darker.

Comments?

**Comment by fgmart** [comment]
This page shows a closely related idea, implemented in R: http://rgraphgallery.blogspot.com/2013/04/rg81-plotting-scatter-plot-with-means.html?m=1

**Comment by pat-son** [comment]
Testers: Poke and prod the histogram density feature (under Bar) any way you can. Make sure that it doesn't break any existing features.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Windows 10).
