### ISSUE TITLE
automatic data set name should include seconds

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2404]
otherwise if you try to contribute data sets quickly you get the duplicate name error.

**Comment by farxinu** [comment]
For argument's sake...do we really want to enable spam data uploading? This is a built-in 60 second delay between dataset uploads.

**Comment by pat-son** [comment]
I don't see an issue with including the seconds. It doesn't protect against spam, either, because someone could just take 2 seconds to change the title themselves.

**Comment by pat-son** [comment]
Testers: Make sure that the default dataset name includes seconds.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Windows 10).
