### ISSUE TITLE
Several vises break when adding a new field to an existing project or reordering fields

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2405]
Check out this project:

http://isenseproject.org/projects/2358/data_sets

It's a "favorite cola" survey project. Fields are Favorite (must be Coke or Pepsi) and then a FF named Votes.

The value of the Votes field is an FF set to be simply "1".

This shows up properly in table:

![screen shot 2016-05-20 at 10 58 15 am](https://cloud.githubusercontent.com/assets/1038856/15431883/c6a01784-1e79-11e6-9a92-ccf4b70c6b64.png)

But, pretty much no other viz seems to know the Votes field exists.

Sometimes Votes shows up in the Y axis, but nothing graphs right.

We were hoping for Pie chart to work -- basically, to automatically populate each row with one vote.

**Comment by pat-son** [comment]
FF work fine on this vis: https://isenseproject.org/projects/2359/data_sets/20165
Although I'm seeing a different issue here. When you first load the page, the default vis is Pie but nothing shows up, and the "Group By" selection is empty:
![image](https://cloud.githubusercontent.com/assets/8462638/15433423/4e3d77a8-1e80-11e6-99ca-4cb40da10703.png)
Sometimes I can get something to show up by changing the "Group By" option and going to the Scatter vis, setting the x- and y-axes to different values, then going back tp Pie:
![image](https://cloud.githubusercontent.com/assets/8462638/15433526/b4c6568e-1e80-11e6-81d9-a799bd8218df.png)
So yeah, something is definitely broken.

**Comment by pat-son** [comment]
Actually, I have no idea what happened. I just recreated your project from scratch, and it works fine: http://isenseproject.org/projects/2361/data_sets/20174,20173,20172,20171,20170

**Comment by fgmart** [comment]
I took a convoluted path to creating my project. It has a normal field named "Votes" (as well as one named "Count") before I deleted them both and then created the FF named Votes.

So maybe it's worth looking into the underlying project data structures and seeing if they're munged somehow in my project.

In which case, it might not be FF's fault that stuff isn't working. The project could be corrupted in a subtle way.

**Comment by pat-son** [comment]
That's what I was thinking. I would just try recreating the project.

**Comment by fgmart** [comment]
Let's leave this issue open until someone has a chance to dig into it.

**Comment by bdonald25** [comment]
@fgmart I got yours working (http://isenseproject.org/projects/2358/data_sets) by going to bar graph, setting the groups to "Data Set Name", enabling votes under Y Axis, and setting the sort by option under tools to "Group Name". 

Once I did those three things all the other graphs started working. I did not look into it further but hopefully that gives you guys a start.

**Comment by bdonald25** [comment]
If you do those things and then make a default vis then it should save all the settings and no longer be in a broken state. The question is how did it get in that state to begin with?

**Comment by pat-son** [comment]
I think we nailed down why this was happening: The Pie chart, and maybe other vises, seem to break when you add a new field to a project with existing data. Here's how you can replicate it:

1. Create a project
2. Add a number field and a text field
3. Manually enter a dataset
4. Add a new text field
5. Manually enter another dataset
6. View Vis

Notice how now the pie chart wants to count up the text fields instead of the number fields. This may be some sort of off-by-one error.

**Comment by pat-son** [comment]
I figured out why it was happening: When you add a new field on the Edit Fields page, it inserts it into the top of the list there. It actually gets saved to the database in that order, too. The vis, however, isn't made aware of this change. So what it thought was field number 7 in the list of fields is actually now field number 8. You can even incur this bug without even adding a new field by simply reordering the existing fields.

There are several ways we can fix this bug, each with their pros and cons. @fgmart we should discuss it in person on Monday.

**Comment by pat-son** [comment]
Testers: Create a project with several different fields and give it some data. Visualize and set some defaults. Then try adding new fields or reordering the existing ones. Make sure that your defaults don't change.

**Comment by pat-son** [comment]
FAILED testing on Chrome 50.0.2661.102 (Ubuntu 16.04).
Works for the most part, but bar chart's default sort by needs to be fixed too.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Ubuntu 16.04).
Everything is right as rain
