### ISSUE TITLE
Several issues involving filtering with Strings

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2410]
**General description:** When you filter a text field and click "Set Current Filters", the box that shows up at the top shows "[fieldName] contains NaN". It still filters correctly; it's just a UI bug.
In addition, when applying a filter for a date by string in the Table vis (for example, show only March data by using "contains Mar"), this causes the filter label to read "[time field] contains Invalid Date". This causes no data to show, so it is a slightly different bug than the above. The weird thing is that the table will filter everything okay before you apply filters, but after applying everything breaks.

Before: Note that only timestamps containing "Mar" are shown.
![image](https://cloud.githubusercontent.com/assets/8462638/15585460/60fba2a8-234d-11e6-8a0a-457080bc4c46.png)

After:
![image](https://cloud.githubusercontent.com/assets/8462638/15585206/496742ec-234c-11e6-9f9a-bd5a2162232d.png)

This probably has something to do with the fact that the table is filtering based on strings, but once you try to apply the filters, our website interprets that as a unix timestamp. If you type a number into the Date filter box (in this case, the current date in Unix milliseconds:
![image](https://cloud.githubusercontent.com/assets/8462638/15585353/d8bb9196-234c-11e6-86e1-0e4b9de0e688.png)
This is the filter that is applied:
![image](https://cloud.githubusercontent.com/assets/8462638/15585383/f18d6b7c-234c-11e6-9ff8-c46cdd06e25d.png)
Obviously not the desired behavior, because no datapoint is going to contain that exact timestamp, and there's no way to do "greater than/less than" with dates on the table, because they're supposed to be interpretted as strings. This will require a slight rework of the filtering system.

**live/dev/localhost:** Any
**iSENSE Version:** 8.0.2
**Logged in (Y or N):** Either
**Admin (Y or N):** N

**OS:** Any
**Browser/Version:** Any

**Steps to Reproduce:** Go to the table vis on a project with a timestamp field and a text field. Try to apply filters for each separately, and observe how they break in different ways.
- [x] String Filtering [NaN]
- [x] Filtering date strings

**Comment by pat-son** [comment]
Testers: Go to the table vis. Search a text column for a valid string. Apply filters. Make sure that the new message doesn't say "[NaN]"

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Ubuntu 16.04).

**Comment by pat-son** [comment]
Not closing until the other issue (table filtering dates) is dealt with.

**Comment by doug-salvati** [comment]
Testers: Do some filtering by date.  These are hybrid filters; they can be treated as strings or exact times. 
 Make sure that when you use table it is treated like a string (i.e. "contains 'Janua'" rather than "contains 124887298370" or "contains 25 Jan 2017 10:00:00 AM...".

When you apply filters on timeline, the EXACT dates (i.e. "timestamp > 25 Jan 2017 10:00:00 AM...") should show up.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 59.0.3071.115 (mac).
