### ISSUE TITLE
Need "delete selected" datasets button

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2431]
Presently data sets can only be deleted one at a time.

Now that we have AppVis publishing large numbers of data sets to a project, it would be handy to have a way to bulk-delete them.

I suggest a button "Delete" that would go in the row of the Visualize and Export buttons.

Maybe right-justify it (immediately to the left of the dataset-selection-pulldown), and it should definitely be in red, so it's visually separated from the ones you'd more typically use.

Probably it should have a confirmation dialog. "Are you sure? ### data sets will be deleted. &lt;Delete&gt; &lt;Don't Delete&gt;"

**Comment by pat-son** [comment]
@fgmart Do you want me to add this in addition to the current "Delete" Buttons for each dataset, or have the new Delete button be the only way to delete the dataset?

**Comment by pat-son** [comment]
Also, how should the website handle a situation when the user has selected some datasets that he does not own, in addition to some that he does? Should the Delete Selected button go ahead and delete the ones that he does own and give a message that some were not deleted, or just abort the deleting altogether?

**Comment by pat-son** [comment]
Testers: Poke and prod at this new feature. Try deleting different amounts of data sets, different patterns of selection, etc.

**Comment by pat-son** [comment]
PASSED testing on Chrome 51.0.2704.103 (Windows 10).
