### ISSUE TITLE
minor edits to Contributor Key details on Edit Project page

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2453]
1. Please move the block to the top of the page.

2. Reword the chunk of text to:

>Create a contributor key to allow anyone to add data to your project. The key is like a per-project password. The associated label will appear next to data sets contributed with the matching key. Contributor keys are not case-sensitive; e.g., ``Glucose10`` and ``glucose10`` are the same.  Contributor keys also allow users to contribute to locked projects. To fully lock a project, set it to locked and delete all contributor keys.

**Comment by pat-son** [comment]
Testers: Make sure the "Edit" page still works.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Ubuntu 16.04).
