### ISSUE TITLE
Manual Entry box is much too tall

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2477]
**General description:** When on the manual entry page, the container holding the slickgrid rows is much taller than necessary, pushing information to the bottom of the screen. See the attached image.

**live/dev/localhost:** Any
**iSENSE Version:** 8.2.1
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Windows 10
**Browser/Version:** Chrome, Firefox

**Steps to Reproduce:** Go to the manual entry page for a project

**Associated Image(s):**
![image](https://cloud.githubusercontent.com/assets/8462638/17448036/04a73066-5b20-11e6-8098-708082f28970.png)

**Comment by pat-son** [comment]
Testers: Play with the manual entry box. Add rows, delete them, submit some.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 53.0.2785.143 (OSX 10.11.6).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (linux).
It is smaller now.

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).
