### ISSUE TITLE
X-Axis labels on Bar vis are incorrectly assigned

### ISSUE THREAD

**Issue by farxinu** [isenseDev/rSENSE#2478]
Seen in: http://isenseproject.org/projects/2551

So if you go to bar chart and select all the language values (Arabic through Vietnamese), hovering over the bar value gives the right thing (the largest bar should be English). But, the x-axis claims that this largest bar is actually Italian. 

![image](https://cloud.githubusercontent.com/assets/3612714/17785261/114e23fa-654e-11e6-93f2-f88f27b9f633.png)

**Comment by pat-son** [comment]
Seems to be caused by having too many x-axis labels. Even after deselecting some of the labels, the off-by-one error persists.

**Comment by pat-son** [comment]
I figured it out; it has to do with the order that you select the fields in. The bars are placed in the correct positions, but the x-axis labels are always placed at the right-most position.

**Comment by pat-son** [comment]
Testers: Go to a project with multiple fields. Select the fields in a random order and make sure that the bars match up with the labels underneath.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 53.0.2785.143 (OSX 10.11.6).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).
