### ISSUE TITLE
Create Project FAB is too large on mobile

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2481]
Should be a one-line fix.

**Comment by pat-son** [comment]
Testers: Open the page in mobile view (Ctrl-Shift-I > Ctrl-Shift-M) and make sure the FAB is an okay size in the projects index page.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 53.0.2785.143 (OSX 10.11.6).
Tested on actual mobile device.

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (linux).
FAB appears smaller on mobile view.

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).
