### ISSUE TITLE
Regression lines are missing tooltips

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2482]
Regressions used to have tooltips that showed the equation and r-squared. They went missing at some point over the summer.

**Comment by pat-son** [comment]
Checking out past releases shows that the tooltips stopped working in v8.2. Will investigate further.

**Comment by pat-son** [comment]
Testers: Make sure the tooltips are back for different regressions. Try different settings on the chart, too.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 53.0.2785.143 (OSX 10.11.6).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (linux).
Missing tool-tips were restored

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).
