### ISSUE TITLE
"Create a Project" modal should auto-focus the text field

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2484]
Self-explanatory. Would just be much more convenient than having to click into the text field.

**Comment by pat-son** [comment]
Testers: Click the Create Project FAB and make sure that the text field is automatically focused for input.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 53.0.2785.143 (OSX 10.11.6).

**Comment by mck529** [comment]
FAILED testing on Chrome 53.0.2785.101 (linux).
Works the first time, but if you close the pop up window and try to do it again, it will not focus the second time.

**Comment by pat-son** [comment]
@mck529 Close enough, not gonna worry about such a small edge case.

**Comment by mck529** [comment]
@pat-son Yeah that's what I figured too, still wanted to point it out just in case. I probably should have put Pass on this one.
