### ISSUE TITLE
Long words in project title will overlap box on cloning project page

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2488]
**General description:** Self-explanatory. View images below.

**live/dev/localhost:** any
**iSENSE Version:** 8.22
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 16.04
**Browser/Version:** Google Chrome - 53.0.2785.101 & Firefox 48.0

**Steps to Reproduce:** 
1. Just type a long word in some part of your project title. 
2. Attempt to clone the project. 
3. Notice how the word will be cut off the box and won't wrap/shrink to fit within the box.

**Associated Images:**
![screenshot from 2016-09-09 13-10-08](https://cloud.githubusercontent.com/assets/19916403/18396289/dbcfb762-7690-11e6-92dc-656d9f87aa63.png)

![crop](https://cloud.githubusercontent.com/assets/19916403/18396657/d72a394c-7692-11e6-8359-3895b12833d8.png)

**Comment by pat-son** [comment]
Testers: Try to clone a project with a really long word in it. Make sure that it does not overflow.

**Comment by doug-salvati** [comment]
Testers: Be sure to deselect all and then just select a few.  Make sure there is padding when there are only a few selected

**Comment by doug-salvati** [comment]
FAILED testing on Chrome 53.0.2785.143 (OSX 10.11.6).
Overlap still occurs.

**Comment by mck529** [comment]
FAILED testing on Chrome 53.0.2785.101 (linux).
Overlapping persists

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.71 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (Ubuntu 16.04).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
