### ISSUE TITLE
Typo in visualizations.css.scss : "whitespace" invalid property

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2489]
**General description:**
Found in line 377 of visualizations.css.scss
"whitespace" is not a valid property. Should be spelled "white-space"
Due to the property being invalid, this line does nothing. 
Line should be either fixed or removed.

**Associated Image(s):**
![whitespacetypo](https://cloud.githubusercontent.com/assets/19916403/18398091/23338c8e-7699-11e6-81ef-3d187fd063fe.png)

**Comment by pat-son** [comment]
Testers: Add a filter on a project and make sure it looks okay.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 53.0.2785.143 (OSX 10.11.6).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (linux).
Filters still display properly

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).
