### ISSUE TITLE
"Failed to create Contributor Key" error message will carry over to other screens

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2490]
**General description:** Upon failing to create a contributor key, there will be an red error prompt at the top of the screen, reading 'Failing to Create Contributor Key', if the user were to use the top bar or the cancel button at the bottom of the screen, the error message will remain at the top of the proceeding screen. 

**live/dev/localhost:** any
**iSENSE Version:** 8.22
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 16.04
**Browser/Version:** Google Chrome  53.0.2785.101 and FireFox 48.0

**Steps to Reproduce:**
1. Create a project, enter the edit screen, and prompt the error message to appear.
(By entering a Key or Name that is more than 40 characters long, or a dublicate Key or Name)
2. The error message should appear at the top of the screen, reading "Failed to Create Contributor Key"
3. Upon seeing this, if you are to click either..
a) the iSENSE logo at the top left which takes you to the home screen
b) the Visualizations link on the top bar
c) the Cancel button at the bottom of the screen
4. The error message should carry over to whatever screen was clicked on.
(Note: Doesn't carry over with any other links)

**Associated Image(s):**
![homescreen](https://cloud.githubusercontent.com/assets/19916403/18443641/ce58c7c2-78e3-11e6-80ec-03f9102e26bb.png)
![project screen](https://cloud.githubusercontent.com/assets/19916403/18443642/cf29cbc4-78e3-11e6-9f75-fdde63201f95.png)
![visscreen](https://cloud.githubusercontent.com/assets/19916403/18443672/e9bf6eda-78e3-11e6-8f7c-43d1d2846acf.png)

**Comment by pat-son** [comment]
Testers: Make sure that you cannot reproduce the above issue anymore.

**Comment by doug-salvati** [comment]
FAILED testing on Chrome 53.0.2785.143 (OSX 10.11.6).
Able to reproduce all the cases mentioned.

**Comment by mck529** [comment]
FAILED testing on Chrome 53.0.2785.101 (linux).
Error continues to carry over upon changing screens.

**Comment by VictoriaAlbanese** [comment]
FAILED testing on Chrome 48.0.2564.116 (linux).
 - still carries over when clicking iSense logo
 - still carries over when clicking visualizations tab
 - still carries over when clicking the cancel button at the bottom

**Comment by mck529** [comment]
Flagged as "In Testing" by mistake. Issue will not be fixed

**Comment by mdibello** [comment]
In addressing another issue concerning contributor keys (issue #2491), it appears that I've accidentally fixed this issue as well. There's no extra code for this fix, so I'll just tie it into the pull request for the other issue (pull request #2558).

**Comment by mdibello** [comment]
For Testers: After causing an error message to appear (if key/value is less than one character, more than 40 characters, or already exists), make sure that when navigating away from the page, the error message does not persist.

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
Works perfectly

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
