### ISSUE TITLE
Failing to create contributor key redirects incorrectly

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2491]
**General description:** Upon failing to create a contributor key, the page will redirect the user to http://isenseproject.org/contrib_keys, this will stretch the UI horizontally, and the "Back to Project" button on the top left will disappear.

**live/dev/localhost:** Any
**iSENSE Version:** 8.22
**Logged in (Y or N):** Y
**Admin (Y or N):** Y

**OS:** Chrome 53.0.2785.101

**Steps to Reproduce:**
1. Create a project, and fail to create a contributor key by either entering a duplicate key/name or a key/name that is over 40 characters, or not inputting anything.
2. Observe that the UI has been stretched and the "Back to Project" button has disappeared.

**Associated Image(s):**
_Before failing to create a key:_

![before](https://cloud.githubusercontent.com/assets/19916403/18444023/862b2240-78e5-11e6-8685-723af4c914bc.png)

_After failing to create a key:_

![after](https://cloud.githubusercontent.com/assets/19916403/18444032/8d74f418-78e5-11e6-8302-35383c426ae4.png)

**Comment by mdibello** [comment]
For Testers: After causing an error message to appear (if key/value is less than one character, more than 40 characters, or already exists), check to make sure that:

- you are not redirected away from the contributor key page
- the UI is not stretched as depicted above
- the "Back to Project" button does not disappear

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
Works perfectly

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
