### ISSUE TITLE
Undefined error message on username edit failure

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2492]
**General description:** Upon failing to edit your own display name, a error message reading "undefined" will appear at the top of the screen.

**live/dev/localhost:** Any
**iSENSE Version:** 8.22
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 16.04
**Browser/Version:** Chrome 53.0.2785.101 and Firefox 48.0

**Steps to Reproduce:** 
1. Attempt to edit your username, and enter something incorrect (less than 4 characters, more than 70, or contains any sort of invalid character)
2. Undefined error message will appear at the top of the screen.

**Associated Image(s):**
![undefined](https://cloud.githubusercontent.com/assets/19916403/18444483/657cf72e-78e7-11e6-9250-20d7c395e247.png)

**Comment by pat-son** [comment]
Testers: Try to reproduce the above bug.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 53.0.2785.143 (OSX 10.11.6).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (linux).
Displays "Failed to edit Display Name" instead of "undefined"

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).
