### ISSUE TITLE
Long words will be cut off in Scatter Plot X-Axis Drop down Menu

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2493]
**General description:** If there is a long continuous string of characters in one of the number fields for a project, when viewed on the left sidebar for x-axis selection, there will be two lines. However, this does not occur on the Y-Axis list. (as seen below) The Y-Axis list uses an ellipsis to avoid overlap, but the X-Axis list created a new line, and the word was still cut off.

**live/dev/localhost:** Any
**iSENSE Version:** 8.22
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 16.04
**Browser/Version:** Google Chrome 53.0.2785.101 and Firefox 48.0

**Steps to Reproduce:**
1. Create a project. Make one of the number fields have a long continuous string of characters.
2. Upload proper data sets so that you are able to view scatter
3. Visualize, and observe that in the X-Axis drop-down menu, there are two lines for the number field with the long word, and that in Y-Axis, it is cut off by an ellipsis instead.

**Associated Image(s):**
![screenshot from 2016-09-12 13-59-11](https://cloud.githubusercontent.com/assets/19916403/18446898/4b197a6e-78f2-11e6-81dc-3358130402ef.png)

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.71 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (Ubuntu 16.04).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
