### ISSUE TITLE
News Titles are unnecessarily scrollable

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2500]
**General description:** On the news page, (http://isenseproject.org/news?page=1) the titles of each particular article are able to be scrolled vertically. However, this is unnecessary, as all of them do not take up more than one line. The titles should not be able to be scrolled unless it is completely neccessary - when the titles actually take up more than one line. 

**live/dev/localhost:** Any
**iSENSE Version:** v8.2.2.
**Logged in (Y or N):** Y
**Admin (Y or N):** Y

**OS:** Ubuntu 16.04
**Browser/Version:** Google Chrome and Firefox
**Note:** Scrollbars are **not visible** on FireFox (see image below), but the title is still **able to be scrolled**.

**Steps to Reproduce:** 
1. Go to the webpage : http://isenseproject.org/news?page=1 
2. Attempt to scroll any of the news article titles.
3. Observe that despite the titles' length, you are able to scroll down.

**Associated Image(s):**
_From Google Chrome:_
![chrome-news-scroll](https://cloud.githubusercontent.com/assets/19916403/18593886/72600856-7c0b-11e6-8ef1-7d321c3330ba.png)

_From FireFox:_
![firefox-news-scroll](https://cloud.githubusercontent.com/assets/19916403/18593892/75aca578-7c0b-11e6-9ba4-d19c537a431e.png)

**Comment by VictoriaAlbanese** [comment]
Not actually an issue.
