### ISSUE TITLE
mobile view improvements - make info and toolbar take up one row

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2502]
In iSENSE mobile, the vis tools info takes up too much of the screen. 

It seems like if we just made the text and icons smaller -- maybe half their size -- we'd be in business?

The key would seem to be getting the row of vis-tab icons to only take up one row.

Going to landscape view isn't really a solution because then there isn't enough room vertically for the vis.

Any ideas? Something simple, that takes the present info about the vis and icons for tabbing, and makes it fit into one row?

**From http://isenseproject.org/projects/1670/data_sets**
![isense_mobile_fullscreen](https://cloud.githubusercontent.com/assets/1038856/18769949/68a7a456-80ff-11e6-9b14-660b935c5e1e.png)

**Same view, but in an App Inventor app**
![isense_mobile_embed](https://cloud.githubusercontent.com/assets/1038856/18769967/89ae4a7e-80ff-11e6-93aa-fa1ba4a66176.png)

**Comment by fgmart** [comment]
So one idea would be, nix the hamburger menu of vis-selection tools, and also nix the info display "Showing N data sets from <projname> <username>"

Just get rid of that nav stuff.

Then you have  row of vis-tab icons, and if they are made smaller, they can fit on one row.

Then, you could switch vis's. That would be valuable, even if you can't dive into configuring them.

**Comment by pat-son** [comment]
Testers: Use the device toolbar (open the console and then hit "Ctrl-Shift-M") to view the page in mobile view. Make sure the vis page looks better in different phone layouts.

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.71 (Ubuntu 16.04.1 LTS).
The mobile view overall is still pretty bad.

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (Ubuntu 16.04).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
