### ISSUE TITLE
Reporting a Bug Broken (not on live)

### ISSUE THREAD

**Issue by VictoriaAlbanese** [isenseDev/rSENSE#2505]
**General description:** When I try and report a bug, I get a routing error from my local version of the site.  I tested it on the live site, and there is no such problem, however, when I try and do it on the dev version of the site, I get a basic iSense error page.  

**live/dev/localhost:** dev and localhost
**iSENSE Version:** v8.2.2
**Logged in (Y or N):** Y
**Admin (Y or N):** Y

**OS:** X11
**Browser/Version:** Chrome 48.0.2564.116

**Steps to Reproduce:** Clicking "report a bug" link in the page footer

3532

**Comment by pat-son** [comment]
This is kind of a non-issue, since you don't need to be reporting bugs from localhost.
