### ISSUE TITLE
Edit Tutorial Page Submit Button Misdirecting

### ISSUE THREAD

**Issue by VictoriaAlbanese** [isenseDev/rSENSE#2506]
**General description:** Edit tutorial page submit button directing to page which does not exist.  This is an artifact of all of the edits made to the tutorials page; in the old page, each tutorial had its own page, while in this one, they are all listed on the same page.  Now that the tutorial-specific pages do not exist, the submit button is trying to link to a bad route.

**live/dev/localhost:** localhost
**iSENSE Version:** v8.2.2
**Logged in (Y or N):** Y
**Admin (Y or N):** Y

**OS:** ubuntu
**Browser/Version:** Chrome 48.0.2564.116

**Steps to Reproduce:** Sign in as an admin, go to the Tutorial Page, click edit a tutorial on any tutorial, and then click the submit button.

**Comment by pat-son** [comment]
Testers: Not everyone needs to test this one. Make sure that the submit button redirects correctly when making a tutorial.
