### ISSUE TITLE
Reporting Bug Feature on website produces incorrect information

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#2508]
**General description:** Reporting a bug will input the incorrect information for the current OS being used. 

**live/dev/localhost:** live
**iSENSE Version:** v8.2.3
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** _X11_ <-- incorrect OS information (was using Ubuntu 16.04)
**Browser/Version:** Chrome 53.0.2785.101

**Steps to Reproduce:** Simply report a bug using the feature at the bottom of the website. Note the OS being incorrect

4855

**Comment by pat-son** [comment]
@mck529 The number at the bottom is the user ID of the user who submitted the issue. As for the OS, what OS are you running?

**Comment by mck529** [comment]
@pat-son 
Oh, okay, I didn't know about the ID.

And I was using Ubuntu 16.04.

**Comment by pat-son** [comment]
Testers: This can be tested without actually submitting a bug report. On the bug report page, use "Inspect Element" to find the hidden form row that lists Browser, OS, and iSENSE version. Make sure the OS listed is at least a little accurate.

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.71 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (Ubuntu 16.04).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
