### ISSUE TITLE
Text on bug report webpage not contained within box

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2509]
**General description:** The text on this page will overlap over the box.
_See image below._ 

**live/dev/localhost:** any
**iSENSE Version:** v8.2.2.
**Logged in (Y or N):** Y
**Admin (Y or N):** Y

**OS:** Windows 10 Pro v1607
**Browser/Version:** Chrome  53.0.2785.116

**Steps to Reproduce:** Simply navigate to the page here.
Note how the text within the boxes will not remain contained at certain screen dimensions.

**Associated Image(s):**
![screenshot_36](https://cloud.githubusercontent.com/assets/19916403/18846626/dbc08f50-83f4-11e6-926d-d7e9a7253a14.png)

**Comment by mdibello** [comment]
**For Testers:** Go to the bug report page and make sure that the text remains in the buttons when the browser window is at different sizes.

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
BUT boxes should be the same height always
