### ISSUE TITLE
Log-in page rework

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2510]
The Google sign-in button can be a bit misleading, as its position can make it seem like you're supposed to enter your Google credentials into the text fields. The Google button should be moved to be next to/above/below the sign-in box.

**Comment by pat-son** [comment]
Testers: Does the new log-in page look nice? Anything look out of place?

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.71 (Ubuntu 16.04.1 LTS).
The login page looks quite nice.

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (Ubuntu 16.04).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
