### ISSUE TITLE
database schema design of project-tagging and -finding

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2512]
Sam and I would like to re-introduce an idea that was in the old iSENSE (isense.cs.uml.edu): project tagging.

The idea is that a project can be tagged with subject-area (math, physics, bio, etc.) and level (elementary, middle, high, college). 

Projects could have an arbitrary number of tags.

Then, you could search for projects that match a given tag.

The idea is that (e.g.) a middle-school math teacher could easily find projects relevant to their teaching.

As a first step, I'd like someone to think through the tech issues (e.g., does the database schema need to be updated, or do we already have this but we're just not using it?).

**Comment by doug-salvati** [comment]
Closing, as this is part of #2567.
