### ISSUE TITLE
Default Category Misleading when Editing Tutorials as Admin

### ISSUE THREAD

**Issue by VictoriaAlbanese** [isenseDev/rSENSE#2517]
**General description:** When editing the tutorials as an admin, the default tutorial category is not what the category was set to, but simply the first category in the list

**live/dev/localhost:** live
**iSENSE Version:** v8.2.2
**Logged in (Y or N):** Y
**Admin (Y or N):** Y

**OS:** linux
**Browser/Version:** Chrome 48.0.2564.116

**Steps to Reproduce:** (1) Login as admin
(2) Go to tutorials page
(3) Click Edit Tutorial under any tutorial
(4) Drop down list of categories is always set to "Getting Started" even if the tutorial is not of that category; this is misleading

3532

**Comment by pat-son** [comment]
Testers: Only test this if you have Admin access.
