### ISSUE TITLE
Account/Logout Links Don't Properly Scale

### ISSUE THREAD

**Issue by mdibello** [isenseDev/rSENSE#2518]
**General description**: When logged into iSENSE, the account/logout links in the upper-right hand corner will overflow off of the top bar to right below. This is hard to see since the text of the account name and logout link are white on the white website background. This bug may only apply to account names greater than a certain length, but I haven't been able to test this.
See image below.

**live/dev/localhost**: any
**iSENSE Version**: v8.2.3
**Logged in (Y or N)**: Y
**Admin (Y or N)**: N

**OS**: Ubuntu 16.04.1 LTS
**Browser/Version**: Chrome 54.0.2840.59/Firefox 49.0

**Steps to Reproduce**: Sign in to iSENSE and decrease the width of the browser, and you will see that the account name/logout link will drop below the header bar before the site scales to the mobile version. 

**Associated Image(s)**:
I've highlighted the account name and logout link for easy visibility.
![accountname-logoutbutton-overflow](https://cloud.githubusercontent.com/assets/22061236/19446155/75b8214c-9465-11e6-8aae-dd93f4118e90.png)

**Comment by mdibello** [comment]
Note: When you decrease the browser width to under a certain size (specifically 992px), your username will now automatically switch to "My Account".

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.71 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (Ubuntu 16.04).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
Could not reproduce original issue, but behavior is as expected
