### ISSUE TITLE
"Cloned From" Field does not Properly Wrap with Long Project Names

### ISSUE THREAD

**Issue by mdibello** [isenseDev/rSENSE#2519]
**General description**: In the project description page, if the project is cloned from another project whose title contains a very long word, then the cloned-from project name does not properly wrap.

**live/dev/localhost**: dev/live
**iSENSE Version**: v8.2.3
**Logged in (Y or N)**: N
**Admin (Y or N)**: N

**OS**: Ubuntu 16.04.1 LTS
**Browser/Version**: Chrome 54.0.2840.59/Firefox 49.0

**Steps to Reproduce**: Log in and create a new project whose title contains a very long word (while staying under the 128 character max). Make sure to use wide characters in the title like M or W instead of l or i. Then when you clone this project, you will see on the project description page for the new project that the cloned-from project name does not properly wrap.

**Associated Image(s)**:
![clonedfrom-wrapping-bug](https://cloud.githubusercontent.com/assets/22061236/19446758/3c9b53d6-9468-11e6-853c-1180028cc99e.png)

**Comment by pat-son** [comment]
There is already a .word-wrap class that you can use, which is the same one that the project title uses: https://github.com/isenseDev/rSENSE/blob/6460837ecc72224d4391eefbd80908b80875d511/app/assets/stylesheets/application.css.scss#L447.

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.71 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (Ubuntu 16.04).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
