### ISSUE TITLE
Project Name with Long Word does Not Wrap Properly in Edit Project Page

### ISSUE THREAD

**Issue by mdibello** [isenseDev/rSENSE#2520]
**General description**: When editing a project with a title containing a long word, the title does not properly wrap.
See image below.

**live/dev/localhost**: live/dev
**iSENSE Version**: v8.2.3
**Logged in (Y or N)**: Y
**Admin (Y or N)**: N

**OS**: Ubuntu 16.04.1 LTS
**Browser/Version**: Chrome 54.0.2840.59

**Steps to Reproduce**: Create a project with that contains a very long word in the title (use wide characters such as W), then go to the edit page. You'll see that the title doesn't properly wrap.

**Associated Image(s)**:
![editproject-titlewraps](https://cloud.githubusercontent.com/assets/22061236/19447330/023cc140-946b-11e6-9cc0-373e7aeb1a58.png)

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.71 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (Ubuntu 16.04).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
