### ISSUE TITLE
Project Deletion Notice of Project Containing Long Word Does not Properly Wrap

### ISSUE THREAD

**Issue by mdibello** [isenseDev/rSENSE#2521]
**General description**: When you delete a project with a long word in the title, the title does not properly wrap in the project deletion notice.

**live/dev/localhost**: live
**iSENSE Version**: v8.2.3
**Logged in (Y or N)**: Y
**Admin (Y or N)**: N

**OS**: Ubuntu 16.04.1 LTS
**Browser/Version**: Chrome 54.0.2840.59

**Steps to Reproduce**: Log in and create a new project whose title contains a very long word (while staying under the 128 character max). Make sure to use wide characters in the title like M or W instead of l or i. Then delete the project, and the in the deletion notice the title does not properly wrap.

**Associated Image(s)**:
![deleteproject-noticewrapping](https://cloud.githubusercontent.com/assets/22061236/19447418/6d29a374-946b-11e6-8d45-eb0734108a0d.png)

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.71 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (Ubuntu 16.04).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
