### ISSUE TITLE
Remove Flash Dependency from Tutorials

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2523]
**General description:**
Flash is not open source.  iSENSE is.  Any Flash dependencies should be removed.

**live/dev/localhost:** live
**iSENSE Version:** v8.2.3 
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Linux
**Browser/Version:** Firefox

**Steps to Reproduce:** Go to tutorials page.  Note flash must be activated.

**Associated Image(s):** 
![remove_flash](https://cloud.githubusercontent.com/assets/1039162/19651961/f6bc5a7a-99dc-11e6-8ee1-3d4ac6b17540.png)

**Comment by pat-son** [comment]
As far as I understand it, YouTube videos in iframes will fall back to Flash if they can't load the HTML5 player, so this might be a PICNIC error. I'll look into it.

**Comment by pat-son** [comment]
I can confirm that this is an issue with your machine. I disabled Flash on my web browser and the videos still load fine using HTML5. You must have an issue using YouTube's HTML5 player.

**Comment by pat-son** [comment]
What flavor of Linux are you running?

**Comment by stowellm** [comment]
@pat-son I think its just an outdated Firefox version (38.4.0) I was on for the time being causing that.  Since this defaults to HTML5 and only falls back to flash then we can close this.
