### ISSUE TITLE
Gravatar does not use HTTPS

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2525]
**General description:** Gravatar does not use HTTPS, so logging into iSENSE causes the security symbol to vanish on some browsers.

**live/dev/localhost:** live
**iSENSE Version:** v8.2.3
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu
**Browser/Version:** Firefox 49.0.2

**Steps to Reproduce:** Go to iSENSE (not logged in).  The browser will display a security symbol.  Log in.  Now the browser will display a warning symbol.

**Associated Image(s):**
![image](https://cloud.githubusercontent.com/assets/17438678/19811472/91ac4462-9cff-11e6-9150-b8126c566788.png)

I'm also a pretty pink princess.

**Comment by pat-son** [comment]
Testers: Make sure Gravatar uses HTTPS now.
