### ISSUE TITLE
reCAPTCHA doesn't actually do anything

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2528]
When we switched over to Devise, the code that verifies the reCAPTCHA was deleted from the user controller and never added back somewhere else. This means that whether the user clicks the reCAPTCHA or not has no effect; you can create a new user without even touching the button.

**Comment by pat-son** [comment]
Testers: Play with the registrations page, make sure that the reCAPTCHA button works and that you cannot create an account without passing.

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.71 (Ubuntu 16.04.1 LTS).
Failing a reCAPTCHA clears form fields.

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (Ubuntu 16.04).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
