### ISSUE TITLE
Long Titles will Overlap on Edit Fields page

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#2532]
Issue submitted by: @mck529

**General description:** When editing a formula field in a project where there are long words involved (either the field titles or the formula field titles), the corresponding text will not wrap properly.

**live/dev/localhost:** live
**iSENSE Version:** v8.2.3
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Windows
**Browser/Version:** Firefox 48.0

**Steps to Reproduce:**
_This issue can be produced in two ways, either by (a) making a formula field with a long title with no spaces, or  (b) having a regular field with the same characteristics._
1(a). Create a formula field for a project, make the title of the formula field be a long word without any spaces.
or
1(b). Create a data field for a project, and make it's title be a long word without any spaces.

2. Navigate to the formula fields page, and make sure you have a formula field created.
3. Click the pencil and paper icon. (If you chose to make a long formula field title, click on the corresponding icon for that field)
4. Observe how the chart displaying the formula field, the reference, and the type, is stretched out so much that it is going off of the screen. 

**Associated Images:**

_Formula Field Name with 128 'W' characters:_

![ahhh](https://cloud.githubusercontent.com/assets/19916403/19937829/1f75df7c-a0f9-11e6-94ba-a6859ed56cf5.png)

_Formula Field with fewer 'W' 's included: (notice the stretched out chart)_

![ahhhh](https://cloud.githubusercontent.com/assets/19916403/19937834/22d2cee6-a0f9-11e6-87f2-3d71e4079343.png)

_Regular Field with 128 'W' characters:_

![ahhhhh](https://cloud.githubusercontent.com/assets/19916403/19938054/0a81d11a-a0fa-11e6-9c28-8b6f71a66607.png)

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
