### ISSUE TITLE
Deleting a media file with a long word will overlap the success notification

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2536]
**General description:** Deleting a media file with a long title will create overlap on the successful deletion message.

**live/dev/localhost:** live
**iSENSE Version:** v8.2.3.
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 16.04
**Browser/Version:** Chrome

**Steps to Reproduce:**
1. Add a media file to a data set.
2. Change the media file's name to be a long string of characters without any spaces.
3. If it is long enough, it will go through the message telling the user that the media file has been deleted successfully.

**Associated Image(s):**

_Upon deleting WWWWW......W.jpg:_
![first](https://cloud.githubusercontent.com/assets/19916403/19940268/7652d33c-a102-11e6-879e-aff573baaf7a.png)

![second](https://cloud.githubusercontent.com/assets/19916403/19940272/7b32134a-a102-11e6-8404-084cd6447063.png)

**Comment by doug-salvati** [comment]
This formatting problem was fixed by a similar issue which has already been merged.
Closing
