### ISSUE TITLE
"Failed to edit Display Name" error message will persist even creating a valid username edit

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2537]
**General description:** 
After making an unsuccessful attempt at editing a username, an error message reading "Unable to edit display name" will appear at the top of the screen.
If the user were to not dismiss this message and actually successfully editing the username, the error message will remain, until it is dismissed manually.

**live/dev/localhost:** live
**iSENSE Version:** v8.2.3.
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Ubuntu 16.04
**Browser/Version:** Chrome

**Steps to Reproduce:**
1. Fail to edit your username (enter less than 4 characters, more than 70, or some invalid characters)
2. Error message should appear, observe that it appeared, of course.
3. Now, actually edit your username to something valid, the error message will not disappear, making it hard to tell if it is valid.

**Associated Image(s):**

_Red Message on top of screen will persist unless dismissed manually:_
![lolol](https://cloud.githubusercontent.com/assets/19916403/19941014/e576b4a2-a104-11e6-8e63-b9c307d3fbc8.png)

**Comment by mdibello** [comment]
It appears that due to the way the error is triggered, via ajaxError, the best solution to this issue is to throw a success message upon success via ajaxSuccess which will overwrite the error message

**Comment by mdibello** [comment]
I almost feel like the username editing should not be on the show user page, but on the edit user page, as that is what best fits with Rails' MVC scheme. So as a result, the person who implemented this error flash had to do it using ajax instead of what's built into rails. Which seems bad to me.

**Comment by mdibello** [comment]
For Testers: Go to your user page. On the left side of the screen, there is a pencil icon which you can use to edit your username. Try to change it to an invalid value (< 4 chars or > 40 chars). An error message should appear. Next, change your username to a valid value. The error message should go away.

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
