### ISSUE TITLE
Histogram density is broken

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2541]
Bar chart width was set to 0. Histogram density needs bars to have widths to show the outlines. 
I already know what needs to be done to fix it:
In [bar.coffee](https://github.com/isenseDev/rSENSE/blob/6460837ecc72224d4391eefbd80908b80875d511/app/assets/javascripts/visualizations/highvis/bar.coffee#L190): change it to
`borderWidth: if configs.histogramDensity then 4 else 0`

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
