### ISSUE TITLE
Filtering out data from Bar vis results in blank bars being drawn

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2542]
**General description:** When you filter out data points, the bars will go away but the labels persist and there's still space allocated on the graph for them.

**live/dev/localhost:** live
**iSENSE Version:** 8.2.3
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Any
**Browser/Version:** Any

**Steps to Reproduce:**
https://drive.google.com/file/d/0ByhfLrDH6PhIYTJLTk1iVll4YnM/view

**Comment by doug-salvati** [comment]
Testers: Make sure the behavior shown in the video no longer happens.

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
Works perfectly

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
