### ISSUE TITLE
Deleting Users doesn't delete their projects; breaks the projects index page

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2543]
Delete the ability from the view, but don't delete the functionality
Admins can still delete users without error.

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
