### ISSUE TITLE
Teacher request: More error bar information

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2547]
What do the error bars mean? We should put that information in the error bar tooltips.

**Comment by doug-salvati** [comment]
Testers: make sure the standard deviation in the error bars looks like it matches the one on the Summary page. Also, make sure "Mean with Deviation" shows up on the tooltip

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
Everything looks fine! 
It would be cool to include the standard deviation itself on the tooltip, though.

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
