### ISSUE TITLE
Bars are too big

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2548]
make the bars smaller
Right now, they are at the default width, which is to fill their container as much as possible. Instead, we should look at the Highcharts options and see if we can give them a maximum width or something.

**Comment by mdibello** [comment]
What we're looking for is a parameter called maxPointWidth. Unfortunately, that was introduced in Highcharts v4.1.8, and we're currently on v4.1.5. I'll be working on a work-around for now, but we should discuss whether or not we want to upgrade Highcharts versions.

**Comment by mdibello** [comment]
**For testers**: Look at a bar chart with more than six bars. Then decrease the number of bars. As the number goes below six bars, the bars should be the same width as the bars are when there are six bars. At six bars and fewer, each bar should take up roughly 1/6 of the graph (3/20 to be precise, factoring in padding).

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
