### ISSUE TITLE
Histogram boxes get too small

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2549]
**General description**: If histogram boxes reach size 1, this is the same as the stroke width, so the histogram looks like a solid white box.

**live/dev/localhost:** live
**iSENSE Version**: 8.2.3
**Logged in (Y or N)**: N
**Admin (Y or N)**: N

**OS**: Any
**Browser/Version**: Any

**Steps to Reproduce**:
Histogram vis on project [866](https://isenseproject.org/projects/866/data_sets/), looking at dissolved oxygen.

**Comment by pat-son** [comment]
Testers: Check out [project 866](https://isenseproject.org/projects/866/data_sets/?vis=histogram). Make sure that you can actually see the histogram.

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
