### ISSUE TITLE
Add help button with instructions for zooming in

### ISSUE THREAD

**Issue by mdibello** [isenseDev/rSENSE#2553]
To increase a user's awareness of how to zoom in, create a dummy zoom-in button that, upon being clicked, creates a pop-up containing instructions on how to zoom in.

**Comment by mdibello** [comment]
Instead of a dummy zoom-in button, it's been decided that a help button will be better.

**Comment by mdibello** [comment]
For Testers: Go to a project->Visualize->Scatter->Tools. You should see a little help icon next to the header "Zoom". Hovering over it should provide a helpful tip on zooming in.

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
This is kind of petty but you say "zoom in" twice in the instructions and once you hyphenate "zoom-in" and once you don't.  Maybe make them consistent with each other?
Looks good though!

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
