### ISSUE TITLE
Increase Code Coverage

### ISSUE THREAD

**Issue by VictoriaAlbanese** [isenseDev/rSENSE#2554]
**General description:** Code coverage under 90%

**live/dev/localhost:** live
**iSENSE Version:** v8.2.4
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** Linux x86_64
**Browser/Version:** Chrome 54.0.2840.71

**Steps to Reproduce:** Run the tests and observe the low code coverage

3532

**Comment by VictoriaAlbanese** [comment]
Testers: no need to test this one, really... it does increase code coverage but there's no way to manually test it.

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
