### ISSUE TITLE
Values become undefined when histogram blocks merge

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2555]
**General description:** When bin size increases, each data point no longer occupies its own block.  The data point will report 'undefined' for the value because it corresponds to many points.  Perhaps it should display the average on the tooltip (full list on detailed tooltip?), or nothing at all.
**live/dev/localhost:** live
**iSENSE Version:** 8.2.4
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Any
**Browser/Version:** Any

**Steps to Reproduce:**  [https://isenseproject.org/projects/34/data_sets/](https://isenseproject.org/projects/34/data_sets/) for example: change bin size to 5 and observe that the serving size is indicated on the tooltip.  Then, change bin size to 100 and observe that serving size is undefined.

![image](https://cloud.githubusercontent.com/assets/17438678/20445475/335ab06a-ada3-11e6-84aa-7a091f36d6f9.png)
![image](https://cloud.githubusercontent.com/assets/17438678/20445446/18114350-ada3-11e6-888b-000d67e147e3.png)

**Comment by doug-salvati** [comment]
Testers: Make bins small and check that the values are shown on tooltip. Then make them large enough to consolidate and make sure that tooltips display the # of items in the bin, instead of an undefined value.

The Fast Food project has good amount of data for testing this.

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
Works perfectly

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
