### ISSUE TITLE
Group by Number Fields Finds No Number Fields

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2560]
**General description:** The Group by Number Field feature on Pie Charts ([#1852](https://github.com/isenseDev/rSENSE/issues/1852)) no longer works.  Selecting this option always reports "No Number Fields", even if a project has several number fields.

**live/dev/localhost:** live
**iSENSE Version:** 8.2.4
**Logged in (Y or N):** N
**Admin (Y or N):** N

**Steps to reproduce:**
[https://isenseproject.org/projects/2683/data_sets/31965](https://isenseproject.org/projects/2683/data_sets/31965)

**Comment by doug-salvati** [comment]
Testers: here's a project I set up to test this: http://dev.isenseproject.org/projects/2843/data_sets

**Comment by doug-salvati** [comment]
FAILED testing on Chrome 62.0.3202.75 (linux).
This breaks timeline period :/

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.0.3 (mac).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 64.0.3282.186 (windows).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 62.0.3202.75 (linux).
