### ISSUE TITLE
Allow pie charts with data sets without number fields

### ISSUE THREAD

**Issue by mdibello** [isenseDev/rSENSE#2561]
To simplify the use of pie charts, we'd like to modify pie charts so that when there are no number fields, the user can still see the chart, though restricted to only the row count view.

**Comment by mdibello** [comment]
For Testers: Create a project with only one field, a text field. Add some data, and then visualize it. You should be able to visualize it as a pie chart. Make sure that under "Tools" the only available analysis type is "Row Count".

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
Works perfectly

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
