### ISSUE TITLE
heat map radius default is smaller than data point marker

### ISSUE THREAD

**Issue by jywarren** [isenseDev/rSENSE#2562]
Hi, just a suggestion -- the heat map feature is really cool, but I noticed that the default radius is 10px, which is just smaller than the marker icon, so to see the heatmap circles, you have to increase the radius. Just thinking perhaps doubling or tripling the default on this line:

https://github.com/isenseDev/rSENSE/blob/master/app/assets/javascripts/visualizations/highvis/map.coffee#L302-L304

Happy to open a pull request for this, the change looks pretty simple. 

Thanks!

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
sure

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
