### ISSUE TITLE
Box and Whiskers

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#2565]
make a new vis for ox and whiskers plot

http://www.purplemath.com/modules/boxwhisk.htm

**Comment by pat-son** [comment]
Testers: Please poke and prod this new feature as much as you can. Report any issues/concerns to me.

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
