### ISSUE TITLE
Report Inappropriate Content

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#2566]
Find a library to check for bad words in usernames, project names, datasets etc.

NOTE: DO NOT KEEP A LIST OF BAD WORDS IN THE REPO

Edit: The direction we're taking with this is just to have a reporting feature

**Comment by theyoyojo** [comment]
How can this functionality be implemented?

Do we want to have a link to a form that sends us an email? That seems like the simplest way to do it.

Where would this link be? Perhaps at the bottom of the page?

**Comment by theyoyojo** [comment]
I wrote some ideas on the whiteboard at around 10:30 on Wednesday 6 December 2017

**Comment by theyoyojo** [comment]
Nearly complete

**Comment by theyoyojo** [comment]
The views have disappeared without a trace.... why git why?

**Comment by theyoyojo** [comment]
It's probably my fault

**Comment by theyoyojo** [comment]
The view is back, now with a border for some reason

**Comment by theyoyojo** [comment]
Cleaning up and getting ready to PR. I just need the correct reporting email addresses.

**Comment by theyoyojo** [comment]
Fixed the infinite send on submission reset page with the ol' bait and switch redirect_to

**Comment by theyoyojo** [comment]
Currently rake'n

**Comment by doug-salvati** [comment]
TESTERS: Let's not spam the account with reports. Joel and I will take care of this one.

**Comment by doug-salvati** [comment]
PASSED testing on Safari 11.0.3 (mac).
