### ISSUE TITLE
Project tags

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#2567]
MAIN IDEA: Be able to add tags to projects.

MAJOR PARTS:

Backend (database)
UI
Frontend
Testing

BACKEND: Add database entry for projects to have tags

UI: 

- Add tags to project tiles on project page (if there are too many tags put a "more" link that expands or something): 
![image](https://cloud.githubusercontent.com/assets/7584536/21653463/43dc8b10-d27f-11e6-8a67-eb71d917f648.png)

- In edit Project page add place to add tags

- Display tags on Project page (somewhere around here):

![image](https://cloud.githubusercontent.com/assets/7584536/21654894/8ecf0e4e-d285-11e6-9dd0-d9c7b612cf85.png)

FRONTEND:

- Add project search functionality for tags (should use existing search):

![image](https://cloud.githubusercontent.com/assets/7584536/21653641/20fede8a-d280-11e6-9d6c-4be0bbc38402.png)

**Comment by pat-son** [comment]
Testers: Poke around with the new feature, make sure it works as intended.
Things to check:

- adding tags (located in the Edit Project page)
- removing tags
- searching by tags

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
You can add repeat tags

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
Let's make them clickable very soon...

**Comment by RistrettoAffogato** [comment]
PASSED testing on Safari 10.0.3 (mac).
