### ISSUE TITLE
Change vis tab through URL query string

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2568]
Should be pretty simple to use a [query string](https://en.wikipedia.org/wiki/Query_string) to change which vis tab is opened first when the page is loaded. It would be similar to how we currently do embed and presentation mode.

**Comment by pat-son** [comment]
Testers: Try to change the active vis tab using the query string.
Example: http://rsense-dev.cs.uml.edu/projects/106/data_sets/?vis=bar
Should work for both saved vises and visualizing a project's data set.

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
It works! However, if you type in a tab that is not available, or just any random string that is not a tab, it goes to the map tab by default.  It would be cool if it would stay on whatever tab you were currently on (but aside from that suggestion everything works fine).

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
