### ISSUE TITLE
Sort-by-name case sensitivity

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2580]
When sorting a BAR graph by Group name, the result should be case insensitive, as is the case for TABLE.
![imageedit_9_8896836888](https://cloud.githubusercontent.com/assets/17438678/22428128/e3eae788-e6d3-11e6-9e06-404b5190e7af.png)
Sort by Group Name just uses the group order, which puts uppercase first.  Either will need to **change so that instead of using default sort it does a case-insensitive sort**, or reconfigure entire group ordering system...

**Comment by pat-son** [comment]
Testers: Make sure that the names are sorted correctly on the bar chart.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
