### ISSUE TITLE
Bin size slider should match current setting

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2581]
The "automatic" slider under Histogram > Tools does not move itself to the corresponding position if the "manual" entry is changed.  This leads to an issue where dragging the slider to the right might not actually make it bigger, which would be the user's assumption.

**Comment by doug-salvati** [comment]
Testers: I think you can figure out what the deal is here...

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
