### ISSUE TITLE
Show standard deviation on bar mean with error tooltip

### ISSUE THREAD

**Issue by VictoriaAlbanese** [isenseDev/rSENSE#2582]
**General description:** For the bar chart, when using the "Mean with error" setting, which shows the error range for one standard deviation, it would be nice if the tooltip reported the standard deviation.

**live/dev/localhost:** live
**iSENSE Version:** v8.2.5
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Linux x86_64
**Browser/Version:** Chrome 54.0.2840.71

**Steps to Reproduce:** Mouse over any bar in the bar chart, making sure under tools that the "Mean with Error" analysis type is set (image showing this below)

![error_prefix_tooltip](https://cloud.githubusercontent.com/assets/12720180/22478952/053d2e1e-e7ba-11e6-9c3e-e1e08c59c9b3.png)

3532

**Comment by VictoriaAlbanese** [comment]
Also removing manual calculation of variance and stdDev from the code and using a function predefined in a separate file

**Comment by VictoriaAlbanese** [comment]
Testers: make sure the standard deviation is being displayed in the bar tooltips and that the upper and lower bounds seem correct for the error bar tooltips.

**Comment by doug-salvati** [comment]
FAILED testing on Chrome 54.0.2840.90 (linux).
Looks like this is what I'm getting...
    Upper bound = value + 2 * stddev
    Lower bound = value

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
New fix passed (latest pull request)

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
