### ISSUE TITLE
HTTP errors when exporting large number of data sets

### ISSUE THREAD

**Issue by mdibello** [isenseDev/rSENSE#2583]
**General description**: When attempting to export data from a project, if there is a large number of data sets (around 700+), then the file(s) will not download, and an HTTP error appears (403/414). Some example projects for which this occurs:

- [http://isenseproject.org/projects/866](http://isenseproject.org/projects/866)
- [http://isenseproject.org/projects/1264](http://isenseproject.org/projects/1264)
- [http://isenseproject.org/projects/864](http://isenseproject.org/projects/864)

A helpful link: [https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error)

**live/dev/localhost**: live
**iSENSE Version**: v8.2.5
**Logged in (Y or N)**: Y/N
**Admin (Y or N)**: N

**OS**: Ubuntu 16.04
**Browser**: Google Chrome, Firefox

**Comment by pat-son** [comment]
This is a similar issue to #2376, and we don't have a good fix for it yet.

**Comment by doug-salvati** [comment]
Combining with #2376 because they must be fixed together
