### ISSUE TITLE
Change Google Play Link on Site

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2593]
Currently it is: https://play.google.com/store/search?q=pub:Engaging+Computing+Group,+UML
Only shows Writer.

You can make it: https://play.google.com/store/apps/developer?id=Engaging+Computing+Group,+UML
Will show all apps published by ECG.

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
