### ISSUE TITLE
Update "Meet the Team" page

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#2599]
http://isenseproject.org/contact

**Comment by fgmart** [comment]
It just occurred to me that this is the perfect Hello World assignment for new team members :)

**Comment by mdibello** [comment]
The team page is a bit outdated and needs the following revisions:
- Add Josh to developers
- Add Chike to developers
- Add Matt to developers
- Add Ashley to developers
- Move Farzeen to Emeritus
- Move Jason to Emeritus

**Comment by mdibello** [comment]
Matthew DiBello
Web Developer
B.S. Computer Science, 2019
Matthew_DiBello@student.uml.edu
https://www.linkedin.com/in/matthew-dibello/

![mdibello](https://cloud.githubusercontent.com/assets/22061236/23180494/9f6c37ce-f83f-11e6-9d8c-a335a96ba940.jpg)

**Comment by mck529** [comment]
Mine is already mostly there, just a few additions

Michael Kusmirek
Web Developer 
[image] 
Undergraduate
B.S. Computer Science 2019
https://www.linkedin.com/in/michaelkusmirek/

Thanks!

![20170221_202243](https://cloud.githubusercontent.com/assets/19916403/23193611/e167813c-f877-11e6-8353-a82f634df261.jpg)

**Comment by chikeabuah** [comment]
Chike Abuah
Web Developer
Graduate
PhD Computer Science 2020
https://www.linkedin.com/in/chike-abuah-8b755846

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
Good luck on PhD Farzeen! =P
