### ISSUE TITLE
limit spreadsheet uploads to 10 MB

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2600]
Last week we tried uploading an 8.2 MB spreadsheet and it worked http://isenseproject.org/projects/2797/data_sets/36434

But then when we tried to import 80 MB it failed. After iSENSE thrashed for more than an hour.

We should protect ourselves by limiting upload size and giving an error if user tries to upload a single data set that is too large.

Important: the error message should include the recommendation: "Maximum upload size of a single data set is 10 MB. Please split your file into multiple pieces and upload them individually."

**Comment by pat-son** [comment]
Do you have an example 80 MB file that I can use to test?

**Comment by fgmart** [comment]
https://drive.google.com/open?id=0B41atXlV0KHKTmNNM2VKVURuRW8

**Comment by tylerpuleo** [comment]
TESTERS: Here's a 10MB file to use for testing

https://drive.google.com/open?id=0B4CQhnSpitbrNDZkbGszMjd0M0U

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
Works nicely

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
Takes awhile to show the message, but gets the job done.

**Comment by RistrettoAffogato** [comment]
PASSED testing on Safari 10.0.3 (mac).
"Maximum upload size of a single data set is 10 MB. Please split your file into multiple pieces and upload them individually." 
Working as intended.
