### ISSUE TITLE
Automatically Reset Defaults if Outdated

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2609]
**General description:**
Creating a project that has a number field and text field, setting the default vis type to pie charts, and then later removing number fields (without changing the default vis type) and attempting to view the vis after entering new text data will make vis unviewable and weird looking.
_See if you can visualize this properly._
http://isenseproject.org/projects/2824

**live/dev/localhost:** live
**iSENSE Version:** v8.3.
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Windows 10 64-bit
**Browser/Version:** Chrome Version 56.0.2924.87 

**Steps to Reproduce:**
1. Create project, with a number field and text field. Enter a few sets of data.
![screenshot_58](https://cloud.githubusercontent.com/assets/19916403/23635146/064b7778-029c-11e7-8837-39561ef3668f.png)
2. Visualize, and set the default visualization type to pie charts, grouping by whatever text field you had created.
![screenshot_54](https://cloud.githubusercontent.com/assets/19916403/23635041/6c13bac6-029b-11e7-80e7-3a6a98ecb852.png)
3. Exit the visualization page, and delete all data set(s).
![screenshot_55](https://cloud.githubusercontent.com/assets/19916403/23635045/6edacaa6-029b-11e7-88f9-ebef631fcf7c.png)
4. Edit data fields, remove the number field you created.
![screenshot_56](https://cloud.githubusercontent.com/assets/19916403/23635046/6fa2a378-029b-11e7-905b-d173830d2ad2.png)
5. Attempt to upload new data sets, with the text field being your only field now.
_I uploaded a one row data set, with a Text Field value of "Bird"_
6. Attempt to visualize the project, it should appear similar to the image below.
![screenshot_57](https://cloud.githubusercontent.com/assets/19916403/23635048/71a72568-029b-11e7-95b5-f426042027b4.png)

(Even upon zooming out and attempting to click on other vis types will result in a blank white screen)
![screenshot_59](https://cloud.githubusercontent.com/assets/19916403/23635267/a4df616a-029c-11e7-92c3-878eff7b87ab.png)
**Also, I can't seem to recover the projects suffering from this issue into anything usable, this issue will persist even when you delete ALL data fields and enter completely new ones.**

**Comment by pat-son** [comment]
This occurs because the default vis options are trying to access a field that doesn't exist anymore. In the "Edit Project" page, there is a button to reset default options. Pressing that button fixes the symptom of the broken vis.
Furthermore, this issue will very rarely happen in practice, as most people don't delete all their data or fields. And even if they did, they could just hit the Reset Defaults button to fix any issues that occur.

**Comment by doug-salvati** [comment]
I think we should automatically reset defaults when the visualization can't be rendered.  The user should not be able to access a broken state.

If I just set up a handler for TypeError exceptions during rendering, we can also handle the case where old visualizations won't open due to the addition of new features.

**Comment by doug-salvati** [comment]
Testers: Follow the "Steps to reproduce" and make sure you get a warning

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
Redirects to 404 page, but still an improvement... will create a new issue

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 60.0.3112.113 (mac).
Redirect to 404 rather than back to page.

**Comment by mck529** [comment]
PASSED testing on Chrome 61.0.3163.79 (windows).

**Comment by VictoriaAlbanese** [comment]
FAILED testing on Chrome 58.0.3029.110 (linux).
Goes to error 404 page instead of where you reset the defaults

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 60.0.3112.113 (Windows 10).
Redirects to 404 page

**Comment by mdibello** [comment]
PASSED testing on Chrome 55.0.2883.87 (linux).

**Comment by doug-salvati** [comment]
Testers: You did this last time, now just make sure (a) it doesn't break the photos vis on every project and (b) redirects to the homepage

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by mck529** [comment]
PASSED testing on Chrome 61.0.3163.100 (Windows 10 x64).

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.0 (mac).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
