### ISSUE TITLE
Icons on mobile view spill into 2nd row

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2612]
With the addition of whisker plot, our row of graphing icons now takes up more than one row. 

Pls fix... Maybe make them smaller? Reduce space in between?

https://goo.gl/photos/k8BNdnGm9rT8EPmq7

**Comment by fgmart** [comment]
Maybe simply hide icons that aren't relevant? Rather than dimming them. Then most of the time it will only be one row.

**Comment by pat-son** [comment]
I already made the tabs smaller [once](https://github.com/isenseDev/rSENSE/pull/2530). They can only get so small before we need to get more creative.

**Comment by fgmart** [comment]
Doug had the idea of putting them in a sidescrolling widget that's exactly one row wide.

I kind of like this.

**Comment by pat-son** [comment]
Good idea, that will be scalable if we add more vises.

**Comment by doug-salvati** [comment]
Testers: Make sure the scrollbar only appears when it is needed. Resize window small enough and test the side scrolling.  Try to test on a mobile device of possible

**Comment by doug-salvati** [comment]
PASSED testing on Safari 9.1.3 (mac 10.11.6).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 58.0.3029.110 (mac).
Checked on iPhone SE as well.

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 58.0.3029.110 (mac).
Checked on Samsung Galaxy S6 Edge Plus as well.
