### ISSUE TITLE
Project tag visual upgrade

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2613]
See here: 
![image](https://cloud.githubusercontent.com/assets/8462638/24305132/4c4800f8-1092-11e7-80e2-8410d116fd58.png)
The tag row at the bottom is pushing other stuff up, which blocks the date. This only occurs for projects with a picture.

**Comment by pat-son** [comment]
Testers: Play around with the new tags. Make sure the toggling works correctly.

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
