### ISSUE TITLE
Downloading a vis as different filetypes

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#2621]
This is just weird. I don't even know what this file is. Users definitely won't.

**Comment by doug-salvati** [comment]
Testers: Try downloading in all three file formats and examine the results on your machine.

**Comment by doug-salvati** [comment]
PASSED testing on Safari 9.1.3 (mac).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 58.0.3029.110 (mac).
Legend overlapping
Table and summary buttons do not work.

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 58.0.3029.110 (mac).
