### ISSUE TITLE
Disable data points does nothing for pie, histogram, or bar

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#2624]

**Comment by pat-son** [comment]
Did you really need to make three separate issues for this? :-/

**Comment by tylerpuleo** [comment]
Haha probably not. I was going through all the vises and didn't realize it
would be a problem on more than one

**Comment by pat-son** [comment]
If only there were a way to edit issues after posting them

**Comment by doug-salvati** [comment]
For these vises, disable data points doesn't work because the data is aggregated (into pie slices, for instance), rather than individually selected points.

We are considering either allowing you to disable a batch of points.  Otherwise we'll take the button away.

**Comment by doug-salvati** [comment]
Batch disabling is not the way to go.  For these vises, the correct thing to do is to uncheck the group.  The Re-enable button should always be up, so I'm closing this issue without removing the disabling controls.  "Disable" will still be grayed out where not applicable
