### ISSUE TITLE
Hyperlinks on Tutorials Not Working

### ISSUE THREAD

**Issue by Dayyvid** [isenseDev/rSENSE#2629]
**General description:**
The hyperlinks on the Working With Timelines and Working With Histograms are not functioning properly.

**live/dev/localhost:**
live

**iSENSE Version:**
9

**Logged in (Y or N):**
Y

**Admin (Y or N):**
N

**OS:**
Ubuntu

**Browser/Version:**
Firefox

**Steps to Reproduce:**
Go onto the Working With Timelines or Working With Histograms PDF under Tutorials. Try to click on the blue hyperlinks.

**Comment by doug-salvati** [comment]
Update made on the admin page, no PR required => closing
