### ISSUE TITLE
Problems with reporting bugs using the website

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2630]
**General description:**
Whether you are a github user or non github user the reporting bugs feature on the website seems to be broken.

**live/dev/localhost:** live
**iSENSE Version:** 9
**Logged in (Y or N):** Y
**Admin (Y or N):** Y

**OS:** Linux
**Browser/Version:** Chrome

**Steps to Reproduce:**
If you try to report a bug by using the link at the bottom of the website page, 
you'll be brought to an area where you can select whether or not you have a GitHub account to use.

If you select that you do have a Github account you'll be brought to the following page:

![asgithubuser](https://cloud.githubusercontent.com/assets/19916403/26313946/6eb00278-3eda-11e7-9b37-3690c16bf5d7.png)

If you select that you don't have a Github account, you'll be brought to a page where you can type in some information about the bug you are reporting. Once you finish and attempt to send in the report, an error will pop up, reading "Bad Credentials", as seen below.

![bugreport](https://cloud.githubusercontent.com/assets/19916403/26313958/76381328-3eda-11e7-8a30-f8b957f0a046.png)

**Comment by doug-salvati** [comment]
[This](https://github.com/isenseDev/rSENSE/blob/master/lib/github_interface.rb#L8) would be the cause of the problem:
```
new_params = {}
    # IMPORTANT #
    # These variables need to be set on the machine that is running the server
    new_params[:client_id] = ENV['GITHUB_ID']
    new_params[:client_secret] = ENV['GITHUB_SECRET']
    new_params[:code] = code
```
@chikeabuah can you help us with this or provide me credentials?

**Comment by doug-salvati** [comment]
Also had to set another variable, it's totally working now
