### ISSUE TITLE
Update link on privacy policy page

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2631]
I got an email from someone who works at the website that generated our privacy policy, and he would like us to change the URL for their website. Here's the email:

> You linked to GeneratePrivacyPolicy.com on this page of your site - http://rsense-dev.cs.uml.edu/privacy_policy. We’ve since migrated to Privacypolicies.com.
>
> Perhaps you’d be able to update the link to our new site?

The old link still forwards to the new website, so it doesn't seem like a huge deal, but it's a 2 second fix so whatever.

**Comment by doug-salvati** [comment]
Thanks @pat-son, this will go in our first summer release ;)
