### ISSUE TITLE
Add compass on Maps Visualization

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2633]
A teacher pointed out that the question on the SOR worksheet about the east-most station is technically ambiguous because there is no compass on the map.

~~Also, consider enabling rotation of the map.~~

**Comment by doug-salvati** [comment]
Testers: Make sure the compass shows up on map and only map.  Make sure its size is appropriate, and try resizing the browser window.

**Comment by doug-salvati** [comment]
PASSED testing on Safari 9.1.3 (mac 10.11.6).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 58.0.3029.110 (mac).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 58.0.3029.110 (mac).
