### ISSUE TITLE
Fix the Photos Visualization

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2647]
GOALS:

- [x] Upload to a data set via the webpage (Manual Entry) in a more intuitive way
       NOTE: There should be a photo for each data *set*, not data *point*!
- [x] Fix photos tab ( photo gallery )
       Use project 221 to test (should work for old and new projects, of course)

**Comment by doug-salvati** [comment]
Testers: Try uploading media to a data set by clicking "Edit" next to its name then check  the photos vis and its grouping options.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).
Seems to not work if there's a space in the file name... but that's ok for now

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 59.0.3071.115 (mac).
