### ISSUE TITLE
iSENSE mailing Group Management

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2648]
Small survey when registering for acct (Google or standard).  For instance, are they a K12/University teacher/student/etc, are they willing to get news from the corresponding mailing list, etc?

Edit: We're starting with just asking them to sign up for the mailing list.

**Comment by theyoyojo** [comment]
We could implement mailchimp, I did it on another website and it was fairly simple

**Comment by doug-salvati** [comment]
Testers: Be wary of actually sending emails as there are many real email addresses on the dev server.  Just make sure you set your subscription choice (either by the pop-up or by creating a new account) and verify can change your subscription choices.  Also make sure the creation page shows up for admins.

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.0.3 (mac).

**Comment by Dayyvid** [comment]
Note: You need to be an admin to send out an email
Also the unsubscribe link in the email sent out when you subscribe takes you to isenseproject.org, not dev.isenseproject.org, so that feature is not testable.

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 64.0.3282.186 (windows).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 62.0.3202.75 (linux).
