### ISSUE TITLE
Stylesheet for emails

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2649]
Design a stylesheet to make our emails (lost password, email confirmation, etc) look professional and not like spam.

**Comment by doug-salvati** [comment]
Testers: Request a password reset for your account and check the email that comes.  Check in browser and on mobile if possible.  If you have an extra email account or throwaway mail, try creating a new user for that email as well.

![image](https://user-images.githubusercontent.com/17438678/27303854-213ddb14-550a-11e7-917a-9a08f0543bb5.png)

**Comment by Josh-Everett** [comment]
FAILED testing on Chrome 58.0.3029.110 (mac).
