### ISSUE TITLE
Contributor Selection Menu is Overlapped

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2652]
**General description:** The menu shown in the image should be above everything else on the screen
![image](https://user-images.githubusercontent.com/17438678/27393553-9fcbb10e-5677-11e7-9861-3e83d217aef7.png)

**live/dev/localhost:** live
**iSENSE Version:** v9.1.0-121-gfff31f3
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Linux x86_64
**Browser/Version:** Chrome 58.0.3029.110

**Steps to Reproduce:** Selecting/deselecting specific datasets using dropdown menu

6105

**Comment by doug-salvati** [comment]
Testers: Open the dropdown menu shown and make sure that nothing is overlapped. Try project 863.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 59.0.3071.115 (mac).
