### ISSUE TITLE
David Nguyen About Us

### ISSUE THREAD

**Issue by Dayyvid** [isenseDev/rSENSE#2654]
Just putting a picture for the about us page

**Comment by doug-salvati** [comment]
PASSED testing on Safari 9.1.3 (mac 10.11.6).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 58.0.3029.110 (mac).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 58.0.3029.110 (mac).
