### ISSUE TITLE
Adding Formula Field causes Indefinite Loading

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2664]
**General description:** Setting up a formula field when not every data point has a value in a field being used causes the user's session to hang.  My suggestion would be to skip the datapoints where this is the case during the calculating.

**live/dev/localhost:** live
**iSENSE Version:** v9.1.0-154-g6a3d6c4
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Linux x86_64
**Browser/Version:** Chrome 58.0.3029.110

**Steps to Reproduce:** Take an existing project, add a few number fields and a new data set that fills them in.  Now try to make a formula field to add the two number fields, and it will be "saving..." indefinitely.

6105

**Comment by doug-salvati** [comment]
Testers: Take an existing project, add a few number fields and a new data set that fills them in. Now try to make a formula field to add the two number fields, and verify it does not say "saving..." indefinitely.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 59.0.3071.115 (mac).
