### ISSUE TITLE
Blurry Tabs on some Browsers

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2667]
**General description:** Text in tabs is blurry on certain browsers 

**live/dev/localhost:** live
**iSENSE Version:** v9.2.0
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** OS X 10.12.5
**Browser/Version:** Safari 10.1.1

**Steps to Reproduce:** Look at the featured visualization

6105

**Comment by doug-salvati** [comment]
Testers: Make sure that the scrollable tabs feature still works.  Particularly if you are on Safari, check that the text/images on the tabs aren't blurry

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 59.0.3071.115 (mac).
Tested on Safari and Chrome
