### ISSUE TITLE
Admins can't "Delete Selected" Data Sets

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2670]
Deleting selected checks if you are the owner before checking if admin.  This should be reversed.

While editing this code, wouldn't hurt to add a field for whether confirmed and a button to toggle on /users

**Comment by doug-salvati** [comment]
Testers: Login as an admin (ask if you need help).  Then, try to delete a bunch of data sets by clicking "Delete Selected" on someone else's project.  Don't delete an important project's data set and NEVER do this on the live server unless the user has asked.

Also try to confirm a user on the users page.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 59.0.3071.115 (mac).
