### ISSUE TITLE
Drag & Drop Media

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2684]

**Comment by doug-salvati** [comment]
Testers: Just drag some image files into the media area of a project & see how it goes

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 61.0.3163.100 (mac).

**Comment by mck529** [comment]
PASSED testing on Chrome 61.0.3163.100 (Windows 10 x64).

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.0 (mac).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
