### ISSUE TITLE
Filter by Date of Upload

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2690]
This feature would be useful becuase it would allow you to show only data that was _uploaded_ during a certain time frame.  It does not depend on a timestamp field.

For instance, if we were showing the [GPS project](https://isenseproject.org/projects/2366) and only wanted to show today's votes, we can easily click to show only datasets uploaded today, even though there is no timestamp field.  This will make it easier for kids to make sense of data in projects like that with a LOT of historical data.

Probably this is best suited for the "Filtering" menu, and could give the options of All, Today, Yesterday, Custom Range...

**Comment by theyoyojo** [comment]
How is this data currently stored? Does it already exist for every data set that has been uploaded?

**Comment by doug-salvati** [comment]
Testers: this feature is self-explanatory and located in the Filtering menu

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.0.3 (mac).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 64.0.3282.186 (windows).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 62.0.3202.75 (linux).
