### ISSUE TITLE
on tutorials page, add tag so YouTube movies don't show recommendations

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2695]
Please add `&rel=0` to all YouTube URLs so that recommendations are not shown.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 60.0.3112.113 (mac).

**Comment by mck529** [comment]
PASSED testing on Chrome 61.0.3163.79 (windows).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 60.0.3112.113 (Windows 10).

**Comment by mdibello** [comment]
PASSED testing on Chrome 55.0.2883.87 (linux).
