### ISSUE TITLE
File upload converter missing from server

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2696]
it gives error:

`Error reading file: No such file or directory @ rb_sysopen - /tmp/rsense/RackMultipart20170911-2715-5412gm.csv`

no problem importing the same data as CSV.

please see attached XLSX and CSV (with TXT suffix to make Github happy)
[fish-by-year.xlsx](https://github.com/isenseDev/rSENSE/files/1294201/fish-by-year.xlsx)
[fish-by-year.csv.txt](https://github.com/isenseDev/rSENSE/files/1294203/fish-by-year.csv.txt)

This is urgent to fix.

**Comment by doug-salvati** [comment]
Issue is that libreoffice is missing from the server, which our code depends on. @chikeabuah and I are going to set up an equivalent for the server and we'll change the source accordingly.

Hotfix is applied for now. XLSX works, CSV works.  XLS and ODS will not for the time being.

**Comment by doug-salvati** [comment]
Testers: try uploading a data set via XLXS, XLS, or ODS

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 60.0.3112.113 (mac).

**Comment by mck529** [comment]
PASSED testing on Chrome 61.0.3163.79 (windows).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).
Passed for xlsx, xls, and ods file types

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 60.0.3112.113 (Windows 10).

**Comment by mdibello** [comment]
PASSED testing on Chrome 55.0.2883.87 (linux).
