### ISSUE TITLE
Pie chart info-text displays the wrong information

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2697]
Check out this saved vis:

https://isenseproject.org/visualizations/1374

It's a pie-chart grouped by a field called "Animal". The pie slices are displayed correctly.

But, the pie is labeled "Years of Teaching grouped by Animal"

There is a field named Years of Teaching in the project.

But why is this showing up in the Pie view? Something is wrong. It's definitely confusing.

**Comment by doug-salvati** [comment]
Typically there is more than one field, you get options to choose which field is plotted:
![image](https://user-images.githubusercontent.com/17438678/30387510-b31104b8-987a-11e7-9a73-93ef6a31554b.png)
Your project only has one field which is numeric, so there are no other options.  Therefore, the fields menu is not shown.
I believe this is not confusing to the user.  If they created the project, they will be expecting the pie chart to use their only numeric field.

**Comment by doug-salvati** [comment]
See #2704
