### ISSUE TITLE
import from Google Spreadsheet seems broken

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2699]
Attempt to import SS (which is properly publicly shared) gives:

`Error reading file: 400 Bad Request`

Here's URL to SS:
https://docs.google.com/spreadsheets/d/1_ynROS1LPQDH4t7evMHdOU510Fl7JwsPNi1-o3iP8X0

Here's the project:
http://isenseproject.org/projects/3069

I downloaded the SS as a CSV and it uploaded fine:
http://isenseproject.org/projects/3069/data_sets/52267

Please investigate...

**Comment by doug-salvati** [comment]
Testers: try uploading the link Fred said didn't work

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 60.0.3112.113 (mac).

**Comment by mck529** [comment]
PASSED testing on Chrome 61.0.3163.79 (windows).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 60.0.3112.113 (Windows 10).

**Comment by mdibello** [comment]
PASSED testing on Chrome 55.0.2883.87 (linux).
