### ISSUE TITLE
Gaps on sides of feature

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2706]
Get rid of those gaps on the left and right of the feature.

![image](https://user-images.githubusercontent.com/17438678/30606751-bda8e2b8-9d40-11e7-9f15-609e9ec0de60.png)

**Comment by doug-salvati** [comment]
Solution is to remove padding from this element 
![image](https://user-images.githubusercontent.com/17438678/32508926-e220c580-c3b9-11e7-9437-1b35cf82042c.png)

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 62.0.3202.75 (linux).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 62.0.3202.94 (windows).

**Comment by mck529** [comment]
PASSED testing on Chrome 62.0.3202.94 (Windows 10 x64).
