### ISSUE TITLE
Libreoffice command has a different name on the server

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2710]
The latest version of Libreoffice which I installed on the server (see the [.ebextensions/deploy.config](https://github.com/isenseDev/rSENSE/blob/master/.ebextensions/deploy.config) file for how it's done) sets up the command `libreoffice5.4`.  However, our [code](https://github.com/isenseDev/rSENSE/blob/master/lib/file_uploader.rb#L83) references simply `libreoffice`, which is the command installed on CircleCI and all new Ubuntu machines.  I think we should make the server version just called `libreoffice` as well.

I have tried adding all the following to the config, to no avail:
`cp /usr/bin/libreoffice5.4 /usr/bin/libreoffice`
`alias libreoffice=libreoffice5.4`
`echo alias libreoffice=libreoffice5.4 >> /etc/profile`

A hotfix is currently applied on isenseproject.org to put the "5.4" in the command [here](https://github.com/isenseDev/rSENSE/blob/master/lib/file_uploader.rb#L83), which makes it fully functional for now...

**Comment by doug-salvati** [comment]
Testers: With this, I set up a symbolic link to libreoffice which means file uploading *should* work immediately after deploy.  Please test uploading a spreadsheet

**Comment by doug-salvati** [comment]
PASSED testing on Safari 11.0.3 (mac).
Symbolic link seemed to work

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.1 (mac).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 65.0.3325.181 (windows).
