### ISSUE TITLE
for mobile view, open vis page with menu closed

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2711]
Is there any way that iSENSE could detect it's on mobile view, and then open by default with the tools menu closed?

this would make it a lot more appealing. see below.

![screenshot_20170930-142540](https://user-images.githubusercontent.com/1038856/31048460-5ee37bae-a5eb-11e7-85e1-dc66c0ab8edf.png)

![screenshot_20170930-142547](https://user-images.githubusercontent.com/1038856/31048461-646affe8-a5eb-11e7-9e29-087d266baa6b.png)

**Comment by doug-salvati** [comment]
Testers: This appears to be already not working for some old projects.  Unless you can think of a reason this is to be expected, you can fail this.

**Comment by VictoriaAlbanese** [comment]
FAILED testing on Chrome 58.0.3029.110 (linux).
nope.

**Comment by Dayyvid** [comment]
FAILED testing on Chrome 61.0.3163.100 (mac).
Tested on Android (Samsung Galaxy S6)

**Comment by mck529** [comment]
FAILED testing on Chrome 61.0.3163.100 (Windows 10 x64).

**Comment by Josh-Everett** [comment]
FAILED testing on Safari 11.0 (mac).

**Comment by doug-salvati** [comment]
FAILED testing on Chrome 54.0.2840.90 (linux).
Tested on iOS.  Needs to override project defaults as well, I'll do that for next release

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 62.0.3202.75 (linux).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 62.0.3202.94 (windows).

**Comment by mck529** [comment]
PASSED testing on Chrome 62.0.3202.94 (Windows 10 x64).
