### ISSUE TITLE
Minimum spelled wrong in Tools

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2712]
Please fix ASAP, including hot patch.
![20171001_122438](https://user-images.githubusercontent.com/1038856/31056693-d694ef3a-a6a3-11e7-9524-934090affb2c.png)

**Comment by theyoyojo** [comment]
Submitted pull request with fix. Single character changed in a single file.

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 62.0.3202.94 (mac).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 61.0.3163.100 (mac).

**Comment by mdibello** [comment]
PASSED testing on Firefox 57.0 (Ubuntu 16.04 xenial).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
