### ISSUE TITLE
bar chart doesn't sort bars properly

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2716]
Check out this project:
https://isenseproject.org/projects/3176/data_sets/

1. Click on Bar, and then Group By > Job Title. 

It should be showing "Number of Jobs in 2014" and bars are sorted from low to high. So far, so good.

2. Now in Y Axis, select Percent Change, and unselect Number of Jobs in 2014.

3. Flip open Tools and it says it's sorting by Percent Change, but it's not.

If you sort it by something else and then come back to Percent Change, it will work.

This should be fixed so that the Tools bar does not change its sort until you tell it to. After doing #2 above, Tools should still be showing that it's sorting by Number of Jobs in 2014.

**Comment by mdibello** [comment]
It looks like the sorting doesn't actually change after step 2, but the drop-down changes to say that it's sorting by Percent Change (even though it's still sorting by Number of Jobs in 2014). To resolve this, we'll need to change what the drop-down says, not how the data is sorted.

**Comment by doug-salvati** [comment]
Testers: try some configurations of a bar chart and make sure the sorting order the drop-down says matches what you already see

**Comment by doug-salvati** [comment]
PASSED testing on Safari 11.0 (mac).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 61.0.3163.100 (mac).
