### ISSUE TITLE
in Tools > Analysis type, change "Total" to "Sum"

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2719]
I think this will make it more clear what it's doing, and distinguish it from Row Count better.

**Comment by theyoyojo** [comment]
Submitted pull request for fix

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 62.0.3202.94 (mac).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 61.0.3163.100 (mac).

**Comment by mdibello** [comment]
PASSED testing on Firefox 57.0 (Ubuntu 16.04 xenial).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
