### ISSUE TITLE
update Formatting Imported Files tutorial written version with Excel formula for timestamps

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2720]
There is an Excel formula that will cause dates and times to be formatted properly for import to iSENSE.

Let's rediscover this and add it to the written tutorial at http://isenseproject.org/tutorials.

**Comment by fgmart** [comment]
Tutorial sources present at https://drive.google.com/drive/folders/0BxpOWxo9TIs2bkliT29JR3pkNjQ

**Comment by doug-salvati** [comment]
This is in tutorial 06, the timestamp format desired is:

YYYY-MM-DD hh:mm:ss.sss [AM/PM] [Timezone]

**Comment by fgmart** [comment]
Here's some material that I wrote. My question is: where can we present this information so that users can readily find it?

In order to get iSENSE to read dates and times correctly, you must format the data in your spreadsheet’s timestamp field a specific way.

If you simply want the year, so special formatting is needed; the timestamp field may contact a 4-digit year.

If you want year, month, and day, it’s necessary to format as `YYYY/MM/DD`.

You can specify this format in Google Sheets by going to Format > Number > Custom Number Format... and then entering `yyyy"/"mm"/"dd" `

If you need hours, minutes, and seconds in addition to the year/month/date, use this format string: `yyyy"/"mm"/"dd" "hh":"mm":"ss`

Microsoft Excel has a similar capability. Use the custom format option and enter: `yyyy/mm/dd hh:mm:ss`

**Comment by doug-salvati** [comment]
I've added this information to the written tutorial as requested.
