### ISSUE TITLE
when Analysis Type is set to Row Count, Y axis label should change to "Count"

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2721]
E.g, see https://isenseproject.org/visualizations/1553

The Y-axis units are set to "Width (cm)".

Which is correct for all of the Analysis Types *except* Row Count.

For Bar Chart and Pie, the Y-axis should simply be "Count" when Row Count is selected.

**Comment by fgmart** [comment]
![from width to count](https://user-images.githubusercontent.com/1038856/31351520-6d13dce0-acf9-11e7-9ae0-e635ee00c40c.png)

**Comment by fgmart** [comment]
![bar-count](https://user-images.githubusercontent.com/1038856/31355348-d4915380-ad07-11e7-8ff9-ca3b2fb174c2.png)

**Comment by doug-salvati** [comment]
Testers: See the images above for what to look for

**Comment by doug-salvati** [comment]
PASSED testing on Safari 11.0 (mac).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 61.0.3163.100 (mac).
