### ISSUE TITLE
Error bars 2 SEM

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2723]

**Comment by doug-salvati** [comment]
Reviewer, see the merged PR above and have a look. Had to merge early

**Comment by doug-salvati** [comment]
Testers: teacher seemed pleased, but check that things work properly without errors and bars look reasonable

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 58.0.3029.110 (linux).

**Comment by mck529** [comment]
PASSED testing on Chrome 61.0.3163.100 (Windows 10 x64).

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.0 (mac).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
