### ISSUE TITLE
Reset Defaults Tutorial

### ISSUE THREAD

**Issue by VictoriaAlbanese** [isenseDev/rSENSE#2726]
This bug is a side project built of of bug #2713.  This bug directs the user back to the homepage if there is an error requiring the user to reset their defaults.  However, the average user may not know how/where to do this (even though it's as simple as a button click).  I therefore propose that we make a new tutorial showing the user how to reset their defaults, add it to the tutorials page, and then either provide the user with the link to the tutorial or send them directly to that tutorial when asking to reset defaults.

To reset defaults, make sure you are logged in first.  Then, go to the project page of the project that you want to set the defaults for.  Go to settings, and then scroll down a bit and click the reset defaults button.

**Comment by doug-salvati** [comment]
Josh made the video, and I've added it to the site.  Once we link to it from that error message, we can close this issue

**Comment by doug-salvati** [comment]
Testers: follow the [steps to reproduce](https://github.com/isenseDev/rSENSE/issues/2609) but make sure this time, the tutorial page is loaded.

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.0.3 (mac).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 64.0.3282.186 (windows).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 62.0.3202.75 (linux).
