### ISSUE TITLE
Limit number of data sets displayed on project page

### ISSUE THREAD

**Issue by mdibello** [isenseDev/rSENSE#2733]
When a project has a large number of data sets, displaying all of them on the project page takes a long time to load, and in many circumstances, may be unnecessary. See [this project](http://isenseproject.org/projects/3177) for a good example.

A good solution to this would be to limit the number of data sets displayed by default (maybe ~50). The data sets could be organized as one long list, which only shows a small number by default, and slowly adds more as the user requests it (with either a "See More" or "See All" button). Alternatively, the data sets could be organized into pages of a reasonable number of data sets (maybe ~50) and the user could go to subsequent pages if they so wish.

**Comment by theyoyojo** [comment]
Not a bad idea
