### ISSUE TITLE
Change stdev formula

### ISSUE THREAD

**Issue by doug-salvati** [isenseDev/rSENSE#2736]
See the pull request at [https://github.com/isenseDev/rSENSE/pull/2728](https://github.com/isenseDev/rSENSE/pull/2728)

**Comment by doug-salvati** [comment]
Testers: Just make sure std-dev still shows up

**Comment by doug-salvati** [comment]
PASSED testing on Safari 11.0 (mac).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 61.0.3163.100 (mac).
