### ISSUE TITLE
Add specific StdDev and SEM to manual test sheet

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2740]
Hey, check out these views of http://isenseproject.org/projects/3177/data_sets/ .

The upper is using **Mean with 2 SEM**, and the lower is using **Mean with Deviation**.

Shouldn't Mean with Deviation be the equivalent of 1 SEM, and then the error bars should be tighter?

![2sem](https://user-images.githubusercontent.com/1038856/32346798-efe8e7c0-bfe4-11e7-9e04-c1541c25eee5.png)

![mean-with-dev](https://user-images.githubusercontent.com/1038856/32346800-f38dbdc4-bfe4-11e7-9d4f-8c340abfaccb.png)

**Comment by doug-salvati** [comment]
@fgmart , you can check out the difference between these on [Wikipedia](https://en.wikipedia.org/wiki/Standard_error#Standard_error_of_mean_versus_standard_deviation) but the moral of the story is that σ ≢ 1 SEM.

Furthermore, SEM ≡  σ / √n , so it _is_ necessarily smaller than standard deviation.

**Comment by fgmart** [comment]
OK this site explains it too: https://www.investopedia.com/ask/answers/042415/what-difference-between-standard-error-means-and-standard-deviation.asp

May I transform this bug report into a request for having test data sets with known SD's and 2 SEMs?

**Comment by doug-salvati** [comment]
Sounds good, we could implement that as a spreadsheet that's not on the site, but we upload at testing time.  This is what we do to test all the values on box-and-whisker plots.

**Comment by doug-salvati** [comment]
Sample data set and values to test have been added to our testing folder.
