### ISSUE TITLE
histogram popup sometimes displays wrong value for data point

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2743]
In this saved vis, there is a data point contributed by Kelsey which has Jumps = 9:

![kelseys-jump-is-9](https://user-images.githubusercontent.com/1038856/32406319-bea1d168-c14c-11e7-8d8b-f43ea5b5d1c0.png)

But when viewed as histogram, the pop-up associated with this data set shows the same value as 12:

![kelsey-12](https://user-images.githubusercontent.com/1038856/32406421-9b426316-c14e-11e7-96ed-f952336db455.png)

The saved vis is https://isenseproject.org/visualizations/1596 and the original project is https://isenseproject.org/projects/3280.

The particular data set which is displaying wrong in the histogram view is https://isenseproject.org/projects/3280/data_sets/59797

**Comment by doug-salvati** [comment]
This value shown in the tooltip is and has always been sourced from the `@point.realValue` variable.  I would do a search for that and see if it's being modified elsewhere in the code, and why

**Comment by theyoyojo** [comment]
I tried to replicate the issue and instead of getting 12 jumps displayed in the histogram view, I got 10. Strange.

![screenshot from 2017-12-04 11-11-59](https://user-images.githubusercontent.com/1909841/33562803-3225edc8-d8e4-11e7-9b38-8d03837c38c6.png)

**Comment by theyoyojo** [comment]
And now with the 2017 timestamp filter removed, I see 12 jumps:

![screenshot from 2017-12-04 11-15-47](https://user-images.githubusercontent.com/1909841/33562925-90107c5a-d8e4-11e7-9e1f-3fd9e4d7f020.png)

**Comment by doug-salvati** [comment]
Testers: there is a copy of this project on the dev machine: search for "Jump Counts new"

**Comment by doug-salvati** [comment]
PASSED testing on Safari 11.0.3 (mac).
Discovered a side issue, that pre-existed this. When loading a histogram immediately after a box plot, the tooltip data is changed.  Likely this has to do with something funky box plot does. Will create a new issue for this.

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.1 (mac).
Passed, noting the issue that Doug has mentioned being replicated here as well.

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 65.0.3325.181 (windows).
Passed, but when you view just Kelsey's point in histogram view, the bin axis scaling issue is extremely obvious, and actually really confusing.  The x-axis implies that there is a bin for every integer, and puts Kelsey's 9 jumps in the 10 bin. The tooltip shows that the bin is correct, but the x axis is very misleading.
