### ISSUE TITLE
http:// needed in url listed for importing aix

### ISSUE THREAD

**Issue by mck529** [isenseDev/rSENSE#2744]
**General description:**
On where the AppVis aix link is listed on the website, it is listed as "isenseproject.org/aix" and tells the user to copy and paste that link to use the aix in the AI2.
However, http:// is needed at the beginning of the link for the extension to properly import, the http:// should be listed on the page as well to avoid any issues.
So, the proper link should be http://isenseproject.org/aix, and that's what should be listed on the page, so avoid problems for users simply copy and pasting the link text rather than the link address. So it's really just a small typo. 
**found on this page:** https://isenseproject.org/appvis

**live/dev/localhost:** any
**iSENSE Version:** v9.6.0
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Any
**Browser/Version:** Any

**Steps to Reproduce:**
There isn't a whole lot to reproduce, but if you attempt to import an extension on App Inventor 2 by using the link:
isenseproject.org/aix , it will produce this message:
![screenshot_102](https://user-images.githubusercontent.com/19916403/32407902-fb1de3e8-c165-11e7-9c1d-073051548b2b.png)
Imports properly when the link http://isenseproject.org/aix is used.

**Associated Image(s):**
![screenshot_101](https://user-images.githubusercontent.com/19916403/32407892-df95a480-c165-11e7-9051-a91f0ef7e0ec.png)
https://isenseproject.org/appvis

**Comment by doug-salvati** [comment]
@mck529 , can I change it to HTTPS or should I change to HTTP?

**Comment by mck529** [comment]
@doug-salvati Both work fine. http:// is just what I got when I used "copy link address" on the hyperlink on the webpage, so that should work fine.

**Comment by theyoyojo** [comment]
What if we had a button to copy the link to the clipboard? I'm going to try and implement that.

**Comment by fgmart** [comment]
+1

**Comment by theyoyojo** [comment]
Submitted a fix for review

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 62.0.3202.94 (mac).

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 61.0.3163.100 (mac).

**Comment by mdibello** [comment]
PASSED testing on Firefox 57.0 (Ubuntu 16.04 xenial).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
