### ISSUE TITLE
Differing box sizes on homepage

### ISSUE THREAD

**Issue by theyoyojo** [isenseDev/rSENSE#2745]
At page width ‘w’, where 991 < w < 1200, The “AppVis” box is longer than the rest of the boxes. See screenshot

![screenshot from 2017-11-03 13-02-29](https://user-images.githubusercontent.com/1909841/32558265-5c1fa4ec-c472-11e7-9262-fc058192730b.png)

**Comment by Josh-Everett** [comment]
PASSED testing on Chrome 61.0.3163.100 (mac).

**Comment by mdibello** [comment]
PASSED testing on Firefox 57.0 (Ubuntu 16.04 xenial).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
