### ISSUE TITLE
Rails server must be run on localhost for recaptcha to work

### ISSUE THREAD

**Issue by theyoyojo** [isenseDev/rSENSE#2750]
Rails server must be run on localhost for recaptcha to work

Running with -b <local_IP_address_of_server> causes ERROR for site owner: Invalid domain for site key.

![screenshot from 2017-11-03 11-19-09](https://user-images.githubusercontent.com/1909841/32565153-3b9ce3f8-c484-11e7-93b6-27d97ffb1e4b.png)

**Comment by doug-salvati** [comment]
Recaptcha requires signing up and getting a key for your domain.  As a result, it only works on isenseproject.org and localhost and probably will stay that way.  Is this pressing?

**Comment by theyoyojo** [comment]
Yeah this is probably not too important.
