### ISSUE TITLE
Deleting all data sets allows for broken visualization

### ISSUE THREAD

**Issue by Josh-Everett** [isenseDev/rSENSE#2756]
Normally if we delete all data sets by choosing the delete selected option on the projects page the project refreshes and we are not allowed a visualization with 0 data sets. However if we delete all of the data sets individually we are allowed to visualize 0 data sets which is just a broken vis.

Screenshots:
[ 1 ]
<img width="1220" alt="screen shot 2017-11-13 at 11 24 35 pm" src="https://user-images.githubusercontent.com/11084059/32762916-65ddc778-c8ca-11e7-8b6c-0b0715630768.png">

[ 2 ]
<img width="697" alt="screen shot 2017-11-13 at 11 25 11 pm" src="https://user-images.githubusercontent.com/11084059/32762917-69b640f0-c8ca-11e7-9811-a6c71665b913.png">

[ 3 ]
<img width="1390" alt="screen shot 2017-11-13 at 11 25 23 pm" src="https://user-images.githubusercontent.com/11084059/32762919-6dbf38c8-c8ca-11e7-87a2-8f963645d6ce.png">

**Comment by doug-salvati** [comment]
PASSED testing on Safari 11.0.3 (mac).

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.1 (mac).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 65.0.3325.181 (windows).
