### ISSUE TITLE
Registration name must be 4 characters minimum, however, some people have three letter names.

### ISSUE THREAD

**Issue by theyoyojo** [isenseDev/rSENSE#2761]
Sam, Jon, Bob, Ann, Amy, Tim, Jan

Etc

**Comment by theyoyojo** [comment]
Found it in models/user/rb Line: 12 Character: 39

**Comment by theyoyojo** [comment]
#2762 fixes this by changing that character from '4' to '1'

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 62.0.3202.75 (linux).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 62.0.3202.94 (windows).

**Comment by mck529** [comment]
PASSED testing on Chrome 62.0.3202.94 (Windows 10 x64).
