### ISSUE TITLE
A rake test uses the param per_page=1 

### ISSUE THREAD

**Issue by theyoyojo** [isenseDev/rSENSE#2766]
I don't know if this is problematic or intentional, but is certainly behavior that is not generally requested by the user. I don't know what the test is doing so I cannot make any further comment.

`{"per_page"=>1, "format"=>"json", "controller"=>"users", "action"=>"index"}
.  test_should_get_index_paged                                     PASS (0.01s)`

**Comment by theyoyojo** [comment]
Considering that this param was just added in my pagination code, I strongly lean towards this being unintentional behavior.

**Comment by doug-salvati** [comment]
@theyoyojo This test you're referring to tests the admin's Users page which has always been indexed, hence `per_page` was preexisting.
