### ISSUE TITLE
Improve appearance of comparison operators in Table view, so it's evident they're clickable

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2780]
The numeric and string comparison operators in Table view do not look like clickable objects:
![image](https://user-images.githubusercontent.com/1038856/33787463-4bdb380e-dc3b-11e7-8d3c-206bdf3be043.png)

They should be updated to look like a clickable thing.

**Comment by doug-salvati** [comment]
Testers: Check that operators look clickable and X button only shows up when you typed something.

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.0.3 (mac).

**Comment by Dayyvid** [comment]
PASSED testing on Chrome 64.0.3282.186 (windows).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 62.0.3202.75 (linux).
