### ISSUE TITLE
misspelling in email notification screen

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2809]
Should be "receive"

![selection_261](https://user-images.githubusercontent.com/1038856/36876646-f991fdc8-1d83-11e8-8366-3a223fb095c5.png)

**Comment by fgmart** [comment]
The welcome email which is sent out has the same misspelling.

**Comment by doug-salvati** [comment]
Hotfix is live, @Dayyvid feel free to make the pull request since you're assigned.  Be sure to search for all instances of the word.

**Comment by doug-salvati** [comment]
Testers: If you have an old account on dev machine that has never chosen a subscription preferences, you can test this.  Otherwise, no big deal.

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 65.0.3325.181 (windows).
