### ISSUE TITLE
Data filtering

### ISSUE THREAD

**Issue by mmcguinn** [isenseDev/rSENSE#413]
Ability to "hide" data not currently visible in the vis. This will be for cross-vis usage.
Will enable the functionality described in #1090.

Finally, the UI interface for this might be similar to regressions, and might be titled "data filters."

**Comment by bdonald25** [comment]
Testers: Try to break filtering. This will require thorough testing of all the visualizations.

**Comment by jaypoulz** [comment]
omg it's really going to be a thing. I think I'm tearing up. :sob:

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).
minor issues:
* filtering by text fields puts NaN in the top part with the list of filters (filtering still works though)
* "contains" is case-insensitive in table and case-sensitive in filtering

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).
