### ISSUE TITLE
Time format changes

### ISSUE THREAD

**Issue by mmcguinn** [isenseDev/rSENSE#416]
Long term "LT [num]" -> "[num]"
Unix time      "[num]" -> "U [num]"

**Comment by pat-son** [comment]
Why tho

**Comment by mmcguinn** [comment]
@pat-son It's uh, a little odd to be asking a question on a issue that's been closed for three years. 

That said, I'm pretty sure I remember the issue was that we had exactly zero people using unix timestamps (outside of our own hardware) and there was a bunch of interest in long-term yearly data sets by people (or maybe even a single person) who could neither excel nor script their way out of a wet paper bag, and thus had trouble with the prefix.

**Comment by pat-son** [comment]
@mmcguinn The reason I ask is because it seems pointless to prepend timestamps with a U, and that's causing issues right now. It's easy enough to fix it (strip the U), but why do we have APIs uploading timestamps with 'u's in front?

**Comment by mmcguinn** [comment]
@pat-son Because there are two numeric time formats that are supported. Numbers prefixed with 'U' are unix timestamps, other numbers (which before the commit linked here were prefixed with 'LT') are a year only, intended for long term datasets like ice core samples. As a bit of trivia - the long term times can often end up getting interpreted as integers by the vis because it's quite easy to underflow javascript's date representation when you are talking about millions of years.

You cannot tell the two formats apart without some kind of marker, hence the 'U'. My previous reply explains why the unix format was given the prefix rather than the long term format.

**Comment by pat-son** [comment]
@mmcguinn That's the part I don't really get. What's the point of having two different formats for time? If someone wants long-term data, they can just as easily use UNIX timestamps. If they only care about the year, then just fill in whatever they want for the other parts.

**Comment by mmcguinn** [comment]
@pat-son There's a couple factors at play here, which I have already mentioned briefly. First and foremost - most users (at least when I was working on the project) have no idea what a millisecond Unix timestamp is, never mind any idea of how to get their data into it. because of that, and given that "years" is a pretty common timestamp value for pre-existing datasets like the ice core samples I mentioned previously, we added the ability to simply use an integer number of years as a timestamp. I'll also note here that in such datasets it's pretty common for the precision to be well larger than even a year - so it's pretty misleading to store it in a format that includes months, nevermind days, minutes, or seconds.

Looking further - the parser for dates that are either unix timestamps or one of the textual supported formats relies solely on the javascript date object, The main issue here is that the javascript date object has a rather small usable range of time (compared to the age of the earth/universe), see [the spec](http://ecma-international.org/ecma-262/5.1/#sec-15.9.1.1).

The point you brought up about using unix timestamps (though I'm not clear on what you mean by "then just fill in whatever they want for the other parts" as unix timestamps are a single number) is completely valid from a technical perspective. I even did some math and determined that doing it that way with double precision numbers you maintain at least one year of accuracy until you get to ~ 4.5 quadrillion years, which is pretty good. The reason it wasn't done this way is both because of the issues with user-imputed data (including that from other scientific sources) and because highcharts has nice features for time series data, and time series data for highcharts means it fits in a javascript date object. 

You could pretty easily extend the unix timestamp interpreter in iSENSE to conditionally support large unix timestamps as numbers like the long term format does (if someone hasn't done it already since this commit was made) if that's a requested feature, but the need to support the formatting in existing scientific data remains.

**Comment by pat-son** [comment]
I guess I understand in context, but it's completely pointless now because we have the Date/time picker for Manual Entry, and on a CSV, the user can just put "1/1/[year]" for the dates and it works fine.

**Comment by mmcguinn** [comment]
@pat-son That's actually not true. Both those things will fail on dates outside of the javascript date range - just verified this myself as it's been quite a while. Manual entry simply won't validate such dates, and they show up as invalid on csv upload.

See this [project](https://isenseproject.org/projects/205)
Try to upload this file [test.zip](https://github.com/isenseDev/rSENSE/files/260604/test.zip) and check out the dates on the data table.
You can also try entering one of those dates from the csv into manual entry - they complain about being invalid.

**Comment by fgmart** [comment]
@pat-son For one of our users, who was interested in projects that represented geological time (or astronomical time), Skittles developed the time format whereby if you did not have the "u" prefix, the value represented an integer year with a huge possible range (much larger than is representable by Unix timestamp values)

So if we get rid of the "u", we lose that. 

I think that's what's going on here?

**Comment by bdonald25** [comment]
I bet ruby's DateTime object has similar limitations to javascript's, so formula fields will probably need to be modified to handle that format too.

**Comment by mmcguinn** [comment]
@fgmart Essentially yeah. It would be possible to add support for unix timestamps that fall outside of the normal javascript date range, it would simply need to detect and switch to 'GeoTime' mode on the timeline the same way that the long term format does. Basically that turns the timeline into a line chart where the 'time' axis is actually just a number to get around highchart's (and javascript's) limitations.

@bdonald25 AFAIK Ruby's 'DateTime' object stores all the fields separately, and thus can support pretty much any date you want. The 'Time' object though is a traditional unix timestamp underneath (using decimal values for fractional seconds rather than javascript's approach of using milliseconds as the baseline), and would have similar issues. Of course if said DateTime had to get moved back into javascript later (into vis for instance), you'd have to tackle the same problem then anyways.
