### ISSUE TITLE
Filter data sessions

### ISSUE THREAD

**Issue by AlanRosenthal** [isenseDev/rSENSE#776]
like this:
![image](https://f.cloud.github.com/assets/1288897/1221228/f0e7c618-26e7-11e3-9c7e-6a84f59cdb97.png)

**Comment by bdonald25** [comment]
Testers: Search for a data set on a project and make sure that the search functionality is working correctly.

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
PASSED testing on Firefox 40.0 (linux).
