### ISSUE TITLE
Uploadable zip files

### ISSUE THREAD

**Issue by AlanRosenthal** [isenseDev/rSENSE#915]
We should be able to upload a zip file of datasets (where each file is a dataset).

The reason for this is that you can download a zip file of datasets, so it only makes sense that you can upload it again.

**Comment by bdonald25** [comment]
Testers: Upload zip files with valid data sets make sure everything works. Also, try to break it with invalid files such as images, ect.

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
PASSED testing on Firefox 40.0 (linux).

**Comment by AlanRosenthal** [comment]
About time

**Comment by Evana13G** [comment]
LMAO alan @AlanRosenthal
