### ISSUE TITLE
In Saved-Vis view, need to be able to click on vis icon to get to saved vis

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#977]

**Comment by fgmart** [comment]
@stowellm we talked about this yesterday. This isn't in the build yet -- is this issue open somewhere else?

@kcarcia please comment too?

Thanks

**Comment by stowellm** [comment]
Addressed once #1925 is finished and merged.

**Comment by stowellm** [comment]
Will be addressed when #2008 is merged.

**Comment by kcarcia** [comment]
TESTERS: Go to the Vis index page. Verify clicking the images takes you to the respective vis.

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.115 (linux).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.115 (mac).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 40.0.2214.115 (linux).
